### ISSUE TITLE
Reflection_Engine: ExtensionMethods to return all available methods

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1002]
Currently the `ExtentionMethods()` method only returns methods with exact type matching for the first argument. This can be a problem when wanting to write methods for interface types that you want to be accessed by the `RunExtentionMethod()`.

As an example, the following method

```
        public static ICurve Geometry(this IFramingElement framingElement)
        {
            return framingElement.Location;
        }
```

is never hit, as the actual type will be `Beam`/`Column` etc.

One solution would be to change the type check on line 45 from `==` to `IsAssignableFrom`.

https://github.com/BHoM/BHoM_Engine/blob/18fd2606dd551b4b3e4785e5a30fbbfebfd1dfd1/Reflection_Engine/Query/ExtentionMethods.cs#L37-L49

A problem with this though is that it would mean you could end up with multiple returns, for cases where someone had implemented a specific method for for example the `Beam` class.

This could be handled by sorting the methods to the "closests" as c# does automatically. Thas is, if you provide a beam, you will get two methods returned, sort them out by "closeness" and call the method for the beam. If you provide a column you will only get the method for the `IFramingElement` returned, hence call that.

Please let me know if you have any comments on how/if this change should be made.

**Comment by FraserGreenroyd** [comment]
Discussion in BHoM call:
@IsakNaslundBh to do the heavy lifting, but after chat with @adecler to discuss implementation/framework.
To be attempted to be achieved within the next week.
