### ISSUE TITLE
Reflection_Engine: BHoMTypeList() To include interface types

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1003]
After some of the restructuring of the physical classes and heavier reliance on interface types, we will want to be able to access interface types from the UI.

An example is pulling elements from various packages. After the migration and split of framing element into multiple sub-classes, they now share the base interface `IFramingElement`. Wee need to be able to create a filter query asking for all `IFramingElements` in the UI's, which currently impossible.

Could we simply add interface types to the BHoMTypeList(), or are there any code structural resons why they need to be kept out?

**Comment by adecler** [comment]
Check the dependencies on that method but I think the `BHoM_UI` is already relying on the fact that `BHoMTypeList()` is only returning types you can instantiate. It might be better to add a `BHoMInterfaceList()` method instead.
