### ISSUE TITLE
Environment_Engine: IsIdentical rounding

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1013]
currently Environmental Method `IsIdentical` compare all available digits up to 16 decimal places, in grasshopper it display up to 6 decimal places and it return false even if all GH digit are the same.
We should implement tolerance or rounding input that will round point digit to specified accuracy. This will allow easier identification of equalization. 

![image](https://user-images.githubusercontent.com/26113670/59381396-28556d80-8d53-11e9-8563-a600ac7fb98b.png)

![image](https://user-images.githubusercontent.com/26113670/59380946-2dfe8380-8d52-11e9-91d5-c924c2ef6563.png)

![image](https://user-images.githubusercontent.com/26113670/59381443-47ec9600-8d53-11e9-90c9-7e094754f054.png)

**Comment by rwemay** [comment]
FYI if you want to change the tolerance/units in Rhino/Grasshopper - type 'units' in Rhino or go through the options menu. When you 'recalculate' the Grasshopper script it should update the solution with the updated unit tolerance. 

This is something we've had to toggle when working with highly complex structural or energy analytical models to get the right geometry tolerance for the engineering platforms (particularly for doubly curved nurb surfaces for example). 

I would also just check that this 'IsIdentical' method is specific in its application/definition - the name implies it will check all properties etc, whereas if it's only checking geometry, would it not be better to have a modellaundry IElement2D specific method?

**Comment by michaldengusiak** [comment]
Agreed I just found and tested `Geometry Query` and seems is doing what I need,
I guess we modify later on panel `IsIdentical `to include data and property. 
I guess will use `IsEqual `method right now 

![image](https://user-images.githubusercontent.com/26113670/59382008-a2d2bd00-8d54-11e9-83fa-fbac6f02497a.png)

**Comment by rwemay** [comment]
Cool, yeah I think any object comparers are going to be much higher level in the framework than on an object by object basis. Particularly with some of the work @alelom / @al-fisher  and others are doing around adapter upgrades and diffing.
