### ISSUE TITLE
Environment_Engine: Query PanelsByGeometry to support Point 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1017]
Currently method `PanelsByGeometry` works for ICurve, can we include also `Point` or make seperate function to support PanelsByPoint

[test script here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1017%20PanelByPoint?csf=1&e=7jJaPD)

![image](https://user-images.githubusercontent.com/26113670/59428432-1a483100-8dd5-11e9-8e21-f7ece78cc8a7.png)

![image](https://user-images.githubusercontent.com/26113670/59428455-321fb500-8dd5-11e9-9c24-e5524e1832fa.png)

**Comment by FraserGreenroyd** [comment]
You have `PanelsContainingPoint` which takes a list of panels as an input and a single point to find the panel which contains the search point. Does this not achieve what you're after?

**Comment by michaldengusiak** [comment]
yes, thanks
