### ISSUE TITLE
Environment_Engine: Query AdjacentSpaces

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1025]
allow this method to work for one input: panels

**Comment by FraserGreenroyd** [comment]
What would this query return? A list of the connected spaces? If so, what's wrong with exploding the panel you want and using the `ConnectedSpaces` property from there?

If you're after the panels that enclose the space the input would require the additional panels to run that, in which case the existing query method should work?

**Comment by FraserGreenroyd** [comment]
Closing as nothing further heard, assuming that suggested method suits the needs. If this still needs work feel free to reopen or raise a new issue with more information :smile:
