### ISSUE TITLE
Geometry_Engine: Query Inside Polyline, Polycurve

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1026]
Do we have method existing solution that returns any point inside Polyline, Polycurve?
I do not want to test it, we have this method, I just want to get a point. 
![image](https://user-images.githubusercontent.com/26113670/59569618-273e7c00-9084-11e9-86ca-8a124373f36f.png)

**Comment by rwemay** [comment]
Try IsContaining methods.

**Comment by michaldengusiak** [comment]
Yes, I know this one. This is check that returns True/False and I need point without need for guessing and iterating to get point inside. 

<img src="https://user-images.githubusercontent.com/26113670/59584474-0a329900-90d6-11e9-82eb-836ba4cc8e01.png" width=300>

**Comment by rwemay** [comment]
Ok, not sure I understand sorry! Can you explain the use-case? Do you want a method that just returns points that are outside rather than bools?

**Comment by michaldengusiak** [comment]
this is part of Topologic workflow. I need point that is inside space. So I can extract floors than use BooleanUnion to merge floors into one polyline(polycurve Dynamo) and then want to get point that is inside. Need Inside method, that I will use this as Location point to find cell from Topologic that will be mapping link between BHoM and Topologic. They implemented method find cell by point.  In addition when, in future we push to Revit, this is all we need space location point. So this will be multipurpose function.

**Comment by michaldengusiak** [comment]
I guess workaround could be if I have tessellate/triangulation method. I could take triangular from polyline, polycurve and then take first one and get centroid.

**Comment by rwemay** [comment]
Ah, sorry, I think I understand now(?) When you create a space (generate rather than pull from some other software) you need to construct/define a 'location point' and the location point should have some default rules as to how/where it's defined, one of them being that the location point should always(?) be inside the space?

**Comment by pawelbaran** [comment]
There is a `Centroid` method in the Common_Engine - is that what you are looking for? The only issue would be concave regions, where there is a risk the point will lie outside...

**Comment by michaldengusiak** [comment]
I tested `Centroid ` and is outside so does not work,
ok, looks we need new method as we do not have currently good solution
![image](https://user-images.githubusercontent.com/26113670/59591455-ed9e5d00-90e5-11e9-98dc-b6177c809a7c.png)

**Comment by epignatelli** [comment]
Do you need to _test_ for containment, or do you need to _generate_ a new poi inside the region?

**Comment by michaldengusiak** [comment]
@epignatelli  I need to _generate_ a new point inside polyline, polycurve. 
![image](https://user-images.githubusercontent.com/26113670/59592148-5e924480-90e7-11e9-84ae-392343438ef4.png)

**Comment by rwemay** [comment]
@epignatelli , I think we need to _generate_. As such, I think the solution is to use Centroid, but wrap this in a specific engine method to generate a location point of a space. It will need to check if the outline IsContaining the centroid point and if it's not, move it to a point inside/use an alternative point. The simplest would be to use a point _on_ the outline curve, however, I don't think that will work as there will likely be coexisitent/colinear adjacent space curves.

**Comment by pawelbaran** [comment]
As a temp solution you can use Populate2D or PopulateGeometry in-built method in GH.

**Comment by michaldengusiak** [comment]
@pawelbaran seems that they will not work on L shape polyline, polycurve and we might need to get rectangular region pull point and test each one... we need a better and simpler method in BHoM so we can use also in Dynamo ..
![image](https://user-images.githubusercontent.com/26113670/59592890-cf862c00-90e8-11e9-896f-4184323756b5.png)

**Comment by pawelbaran** [comment]
Create a BoundarySurface from the L shape polyline, then populate geometry. Must work if the input curve is correct, I did it many times.

**Comment by michaldengusiak** [comment]
@pawelbaran thanks,  this works as temporary solution, 
Can you replicate the same in `BHoM Query Inside` and will do the same and later on we can work on better looking point :)
![image](https://user-images.githubusercontent.com/26113670/59593706-54be1080-90ea-11e9-88af-ce93aef3cf00.png)

**Comment by michaldengusiak** [comment]
ok I run lots of tests on our template and here is conclusion:
we need new function `Query Inside ` that will work for panels:
1. try to get `Centroid `
2, Check IsContaining 
3. if _fail_ should use Populate Geometry from Boundary Surface
this will work for all cases and guarantee good quality point that we need

@FraserGreenroyd @pawelbaran @LMarkowski is this something achievable? or to difficult and complex and need different approach?

<img src="https://user-images.githubusercontent.com/26113670/59597332-7b337a00-90f1-11e9-9b56-72055ded3644.png" width=300>
<img src="https://user-images.githubusercontent.com/26113670/59597344-7ec70100-90f1-11e9-871f-ec08795b9123.png" width=300>
<img src="https://user-images.githubusercontent.com/26113670/59597351-85557880-90f1-11e9-8ef2-31d55c3d2963.png" width=300>
<img src="https://user-images.githubusercontent.com/26113670/59597360-8a1a2c80-90f1-11e9-9282-e00523c3cfb9.png" width=300>

**Comment by rwemay** [comment]
This is sounding good. As an aside/further check it might be worth pulling some Revit spaces and checking what the rule Revit uses to create space location points (assuming it does so?). Not that we should rely on Revit/standards, but good to know what an existing package uses as a default 'location point' for an environmental space.

**Comment by pawelbaran** [comment]
What comes to my mind as an easy to go with solution:
- if the panel is triangle/circle, take the centroid
- else start drawing the diagonals, return first midpoint of a diagonal that lies inside the panel outline

Can be heavy, but the implementation would be very simple.

**Comment by michaldengusiak** [comment]
@pawelbaran 
sounds good, let's start with your proposal
 I will change ...tag
