### ISSUE TITLE
Structure_Engine: Add Bar.SetGeometry(Polyline) method for 2-node polylines

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1028]

**Comment by pawelbaran** [comment]
@IsakNaslundBh is that still relevant? Should we push it to 3.2?

**Comment by IsakNaslundBh** [comment]
Sneaked this in to #1547

**Comment by pawelbaran** [comment]
Oke, then I am happy to unassign myself and leave handling of this issue to you
