### ISSUE TITLE
Environment_Engine: Get Unique Space Names from Panels

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1037]
Get Unique list as input for `ChangeAdjacentSpaces`

**Comment by rwemay** [comment]
You should be able to use 'Create Set' in Grasshopper (and equivalent in Dynamo) for this - if you just want a list of unique names from a longer list(?)

**Comment by FraserGreenroyd** [comment]
There is a `UniqueSpaceNames` component in `Environment.Query` which takes a list of `Panels` and returns all of the unique space names they are connected to - would this solve it?

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  yes will test this, 
in input for `ChangeAdjacentSpaces` names order matter?

**Comment by FraserGreenroyd** [comment]
Correct, order matters. There should be some simple GH/Dynamo components to sort alphabetically though given the space naming conventions used :smile:

**Comment by michaldengusiak** [comment]
do they need to follow panels order ?
