### ISSUE TITLE
Environment_Engine: Fix SpaceCentres

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1046]
wrong point for our method SpaceCentre method:

![image](https://user-images.githubusercontent.com/26113670/59799020-5dc20400-92db-11e9-94b6-2486d5abd924.png)

[test file here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1046%20Fix%20SpaceCentres?csf=1&e=QQohUR)

**Comment by FraserGreenroyd** [comment]
Please provide more information about what exactly is wrong - what is the exception being given, what is the error you're receiving, and what is the answer you'd expect to see? :smile:

**Comment by michaldengusiak** [comment]
I got it :) updated description...method is SpaceCentre and left hand side space centre is outside space. 
I guess method should be `SpaceBoundingBoxMassCentre` so it works fine above, I would expect  `SpaceCentre` to be inside for all spaces
