### ISSUE TITLE
Environment_Engine: panel unusual behaviour 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1056]
I place noew node see below and works when I connect to existing node it does not work
![image](https://user-images.githubusercontent.com/26113670/59932727-bc07f780-943f-11e9-8e03-7e0476f299d7.png)

when I connect again lower level does not work anymore
this must be related to my Revit question
https://github.com/BHoM/Revit_Toolkit/issues/326

![image](https://user-images.githubusercontent.com/26113670/59932831-fd000c00-943f-11e9-83fc-6474097bcc3a.png)

**Comment by FraserGreenroyd** [comment]
This isn't related to anything done by the Environment Engine. At best, it is either a reference problem, or an issue with the Grasshopper_Toolkit, or BHoM_UI. At best I'd recommend raising a question on the Grasshopper_Toolkit, see if anyone else is having similar issues and investigate from there :smile:
