### ISSUE TITLE
Geometry_Engine: PointinRegion dynamo error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1065]
not sure why but this method does not work in dynamo
![image](https://user-images.githubusercontent.com/26113670/60280189-595ca300-98fa-11e9-9c9c-ac3f25f47fad.png)
@ZiolkowskiJakub @IsakNaslundBh

**Comment by pawelbaran** [comment]
Same as in #973, this looks like an issue in Dynamo_Toolkit, would rather move it to https://github.com/BHoM/Dynamo_Toolkit

**Comment by pawelbaran** [comment]
Closing as the method works fine in the Geometry_Engine, it is definitely Dynamo_Engine issue.
