### ISSUE TITLE
Reflection_Engine: Should not have "X is stored in Custom Data" for CustomObject properties

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#1081]
#### Description:
Those notes are confusing when exploding a custom object:

![image](https://user-images.githubusercontent.com/16853390/60571263-d7f78b80-9da5-11e9-845c-a00fcdcec5fe.png)

#### How to replicate:

Explode any custom object

#### Expected behaviour:
Should not show those notes since all properties are in CustomData for a custom object

**Comment by adecler** [comment]
@epignatelli , also note that the first output of the explode is called 'object' instead of Category. Not sure how it happens or if you are aware of it. It goes away if I re-plug the first input of CustomObject.

**Comment by epignatelli** [comment]
More than confusing, it is excessively verbose, agreed - even though it is clearer.

> @epignatelli , also note that the first output of the explode is called 'object' instead of Category. Not sure how it happens or if you are aware of it. It goes away if I re-plug the first input of CustomObject.

Yeah, I am aware of this one! I haven't looked into it yet - that's a pretty weird one.
