### ISSUE TITLE
Environment_Engine: How to export DaylightSpacePerimeter

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1084]
How do we export our DaylightSpacePerimeter? It does not works with our File Adapter
@tg359 

![image](https://user-images.githubusercontent.com/26113670/60646790-205d8a80-9e34-11e9-9445-17cd80a998f8.png)

[TestFileHere](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1084%20ExportDaylightSpacePerimeter?csf=1&e=XSgKm6)

**Comment by rwemay** [comment]
It looks like you’re trying to push text into a BHoM object input which push requires. You would need to make a file object and push that. Easier just to export the text using grasshopper components though - either right click the yellow panel and select ‘stream contents’ or use write file.

**Comment by michaldengusiak** [comment]
@rwemay 

thanks
![image](https://user-images.githubusercontent.com/26113670/60647417-97475300-9e35-11e9-9d04-6408953b0323.png)
