### ISSUE TITLE
Geometry_Engine: BooleanUnion bug

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1096]
#### Description:

`BooleanUnion(List<Polyline>)` bug found.

#### How to replicate:

Test file added.

#### Expected behaviour:

Should work 🐒 

#### Test file(s):

Uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1096%2DUnionBug).

**Comment by FraserGreenroyd** [comment]
> #### Expected behaviour:
> Should work 🐒

🤣
