### ISSUE TITLE
Geometry_Engine: ControlPoints() on openings gives duplicate points

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1098]
For example, if using ControlPoints() on a rectangular structural panel opening, it returns 8 points. Presumably relating to the 4 edge curves/lines. Not sure if this is expected behaviour given the edges are separate, but the engine method could join curves/remove duplicates possibly?

**Comment by FraserGreenroyd** [comment]
Do you have an example file @rwemay for reference? I've not noticed similar happening with environment panels but would be keen to double check! :smile:

**Comment by rwemay** [comment]
No sorry, I've already modified the method I was using to get the line rather than control points.

**Comment by FraserGreenroyd** [comment]
Fair enough, I'll take a look with some environment panels tomorrow to check if it's happening there as well and see if this can be replicated/isolated :smile:

**Comment by Tom-Kingstone** [comment]
Checked now with both Structural and Environment panels, and could not replicate. In fact, it currently produces the correct number of control points for a closed `PolyLine` when querying the control points of both panels and their openings (5 points for a PolyLine with 4 corners). Assuming that this issue has been solved in the time between opening and this review, I am closing this issue as completed.
