### ISSUE TITLE
Base_Engine: RandomObject hangs indefinitely for certain Types

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#1104]
### Description:
Computing `RandomObject` with certain Types hangs Rhino indefinitely.

Execution gets trapped in this loop:

![image](https://user-images.githubusercontent.com/6352844/61524440-5d1daa00-aa0e-11e9-8391-494d724c2645.png)
https://github.com/BHoM/BHoM_Engine/blob/05bfd768bf544899d6ddd60795d3b81b551538b2/BHoM_Engine/Create/RandomObject.cs#L227-L228

If you leave Rhino running, after a minute or so it crashes.

<img src="https://user-images.githubusercontent.com/6352844/61526874-301fc600-aa13-11e9-9ce3-d1173cb1cee5.png" width=250>

### How to replicate:
I have encountered this with types in the `Structure` namespace.
For example, just try to create a `Structure.Elements.Bar` randomobject:
![image](https://user-images.githubusercontent.com/6352844/61524563-95bd8380-aa0e-11e9-8198-44333b459eb3.png)

### Additional comments
Random object **does** work with other Types, such as `Geometry.Line` and `Geometry.Point`.

However, I never got it to work with objects in the `Structure` namespace (here it crashes after switching the input to  `Structure.Elements.Node`):
<img src="https://user-images.githubusercontent.com/6352844/61524821-25fbc880-aa0f-11e9-8ed9-d62b275dabb0.png" width=200>

**Comment by adecler** [comment]
Tested today different types of structural element, left GH open for a while and also checked that the line of code mentioned was not being triggered in a loop.
So I think we should close this one since it's been 3.5 years and reopen it only if the issue appears again.
