### ISSUE TITLE
Geometry_Engine: Add Distance methods for Line, Arc, Circle, PolyLine, PolyCurve

### ISSUE THREAD

**Issue by KonradStolarski** [BHoM/BHoM_Engine#1133]
#### Description:

As a support issue to other toolkits, I add an issue here to add Distance methods for Line, Arc, Circle, Polyline and Polycurve (as in title).

**Comment by pawelbaran** [comment]
@KonradStolarski please change the name of the issue to include a relevant suffix (in this case it is _Geometry_Engine: _)
