### ISSUE TITLE
Structure_Engine: Make sure bar extrusions work for all types of Bars

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1147]
#### Description:

Bar extrusion currently has problems with any curved shape. Is currently relying on Nurbs for transforms, which are were removed from the geometry engine

Two options to get this solved:
1. Reimplement Transform methods for nurbs #764  as well as NurbsForm methods for all curves #1148 
2. Turn the section outlines in to polylines, before transform

@rwemay @pawelbaran

**Comment by al-fisher** [comment]
Good one - I would say we just implement #764 as the preferred option. As you highlight there - is just updating control points - not too fiddly!

**Comment by pawelbaran** [comment]
I think the 1st option sounds more reasonable, taken into account the fact that we have the code ready - agreeing with Al 👍

**Comment by IsakNaslundBh** [comment]
Realised the NurbsForm method had been removed as well. They will also be needed. Have updated the issue description. The code for these also already exists on the same old PR.

Do you both still agree with option 1 @al-fisher @pawelbaran ?

**Comment by al-fisher** [comment]
For translation and rotation transformations - I would suggest we do not convert primitive geometries into NurbsForm. Is that not right?
Then if at all possible - and certainly all that is needed for the scope of this issue, simple linear (bar) extrusion - lets focus on just enabling translate for all curve types.

**Comment by al-fisher** [comment]
Would suggest making smaller more specific issues on types of transformations - so we can easily phase development, and support the critical (and simplest) translate only first. @IsakNaslundBh @pawelbaran does that make sense?

**Comment by pawelbaran** [comment]
Makes perfect sense to me (was wondering a long time ago whether we should convert to nurbs any curve under any transformation). However, I would leave the last word to @IsakNaslundBh, depending on how urgent this is to him.

**Comment by IsakNaslundBh** [comment]
@al-fisher, for the nurbs transformations, the way this was implemented before (and I personally think is the best way to implement it as, but can of be convinced otherwise) is to simply implement the transform method for a generic transformation matrix. This method can then be used by translate/scale/rotate etc. by constructing the appropriate transformation matrix. For rotations we at least already have the code to do this and it is generally how it is done right now for most geometries.
Would agree to have something separate for translations though after second thought.

For the Bar extrusions, it is currently implemented by mapping between coordinate systems, i.e. it is not implemented as a series of rotations and translations, but instead the full transformation matrix is constructed and then applied as a single transformation to all the curves. So for this to work as-is, without a big re-write, general transformations would be needed.

@pawelbaran for curved geometries, for general transformations I would agree with this.

**Comment by al-fisher** [comment]
> So for this to work as-is, without a big re-write, general transformations would be needed.

I see.
Taking a quick look at `Bar.Extrude` - I think we do need to simplify approach a little - I can now really see why you have separated out the two options above 1. or 2.
 The methods in BH.Engine.Structure.Query.Extrude are doing a couple of things. I think we should do a simple separation of the `Extrude` (our BHoM definition is nice and simple - just a cross section and a vector axis) and then Convert from `Extrude` to `Mesh`. 

Our `Bar.Extrude` can therefore return a `BH.oM.Mesh` not `IGeometry`. Simplifies the scope of the bar extrude issue.
Does that make sense @IsakNaslundBh ?

**Comment by al-fisher** [comment]
The work to close this then becomes simple - ensure we can `Translate` all cross-sections curves.
Implement convert `Extrude.ToMesh`. This method will translate the section curve along its own axis and then make simple mesh faces - faceting the extrusion for wobbly geometry.

**Comment by al-fisher** [comment]
Option to then raise further issues and complete the work to ensure we can create Surface (or Rhino equivalent Brep) extrusion.

**Comment by epignatelli** [comment]
From the Sprint Closure call - this will be solved in the 2.5 milestone, since it is related to #1148

**Comment by IsakNaslundBh** [comment]
Think this can be safely closed now that Transformations for nurbs as well as checks for arcs anbd circles have been added to the transform method in Geometry_Engine
