### ISSUE TITLE
Geometry_Engine: Re-enable NurbsForm for curves

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1148]
#### Description:

For general transformations for arcs and circles the simplest way is to turn them into nurbs curves and perform the transformations on those.

Previously NurbsForm methods were culled out #748
Proposing to bring them back

**Comment by epignatelli** [comment]
From the Sprint Closure call - this will be solved in the 2.5 MVP milestone
