### ISSUE TITLE
Geometry_Engine: Add MergeLine

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1151]
#### Description:

Add MergeLine
Allow merging two Lines, iCurves with tolerance input

![image](https://user-images.githubusercontent.com/26113670/63841506-d5b34700-c97a-11e9-827b-90b0ec117232.png)
![image](https://user-images.githubusercontent.com/26113670/63841525-de0b8200-c97a-11e9-83f1-b1178aa62faf.png)

**Comment by michaldengusiak** [comment]
ok, this method will work fine just inputs need clear description, I will add this to current PR

![image](https://user-images.githubusercontent.com/26113670/63855040-65b2ba00-c996-11e9-904e-5cc4d4c0a43f.png)

**Comment by pawelbaran** [comment]
@michaldengusiak shouldn't this be resolved by using `BooleanUnion(List<Line>)`?

**Comment by michaldengusiak** [comment]
this is solved now, 
will be closed with open PR I just adj description, this is a bit different approach here
