### ISSUE TITLE
Environment_Engine: Fix CleanPanel

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1152]
#### Description:

Currently, the panel might have many short segments that cause unnecessary delay in simulation. The current function is not fixing this example. 
New method will find `IsCollinear`, `MergeLine `and then `SetGeometry `can be used to update panels

![image](https://user-images.githubusercontent.com/26113670/63841960-a7823700-c97b-11e9-9cc5-80348e25d3ce.png)
![image](https://user-images.githubusercontent.com/26113670/63841970-acdf8180-c97b-11e9-8a8b-018887b036e8.png)

![image](https://user-images.githubusercontent.com/26113670/63854057-27b49680-c994-11e9-91ae-5b4e1bb31e5b.png)

**Comment by FraserGreenroyd** [comment]
Assigning me but @MajaLindroth will work on this.

@michaldengusiak can you provide a test file for this work and an enhanced description of the issue please :smile:

**Comment by michaldengusiak** [comment]
@MajaLindroth 
please find here [test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1152%20CleanPanel?csf=1&e=qi5MJa)
