### ISSUE TITLE
Geometry_Engine: Expose tolerance in Query Normal

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1157]
#### Description:

Currently, we use  default tolerance
![image](https://user-images.githubusercontent.com/26113670/64158802-0ab71200-ce31-11e9-9593-b983484a8e21.png)

I need the flexibility to adjust and decrease tolerance,
 therefore, we need to expose tolerance input
![image](https://user-images.githubusercontent.com/26113670/64158773-fbd05f80-ce30-11e9-85bd-7a47318d3f70.png)

**Comment by Majalindroth** [comment]
Tried some workflows and had a problem with the tolerance when exporting XML files. This issue needs to be fixed.
