### ISSUE TITLE
Environment_Engine: Create Panel by Curve

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1158]
#### Description:

Add two create object method
Create  Panel by Curve
Create Panels by Curves

**Comment by FraserGreenroyd** [comment]
There is no need for this method, we have a single create method for `Panel` within `BH.Engine.Environment.Create` which takes, as an argument, the `ExternalEdges` of the `Panel`. If a curve is being used to create a `Panel`, you should first convert the `Curve` to `Environment.Edge` with the `ToEdges` method. If the `Curve` you're using does not have a `ToEdges` method, you can collapse it to a polyline first and try that, or raise an issue to create additional `ToEdge` methods.
