### ISSUE TITLE
Environment_Engine: Modify Panel properties

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1159]
#### Description:

All to copy, use data between panels

Modify Panels
- [ ] openings
- [ ] construction
- [ ] type
- [ ] Name
- [ ] Fragments

I guess we could add as separate nodes and all together to provide max flexibility

**Comment by FraserGreenroyd** [comment]
Having reviewed this issue again today I am still not clear on what is needed by the description, and wonder if we're erring towards a panel that ends up being like [Trigger's Broom](https://www.youtube.com/watch?v=56yN2zHtofM) whereby the panel has been modified to the nth degree to the point it's no longer possible to be the same panel at all.

At that point I would advocate for creating a new panel with changed data and `exploding` the existing panel to obtain any properties that should remain the same.

With regards to each individual check box, we do have the following methods:
 - Openings - `SetOpenings` allows us to modify the openings of a panel
 - Construction - `SetConstruction` allows us to change the construction of a panel
 - Type - `SetType` allows us to change the type of a panel
 - Name & Fragments - `SetProperty` from within the core BHoM Engine would allow us to modify these properties of a panel

On the information provided, I think this resolves the issue raised - however, if this is a misinterpretation please do feel free to reopen with more information :smile:
