### ISSUE TITLE
Environment_Engine: Tilt bug

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1165]
#### Description:

When we have wall with tilt 90deg due to our tolerance could like that 
![image](https://user-images.githubusercontent.com/26113670/64355683-89f74200-cff9-11e9-9599-f5a1599a8e66.png)

this is causing wrong element selection
 
![image](https://user-images.githubusercontent.com/26113670/64355630-75b34500-cff9-11e9-99c2-e1f9dd054da4.png)

#### How to replicate:

run test file

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-1165%20TiltBug?csf=1&e=95kqiS)

**Comment by michaldengusiak** [comment]
OK, I found and added the second example, 
Tilt should be around  90 

![image](https://user-images.githubusercontent.com/26113670/64421495-9df28080-d099-11e9-8c03-05eff071e72e.png)

![image](https://user-images.githubusercontent.com/26113670/64421621-e611a300-d099-11e9-9041-8dd9a26d6fe0.png)


added to samples

**Comment by michaldengusiak** [comment]
I believe if we have more than 4 vertices we should create additional planes and compare values and get one with max tilt..this will protect from selecting point along one edge

**Comment by FraserGreenroyd** [comment]
What happens if we clean the polyline using the `CleanPolyline` method of the panel before trying to query its tilt? Does that resolve the issue for having more than 4 vertices?

**Comment by michaldengusiak** [comment]
OK, we solved this with @KonradStolarski, 
small adj to current `DiscontinuityPoints ` code but adding `AngleTolerance` this now protect and return better points to avid this situation... will add this to current PR
![image](https://user-images.githubusercontent.com/26113670/64423394-5ae6dc00-d09e-11e9-8d0e-b25d09576c5c.png)
