### ISSUE TITLE
Structure_Engine: Compute, Convert, and Properties folders methods documentation

### ISSUE THREAD

**Issue by FredericBourgeon** [BHoM/BHoM_Engine#1179]
#### Describe the documentation issue:
- [ ] Various methods are not documented

#### What is missing/incorrect?
Code attributes are missing from methods in the Compute, Convert and Properties folders of the Structure_Engine.

**Comment by IsakNaslundBh** [comment]
Will close this as this is mostly handled after https://github.com/BHoM/BHoM_Engine/pull/1547
