### ISSUE TITLE
Environment_Engine: Bug Openings

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1183]
#### Description:

I am connecting BHoM objects, panels but can not see any openings
![image](https://user-images.githubusercontent.com/26113670/64649769-7b53c500-d415-11e9-8e9e-ab7f32e0ece9.png)

#### How to replicate:

run script

#### Expected behaviour:

return list of openings

#### Test file(s):

[test script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environmnet_Engine-Issue-1183-Openings?csf=1&e=3Vf4ed)

**Comment by rwemay** [comment]
If you explode the polyline output is there anything there? (Is is a viz problem or an object problem?).

**Comment by michaldengusiak** [comment]
sorry maybe it was not clear... I want to show that I do have openings and just visualise them using explode and Polyline... but when I connect `Openings` which should take any BHoM Object that have openings like a panel - it does not work.. and the list is empty,,,

**Comment by michaldengusiak** [comment]
we need to adj description...or make it more clear
![image](https://user-images.githubusercontent.com/26113670/64679478-b8e73b00-d473-11e9-80a2-846bae9b9956.png)

**Comment by FraserGreenroyd** [comment]
That description is not part of the component housed by the Environment Engine. Plus the description above it clearly states `generic BHoM objects`. Closing as non-issue.
