### ISSUE TITLE
Reflection_Engine: Create Type from string throws exceptions rather than recording errors

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#1193]
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/688ac3c77e6a9e7ce5e9a14c96a50eaedb797009/Reflection_Engine/Create/Type.cs#L35-L52
This method is throwing exceptions rather than logging BHoM events.
This breaks the UI side.

#### How to replicate:

1. Use this pr https://github.com/BHoM/Grasshopper_Toolkit/pull/402
2. Instantiate a `Create.Type(string name)` component
3. Use "this is not a type" string as input
4. A Grasshopper error will popup

#### Expected behaviour:

Exception should be recorder with `Reflection.Compute.RecordError`.

@adecler @IsakNaslundBh is there any reason why we are throwing an actual exception in this case?

**Comment by IsakNaslundBh** [comment]
Agree with @adecler , can't see any reason either.
