### ISSUE TITLE
Serialiser_Engine: There is already a discriminator convention registered for type System.Object.

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#1194]
#### Description:

At Grasshopper startup, the Serialiser_Engine is used to build the objects tree.
Although, it seems like we are trying to register a convention for `object` , but it already  has one. 
This exception is thrown at every startup of the UIs.
![image](https://user-images.githubusercontent.com/26899347/64780251-cd046880-d557-11e9-9570-abc4f3fe62d3.png)

#### How to replicate:

Load Grasshopper while attached to a debugger.
Make sure that in the `Exception Settings` you have all the CLR Exceptions set.

#### Expected behaviour:

BHoM initialisation should not throw exceptions.

**Comment by adecler** [comment]
@epignatelli , I cannot reproduce this issue even with all CLR exceptions selected. 
Since this is a fairly old issue, can you test this again?

**Comment by epignatelli** [comment]
I cannot reproduce this as well right now.
I will close for now, and reopen in case we experience it again.
