### ISSUE TITLE
Environment_Engine: Tilt bug

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1197]
#### Description:

it returns 90deg which is wrong is more around 45deg
@pawelbaran as you mention it could relate to  Geometry.Engine plane... I am attaching example 
![image](https://user-images.githubusercontent.com/26113670/64790819-9ede5300-d56e-11e9-8f90-b46bc375fcb1.png)

Attached example

#### How to replicate:

run script

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environmnet_Engine-Issue-1197%20TiltBug?csf=1&e=xXuiGl)

**Comment by pawelbaran** [comment]
The issue seems to be that the method analyses first 3 point of a polyline, which may be collinear and consequently return nulls. A quick fix could be to `RemoveLeastSignificantVertices` or work on the whole throughout the whole process.

**Comment by michaldengusiak** [comment]
@pawelbaran thanks for great call will run some tests .. locally

**Comment by rwemay** [comment]
Not sure 3 point check is the best/most robust, although I _think_ @pawelbaran 's suggestion will work (although depends on tolerance - could be 3 points incredibly close to each other such that the issue persists). In the past we've move away from 3 point check and used a fit plane of the control points - may be more robust?

**Comment by pawelbaran** [comment]
Probably obvious to us all, but worth mentioning: performance difference between 3 point check and `FitPlane` should be negligible, especially taken into account the overhead that GH/Dynamo drops on us OOTB.

**Comment by FraserGreenroyd** [comment]
I would agree with you @rwemay may be the best solution for the bug when investigated properly in the next sprint :smile:

**Comment by michaldengusiak** [comment]
I run a few tests and have this on my branch...it is working fine with `FitPlane`, I will push this branch so the test can be run by others as well

**Comment by FraserGreenroyd** [comment]
@michaldengusiak I've just taken a look at the branch you've pushed and that does appear to fix the problem, so I'm happy to see a PR on that if you want to raise one :smile:

A great result from the collaboration of all of us in this thread (I say all of us like I'm trying to claim some credit but transparency of GitHub proves it was the three of you really :wink: ).
