### ISSUE TITLE
Geometry_Engine: IsContaining returns true incorrectly when tolerance is changed

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1214]
#### Description:

I have here an example where the opening was picked by panels and is quite far, ...
![image](https://user-images.githubusercontent.com/26113670/65278831-d5930b00-db24-11e9-959a-af33e2cbf709.png)

[test script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environmnet_Engine-Issue-1213%20AddOpening?csf=1&e=Fdc7n0)

**Comment by MajaLindroth** [comment]
Had a look at this issue and after some investigation traced it back to the IsContaining method in the Geometry Engine. 
I have isolated the specific opening and panel and the IsContaining component shows true for them. 

Seems to be an issue on the Geometry_Engine and I am forward it to @pawelbaran 

[Test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FEnvironment%5FEngine%2FEnvironmnet%5FEngine%2DIssue%2D1214%20AddOpening)

**Comment by FraserGreenroyd** [comment]
Thanks @MajaLindroth - great work on isolating where the error was coming from. I have updated the issue title and reassigned to @pawelbaran for his review/input of your test file! :smile:
