### ISSUE TITLE
Environment_Engine: NormalAwayFromSpace bug

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1217]
#### Description:

I manage to isulate case with 3 panels that normals is wrong. 

as you can see current surface order is correct
![image](https://user-images.githubusercontent.com/26113670/65421970-0f059800-ddfd-11e9-9448-bcce6df9ff4c.png)

we wrongly recognize this in `NormalAwayFromSpace ` method and flip
I manage to internalize neat example
@pawelbaran would be happy to get your feedback on this to get method more rigid for special cases

#### Expected behaviour:

this polyline in the example should return `True`

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environmnet_Engine-Issue-1217%20NormalAwayFromSpace?csf=1&e=FzZoNd)

**Comment by FraserGreenroyd** [comment]
Unassigned @michaldengusiak as issue solver @MajaLindroth and I are looking into this today :smile:
