### ISSUE TITLE
Engine_Explore: delete this project

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#1234]
#### Broken rules:
The name is not compliant and the code seems to be stale.

#### Suggestions to restore compliance:
delete the project and folder

**Comment by adecler** [comment]
Also delete Engine_Test while at it

**Comment by epignatelli** [comment]
I would add also:
- BHoM_Engine_Legacy
- MachineLearning_Engine
- StadiaCrowdAnalysis_Engine

**Comment by FraserGreenroyd** [comment]
`Engine_Test` has been deleted already since this issue was raised :smile:

**Comment by adecler** [comment]
waiting for https://github.com/BHoM/BHoM_Engine/pull/1344 to be merged as it modifies the sln file.

**Comment by FraserGreenroyd** [comment]
That was good timing on #1344 being merged then :smile:
