### ISSUE TITLE
Geometry_Engine: avoid converting arcs and circles to nurbs on Transform when not necessary

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1236]
#### Description:
At the moment arcs and circles are converted to nurbs when any transformation is done on them, which leads to many `NotImplementExceptions` afterwards. Conversion could be avoided in most cases (as long as the curve is not scaled nonuniformly). A simple if statement that checks the transform matrix for uniform scaling factor should solve the problem.

FYI @IsakNaslundBh @al-fisher @epignatelli

**Comment by IsakNaslundBh** [comment]
Had a quick look into this before, and I think this should solve it:

https://en.wikipedia.org/wiki/Rigid_transformation#Formal_definition

Basically, we just need to check if the determinant of the Transformation = 1. If so, it will be safe to transform the CoordinateSystem in the case of Arcs and Normal and Position in the case of Circles.
