### ISSUE TITLE
Geometry_Engine: Protection if ICentroid returns null

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#1242]
#### Description:
If `ICentroid` is unable to return a point (if the `line` is `SelfIntersecting` or `NotClosed` for example) it returns `null`. On line `39` in `PointInRegion`, a `null` point is then used to check if the curve is containing that `null` point. This causes a crash when later in the process something tries to use the point and it returns `object not set to instance of an object`.

This issue was found following investigation into https://github.com/BHoM/XML_Toolkit/issues/355 by @Majalindroth 

#### How to replicate:
Run [Test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue355_PushError?csf=1&e=UuLrGh)

#### Expected behaviour:
I would expect `PointInRegion` to carry on past line `39` and try to find a `PointInRegion` if `ICentroid` has returned null

#### Test file(s):
[Test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue355_PushError?csf=1&e=UuLrGh)

Currently assigning to @pawelbaran for input, am happy to do a fix myself if @pawelbaran is happy as code owner to the above bug report :smile:

**Comment by pawelbaran** [comment]
Happy to hand it over to you, @FraserGreenroyd :>
