### ISSUE TITLE
Structure_Engine: FreeFormProfile not working in "wrong" orientation

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1243]
#### Description:
When inputting a profile curve into `FreeFormProfile` it outputs `null` if the curve is in the wrong orientation

This is also a "problem" in `Geometry.Create.IntegrationSlices` but i'm unsure if there is need for that one to handle curves away from the right orientation.

But would suggest either moving the curves to the right orientation in the code before `Geometry.Create.IntegrationSlices` runs or at least give a error message to the user.

#### How to replicate:
Draw a section in the "wrong" plane and send it into `FreeFormProfile`

I'm also 80% sure this used to work

**Comment by IsakNaslundBh** [comment]
The integration method has always assumed the curves to be in the world XY plane, and they still need to be there for it to function as it is supposed to.

Agree that a check can/should be made for the freeform profiles and a warning/error message sent back stating this whenever someone does anything that breaks this rule, but not sure some automated fixing is the way to go.
