### ISSUE TITLE
Structure_Engine: Index out of bound error in rare cases

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#1245]
#### Description:

The code below has a small risk of hitting a negative index for a single slice or a first slice larger than half of the total area

![image](https://user-images.githubusercontent.com/16853390/66468483-cca8b000-eab8-11e9-868c-207f7a57a20f.png)

#### How to replicate:

One possible case: 

![image](https://user-images.githubusercontent.com/16853390/66468462-c31f4800-eab8-11e9-9e58-5e048301a5ee.png)

**Comment by IsakNaslundBh** [comment]
Of lot less prioerity as section integration has been switched over to greens theorem

**Comment by adecler** [comment]
Closing as it hasn't been an issues for the last 3 years
