### ISSUE TITLE
Geometry_Engine: Remove Degrees() method for NurbsSurface

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1297]
#### Description:
`BH.Engine.Geometry.Query.Degrees(this NurbsSurface surf)` method does not return correct results when the first knot value does not have full multiplicity ([Rhino wiki](https://wiki.mcneel.com/rhino/nurbs)). Therefore, a new approach is proposed in [this BHoM PR](https://github.com/BHoM/BHoM/pull/603) and #1298.

#### Test file:
Uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1297%2DRemoveDegreesMethodForNurbsSurface).

**Comment by epignatelli** [comment]
When does this happen? Why doesn't the nurbs knot vector have full multiplicity some times?

**Comment by pawelbaran** [comment]
I believe every surface closed by a periodic curve will be subject to that issue - an example has been added to the description of this issue.

**Comment by epignatelli** [comment]
Yeah, I am almost sure it is what @enarhi caught as well.

But then I think that making sure that the degree returns a correct value also for periodic curve is the thing to fix. I'd avoid storing it in the object just because there is a bug in the `Degrees` method. 
What do you think?

**Comment by pawelbaran** [comment]
From what I have found out, it is _impossible_ to fix the bug because at the moment what we have is:
- total number of control points
- number of u knots
- number of v knots

In order to retrieve the degree in each direction we still need  the number of control points in u and v - we end up with two unknowns in one equation: _n = u x v_

I am not an expert in the field though, so please be critical towards the above 🐒
