### ISSUE TITLE
Common_Engine: IElementCurves uses BHoMObject

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1323]
#### Description:
![image](https://user-images.githubusercontent.com/53530468/68760146-2137d180-0609-11ea-8aa4-9f6e940e3e1c.png)
`IElement` is not a `BHoMObject`. This still "works" as it's mostly used for Tex `Bar` & `Panel` which also is a `BHoMObject`.

The only thing this does is sending it to a decrepit method which then casts it to `IElement` to then call the new one. Hence simply changing `BHoMObject` to `IElement` would fix this.

https://github.com/BHoM/BHoM_Engine/blob/977443201f405a70635299ab61c40f8a51827ebe/Common_Engine/Query/ElementCurves.cs#L86

**Comment by FraserGreenroyd** [comment]
I would agree that it would make logical sense when reading the code for the `for` loop to be
`foreach(IElement element in elements)`
than what is currently there. I see no reason why the `for` cannot be updated per the suggestion @kThorsager is making?

@IsakNaslundBh and @pawelbaran if you're in agreement I propose @kThorsager make the change for PR and review? :smile:

**Comment by pawelbaran** [comment]
Yeah, this is legacy from the times when there was no `IElement` interface - should have been changed when the latter was being implemented. I believe the issue should be resolved while migrating all `IElement`-related stuff to Geometry_Engine.

**Comment by kThorsager** [comment]
Ok, then I'll add this in the TODO of #1316 whenever the Geometry_Engine `.csproj` is free

**Comment by pawelbaran** [comment]
@kThorsager is this still in progress or already resolved?

**Comment by kThorsager** [comment]
In progress in #1498 
Was a bit distracted from all the planning around Geometry vs Common vs Spatial Engine
