### ISSUE TITLE
Serialiser_Engine: Failing to deserialise generic types

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1340]
#### Description:

After some fairly recent changes to the `GenericDiscriminatorConvention`, some generic type obejcts are failing to deserialise correctly from Bson/Json. One example all all structural load classes.

The change the seem to have caused the issue was the addition of the conditional statements here:

https://github.com/BHoM/BHoM_Engine/blob/546cd2fe5211b3420732dd73d34ae5a108edab83/Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs#L69-L72

removing the if-statement and changing it to only say:

```
actualType = BsonSerializer.LookupActualType(nominalType, discriminator);
```

makes the deserialisation work again for the load objects I have tried with, but I assume that the conditional statement was put there for a reason. 

@adecler As this seem tied with the refactoring to get the backwards compatibility working, I do not want to touch this as I do not know all the details, but would be nice if this could be fixed as soon as possible to make it possible to deserialise the load-obejcts again.

Interestingly, BHoMGroups of the same type (that fail when inside a load) are being deserialised correctly if by themselfs. See testfile.

#### How to replicate:

Deserialise a BHoMLoad object. They are all currently being returned as CustomObject, complaining about not being able to Deserialise the Group.

#### Expected behaviour:

For the objects to be deserialised correctly.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue1340-FailingToDeserialiseLoads.gh?csf=1&e=qhxese

**Comment by adecler** [comment]
_**IF**_ I remember correctly that if-statement was there for historical reasons (see https://github.com/BHoM/BHoM_Engine/blob/5e4995bc564536977d4a0ccea53ceb3fcfa9b69d/Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs#L59).

I'll do some tests with it removed and if all works fine, I'll do the PR for it.

**Comment by adecler** [comment]
@IsakNaslundBh , I don't know how you managed to make it work by just removing the if-statement but, for me the problem appeared to be way deeper than that. 

Basically, the `nominalType.ToString() != discriminator.ToString()` was the culprit since we are using assembly qualified names for discriminating generic objects. In the case of the BHoMGroup, the discriminator would give:

```
BH.oM.Base.BHoMGroup`1[[BH.oM.Structure.Elements.Node, Structure_oM, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], BHoM, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
```

and the `nominalType.ToString()` would give 

```
BH.oM.Base.BHoMGroup`1[BH.oM.Structure.Elements.Node]
```

So same on the type level but different on the string level.

I'll PR a fix soon.

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh , I don't know how you managed to make it work by just removing the if-statement but, for me the problem appeared to be way deeper than that.

Did fix the very limited set of objects I tried with, but assumed it would screw other things up.

> Basically, the nominalType.ToString() != discriminator.ToString() was the culprit since we are using assembly qualified names for discriminating generic objects. In the case of the BHoMGroup, the discriminator would give:

Ok! Good find! 👍
