### ISSUE TITLE
SVG_Engine: Should be called Graphics_Engine

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1342]
#### Description:
The name might have made some sense before, but the namespace was already `Graphics` and I'm in the process of adding Gradient objects ([issue](https://github.com/BHoM/BHoM/issues/626), which will need corresponding engine methods which in turn would make the `SVG_Engine` have other things than `SVG` things

**Comment by al-fisher** [comment]
Yes - agreed! Thanks @kThorsager
