### ISSUE TITLE
Deprecated class still showing up

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM_Engine#1372]
We deprecated a class within an adapter (trying to deprecate the adapter as a whole at this time), however, the component does not get the 'old' sticker applied to it (in GH at least, though suspect may be across all UIs hence raising here). It is also still selectable from the right-click menu of new adapters. Not sure this is valid.

**Comment by IsakNaslundBh** [comment]
Re-opening as reverted by https://github.com/BHoM/BHoM_Engine/pull/1377
