### ISSUE TITLE
More informative Errors returned by RecordError for nested methods

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#1375]
### Description:

RecordError could return a more informative error message for errors arising in nested methods.

### Why? 
The Error message should be descriptive of only the specific issue (as we are doing now). 
However, the current behaviour of RecordError misses a feature of a thrown Exception: the Call Stack. This makes a lot of sense: we don't want to bloat the UI with a Call Stack for user experience.

However, this doesn't mean that we can not have a simple, user-friendly Call Stack.
Clarifying the context where an Error is recorded makes a lot of sense, also from an user perspective.

 > "object not set to an instance of an object" during a Push --> but where *actually* is the issue?

### Proposed how

This could be achieved adding the caller name to the Error message for methods in a nested call stack, avoiding to report the caller name when it does not make sense, which is:
 1. for Errors arisen in non-nested callers (e.g. callers that are top-level UI components)
 2. for Errors arisen in non-BHoM methods.

A way of achieving this could be:
```cs
public static bool RecordError(string message)
{
    string additionalInfo = "";
    var frame1 = new StackTrace().GetFrame(1).GetMethod();
    var frame2 = new StackTrace().GetFrame(2).GetMethod();

    if (frame1.Name != "RecordError" && frame1.Name != frame2.Name)
    {
        additionalInfo = $"\nHappened in: {frame1.Name}";
        if (frame2.DeclaringType.FullName.Contains("BH."))
            additionalInfo += $" while executing {frame2.Name}.";
    }

    return RecordEvent(new Event { Message = message + additionalInfo, Type = EventType.Error });
}
```

Test example in the Adapter:
![image](https://user-images.githubusercontent.com/6352844/70226415-b6317480-1748-11ea-8c28-fe7400e749d3.png)

See how the same code will not append the caller name for callers that is not thrown by a BHoM method:
![image](https://user-images.githubusercontent.com/6352844/70226507-dfea9b80-1748-11ea-97fb-d9a1ceb23ca4.png)

**Comment by adecler** [comment]
See  https://github.com/BHoM/BHoM_UI/issues/179#issuecomment-571866353
