### ISSUE TITLE
Serialiser_Engine: IImutable objects with abstract base class fail to serialise

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1384]
#### Description:

All `MeshElementResults` currently fail to serialise. This seem to stem from them being immutable 
and having an abstract base class which also is immutable.

After some investigation it seems as the the class map is failing when trying to run the AutoMap on row 181 in the RegisterClassMap method. https://github.com/BHoM/BHoM_Engine/blob/ec3a2a04a589b1925d975a92b8d875682f36f151/Serialiser_Engine/Convert/Bson.cs#L180-L182

From checking the stack trace and by trying to debug placing breakpoints in our methods it looks as if the standard [ImmutableTypeClassMapConvention](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/Serialization/Conventions/ImmutableTypeClassMapConvention.cs) is being used rather than our own.

This then fails as it tries to register memberinfo from the abstract base class to the superclass here:

https://github.com/mongodb/mongo-csharp-driver/blob/4fc6a30bd8b62ed1acbec01bd6b8df435f01a99d/src/MongoDB.Bson/Serialization/BsonClassMap.cs#L1252-L1262

I tried adding a dummy member to the MeshElementResult with a setter and that made the class registration hit [our method](https://github.com/BHoM/BHoM_Engine/blob/master/Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs), but then all got registred without any of the members from the baseclass which made it fail to serialise the object. (plus we ofc do not want to enforce having at least one public setable property on all immutable obejcts)

I also tried making the mesh class mutable (removing interface and adding setters to all properties) which made it work fine.

have also tried various things like setting the abstract base class to a root class but no luck.

Found this after googling:

https://jira.mongodb.org/browse/CSHARP-1559

Seems like that guy has the same issue as we do and have solved it by forking and tweaking the mongo drivers. Something I guess we would like to avoid if at all possible.

Would be nice if this can be done before the beta, as we have put a bit of focus on making working with results smoother in this quarter, but if not possible, so be it.

Will check if @epignatelli knows anything more, if not would be grateful if you could have a look at this @adecler .

#### How to replicate:

try ToJson on any mesh result

#### Expected behaviour:

For the object to serialise correctly

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue1384-FailingToDeserialiseSomeImmutableObjects?csf=1&e=O7JV7F

Note test files requires robot. Can not just store out a mesh result for obvious reasons.

**Comment by adecler** [comment]
I am still trying to get to the bottom of that one so you'll have to bare with me.
One thing that comes to mind though: I though we agreed that all objects would have a flat inheritance chain. Any comparison method would therefore be moved to the engine. That actually indirectly removes our problem here, right? I appreciate those are `IResults`, not BHoM objects but am wondering how much computational gain we are talking about but adding the complexity of the abstract class and comparison method in the BHoM. I will continue to look into this serialisation issue though.

**Comment by IsakNaslundBh** [comment]
> One thing that comes to mind though: I though we agreed that all objects would have a flat inheritance chain. Any comparison method would therefore be moved to the engine. That actually indirectly removes our problem here, right? I appreciate those are IResults, not BHoM objects but am wondering how much computational gain we are talking about but adding the complexity of the abstract class and comparison method in the BHoM.

As discussed over Skype (logging here as well in case we come back to it):

Reason for abstract class is implementation of the `IComparable` interface. This is there for two reasons, were efficiency is the second. The main reason to use it is to make use of the built in functionality you get from implementing this interface, where `list.Sort()` being the one most frequently used right now.
This ofc can be moved to the engine with our own set of sort methods, but I kind of like keeping it here if we can.
