### ISSUE TITLE
Physical_Engine: Add `Normal` method for IFramingElement

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1401]
#### Description:

IFramingElement need a method to get the normal. 

- For a Linear element the same principle as for a bar should be used
- For a planar curved centrecurve the Normal should be taken as the plane that the curve can be fitted through. 
- For nonplanar curved it gets a bit more tricky. Can leave this case as not implemented for now until a convention has been decided. @rwemay

**Comment by kThorsager** [comment]
Started looking at this and am wondering if it would be nice to have a method `Normal(ICurve curve, double orientationAngle)` from which both `Bar` and `IFramingElement` would call.

I'm saying this as this is turning into a copy paste as it is and I'm also unsure of where to place the resulting method as it wouldn't really be Physical, Structure or Geometry.

**Comment by IsakNaslundBh** [comment]
good points @kThorsager .

Think we sort of have two options:

1. Put the `Normal` definition for `IFramingElement` in Structure_Engine. Least disruptive way of getting this implemented, but might not really be the correct place.
1. Add the proposed `Normal(ICurve curve, double orientationAngle)` method to the Geometry_Engine. This will also require moving the `IsVertical(this Line line)` method here, which is currently something that is only used by the structures discipline. Saying this, having a general way for defining this across disciplines is not a bad thing. 

I think going for the second option would be the right way forward, just need to be tested that it does not affect to much code in other places.
