### ISSUE TITLE
Diffing_Engine : Default exception provided to Compute SHA256Hash

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#1418]
Suggestion of including "BHoM_Guid" as a default for the exceptions list in the Compute method

`public static string SHA256Hash(IBHoMObject obj, List<string> exceptions = null)`

@alelom - just wondering from discussions before, if there is a reason not to have the Guid excluded by default (you can always over ride) - the way BHoM currently operates, the above will be most common usage. I think at least!
Longer conversation required to bottom out usage both of Guids and Hashes(!) but on the above are you happy?

@epignatelli @michaelhoehn @kayleighhoude FYI

**Comment by alelom** [comment]
This is because `SHA256Hash` is thought just as a generic method to obtain an [SHA-256](https://en.wikipedia.org/wiki/SHA-2) from any object passed to it, in order to keep the Engine method as generic as possible.

In case you want to obtain a Hash for a BHoMObject meaningful for certain hashing scenarios (e.g. Diffing) I believe we should have other methods that expose default exclusions like the GUID.
This is what happens in 
https://github.com/BHoM/BHoM_Engine/blob/a2defb2cbe3ba0271a4fbf6eb2bd911766bd935e/Diffing_Engine/Compute/DiffingHash.cs#L48

where `DiffConfig` has a property `PropertiesToIgnore` which by defaults includes the BHoM Guid.

**Comment by alelom** [comment]
The question could then become whether we want to move the SHA256Hash method "one level up" as it abstracts from the Diffing context - perhaps in the Data Engine?

**Comment by epignatelli** [comment]
> The question could then become whether we want to move the SHA256Hash method "one level up" as it abstracts from the Diffing context - perhaps in the Data Engine?

I would second that!

**Comment by al-fisher** [comment]
@alelom - I have moved to next milestone. Not urgent - but potentially useful to comb through all delta code and workflows as priority next milestone and as part of further role out of AEC Deltas! 
Perhaps a dedicated general technical review between us two (and any others we might want to include)
👍 🚀

**Comment by alelom** [comment]
> @alelom - I have moved to next milestone. Not urgent - but potentially useful to comb through all delta code and workflows as priority next milestone and as part of further role out of AEC Deltas!
> Perhaps a dedicated general technical review between us two (and any others we might want to include)
My current work on the Speckle_Toolkit depends on a PR that is currently open on the Diffing Engine, which changes some things around. The Engine PR is mainly aiming to bring the Diffing_Engine more aligned to our decision done two weeks ago (Revision/diff based payload...). Collaterally, I also touched this hashing, and this issue might be not standing anymore. However, I generally still think the distinction is the aim of the Hash: getting a `diffing hash` requires specifying a `DiffConfig`, while a SHA-256 hash is generic and context-independent. Happy to move it "one level up" as that seems something that others would like.

**Comment by al-fisher** [comment]
Thanks @alelom - yep -sounds good. Let's re-look once your open activities are completed! Cheers

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Engine/pull/1952
