### ISSUE TITLE
Serialiser_Engine: Add methods to check if a string is a valid json

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#1427]
#### Description:

Currently the `FromJson` takes a `string in and tryes to output a valid object. If the string is not a valid json, it returns an error..

When calling this methods from the outside, such as in the `HTTPAdapter.Pull(GetRequest request PullType pulType, ActionConfig, actionsConfig)`, there is no standard way of checking if the string is a valid json, and the component turns red, if an e.g. an xml is pulled.

**Comment by travispotterBH** [comment]
@desaiwangBH  work for week of 6/26 - 6/30  Work with Fraser on this. I guarantee there is an already build piece of code somewhere on the internet that would get us 95% of the way. Don't reinvent the wheel.

**Comment by FraserGreenroyd** [comment]
See [this comment](https://github.com/BHoM/BHoM_Engine/pull/3097#issuecomment-1619100218) which summarises the work completed by @desaiwangBH and the collective agreement to not merge the code, but we are considering this issue completed in the interim since 2020.
