### ISSUE TITLE
Reflection_Engine: Do not add default description if one is found

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1461]
#### Description:

When descriptions have been added to the proeprty/class, the last part "This is a property of xxx" becomes redundant and is almost more in the way than helping:

![image](https://user-images.githubusercontent.com/22005920/73932384-80407600-48da-11ea-8f30-46f20d84c980.png)

Propose removing if descriptions have been found.

**Comment by al-fisher** [comment]
Agreed. 
I actually would be tempted to go further and say we remove "This is a property of xxx" entirely for all cases

**Comment by al-fisher** [comment]
@IsakNaslundBh as also discussed can we also only include "This is a xxx" if `IObject` ? 🙏 😄
