### ISSUE TITLE
Reflection_Engine: Expose property attributes in create methods

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1462]
#### Description:

We have some create methods that have some logic in them, but where the rest is simple property assignments. An example is the Bar create that accepts a Line. here the only difference between a straight property assignment is that the line is used to grab out the start and end node positions, the rest goes straight through.

For these types of methods is would be good to be able to pick up descriptions from the base class, and not have to add new input attributes to describe them.

**Comment by adecler** [comment]
```c#
[Description("inputName", "[NickIt"])]
```

More seriously. It might be good to still explicitly have to indicate that you want to  grab the description from the object property. For simpler CI checks if nothing else.

**Comment by FraserGreenroyd** [comment]
> More seriously. It might be good to still explicitly have to indicate that you want to grab the description from the object property. For simpler CI checks if nothing else.

I would support/second this

**Comment by adecler** [comment]
> I would support/second this

Great! Then, let's maybe think of a slightly better way to do this than a "NickIt" string 😋 
What about a new attribute `[InputFromProperty("inputName")]` ?

**Comment by al-fisher** [comment]
Oh - I quite liked “NickIt” 😝 !! 

> What about a new attribute `[InputFromProperty("inputName")]` ?

Yes. Sounds good.

**Comment by FraserGreenroyd** [comment]
> What about a new attribute `[InputFromProperty("inputName")]` ?

Would it be worthwhile including the matching property name from the input name in this attribute? This would help with things like a property called FEMesh and in input called feMesh without relying on only one letter changing? If that makes sense?

**Comment by IsakNaslundBh** [comment]
> > What about a new attribute `[InputFromProperty("inputName")]` ?
> 
> Would it be worthwhile including the matching property name from the input name in this attribute? This would help with things like a property called FEMesh and in input called feMesh without relying on only one letter changing? If that makes sense?

Yeah, had been thinking that as well. Could add something like:

```
namespace BH.oM.Reflection.Attributes
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor, AllowMultiple = true)]
    public class InputFromProperty : Attribute, IImmutable
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        public string InputName { get; private set; } = "";

        public string PropertyName { get; private set; } = "";


        /***************************************************/
        /**** Constructors                              ****/
        /***************************************************/

        public InputFromProperty(string inputName, string propertyName = null)
        {
            if (propertyName == null)
            {
                if (inputName.Length == 0)
                    propertyName = inputName;
                if (inputName.Length == 1)
                    propertyName = char.ToUpper(inputName[0]).ToString();
                else
                    propertyName = char.ToUpper(inputName[0]) + inputName.Substring(1);
            }

            InputName = inputName;
            PropertyName = propertyName;
        }

        /***************************************************/

    }
}
```

that automatically would use the input name as property name (with pascal instead of camel case), or let you override it for cases where property names starts with acronyms etc (FEAType for example).

**Comment by FraserGreenroyd** [comment]
That SGTM @IsakNaslundBh , I'd be happy with an implementation along those lines

**Comment by adecler** [comment]
I like Isak's solution too.
