### ISSUE TITLE
Physical_Engine: Add Method for Calculating Volume of Columns

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_Engine#1464]
#### Description:
Add method for calculating volume of columns using the length and the Constant Framing Property Profile curves

![image](https://user-images.githubusercontent.com/34316256/73958797-73ba1e80-48d6-11ea-8fe9-ae6a950156a4.png)

**Comment by Tom-Kingstone** [comment]
On review of historic issues: The PR for this issue was closed, and a separate PR that handles this feature was created and linked to that PR, which added volume calculations for `IFramingElement`, which covers `Column` objects.
