### ISSUE TITLE
Reflection_Engine: SetProperty not calling properties correctly

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1475]
#### Description:

Using set property for a property that does exist, is reporting it doesn't/using customdata. Have not tested in other UI's so unsure if it's GH or UI. 

![image](https://user-images.githubusercontent.com/15233608/74192340-427e7d00-4c4d-11ea-9550-85c1e5e5f511.png)

#### Steps to reproduce:

Call get/set property on any nested property of same name and try to set. 

#### Expected behaviour:

SetProperty should set the property

**Comment by adecler** [comment]
This is an issue with the reflection engine, not the UI.

It appears that `BH.Engine.Reflection.Modify.PropertyValue()` has not been updated to follow the same property chain support as `BH.Engine.Reflection.Query.PropertyValue()`

**Comment by rwemay** [comment]
First pass here: https://github.com/BHoM/BHoM_Engine/tree/Reflection_Engine-%23Issue1475-Setproperty-using-concatenated-names

[Test Script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FReflection%5FEngine%2FReflectionEngine%2DIssue982%2DGetSetNestedProperties&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
