### ISSUE TITLE
BHoM_Engine: RemoveFragment should return the same BHoMObject if the given fragment is not found

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#1479]
#### Description:

The following behaviour does not seem reasonable to me:
![image](https://user-images.githubusercontent.com/6352844/74328879-9f318300-4d86-11ea-8e3c-b568918b0344.png)

Instead of `null` it should return the same BHoMObject.

**Comment by alelom** [comment]
@FraserGreenroyd can't remember if it was me or you writing this method. If you agree to this modification I can do it myself - I'd find it useful as part of something I'm currently doing.

**Comment by FraserGreenroyd** [comment]
Go for it, I'm happy to see that change
