### ISSUE TITLE
Common_Engine - Compliance issues

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#1509]
This report has been generated as part of a close out for the 3.1 milestone compliance and outlines all of the compliance issues currently highlighted by the CI team. I will be undertaking this issue to resolve all compliance issues which do not impact scripts or versioning, with the remainder being moved to the 3.2 milestone for further discussion and resolution.

The following compliance issues have been found for this project. Please see the checklist below.
##### Create file  must match the create method(s) return type. Either part of the path or the filename must be an exact match of the return type of the method. If the file name does not match the return type file name must match the method name.
 - [x] in BHoM_Engine\Common_Engine\Create\NewElement0D.cs at line 34, column 33 
 - [x] in BHoM_Engine\Common_Engine\Create\NewElement1D.cs at line 34, column 33 
 - [x] in BHoM_Engine\Common_Engine\Create\NewInternalElement2D.cs at line 34, column 33 

##### Input parameter should start with a lowercase letter
 - [ ] in BHoM_Engine\Common_Engine\Create\Material.cs at line 35, column 100 

##### Method name must match file name
 - [x] in BHoM_Engine\Common_Engine\Modify\TranslateIElements.cs at line 35, column 33 
 - [x] in BHoM_Engine\Common_Engine\Modify\TranslateIElements.cs at line 55, column 33 
 - [x] in BHoM_Engine\Common_Engine\Modify\TranslateIElements.cs at line 62, column 33 
 - [x] in BHoM_Engine\Common_Engine\Query\OutlineCurve.cs at line 50, column 38

**Comment by FraserGreenroyd** [comment]
@kThorsager how would this impact your current plans with moving most of these objects?

**Comment by kThorsager** [comment]
Good to get done in the migration PR right away, and hardly game breaking changes so easy fix.

Is not `Material.cs` exempt by virtue of being very deprecated? (and proposed change would be script breaking)

**Comment by FraserGreenroyd** [comment]
> Is not `Material.cs` exempt by virtue of being very deprecated? (and proposed change would be script breaking)

Deprecation is only exemption in a few cases, but the proposed change would not be script breaking I don't think? Have you got a script showing that it would break?

**Comment by kThorsager** [comment]
hmm, miss remembered that input name changing was breaking

> Good to get done in the migration PR right away

If it is done in a separate PR it will definitely conflict with the migration PR, I was planning to handle this in #1498 @FraserGreenroyd
