### ISSUE TITLE
Diffing_Engine - Compliance issues

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#1511]
This report has been generated as part of a close out for the 3.1 milestone compliance and outlines all of the compliance issues currently highlighted by the CI team. @alelom will be undertaking this issue to resolve all compliance issues which do not impact scripts or versioning, with the remainder being moved to the 3.2 milestone for further discussion and resolution.

The following compliance issues have been found for this project. Please see the checklist below.
##### Incorrect Engine class name based on file path
 - [x] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 17 
 - [x] in BHoM_Engine\Diffing_Engine\Convert\ToDiffingJson.cs at line 42, column 32 

##### Input attribute does not match any of the given parameters
 - [x] in BHoM_Engine\Diffing_Engine\Create\Stream.cs at line 44, column 15 

##### Method name must match file name
 - [x] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 57, column 20 
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 67, column 19 
 - [ ] in BHoM_Engine\Diffing_Engine\Modify\UpdateRevision.cs at line 43, column 43 
 - [ ] in BHoM_Engine\Diffing_Engine\Query\GetHash.cs at line 36, column 35 

##### Modify methods must return the same type as their first parameter
 - [x] in BHoM_Engine\Diffing_Engine\Modify\SetHashFragment.cs at line 47, column 22 

##### Invalid Engine class: Engine classes must be static
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 4 

##### Invalid Engine class name
 - [ ] in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 39, column 17

**Comment by alelom** [comment]
I like Ending punctuation! Damn me

**Comment by FraserGreenroyd** [comment]
> I like Ending punctuation! Damn me

I know, blame @IsakNaslundBh  - he's been giving everyone headaches this morning :wink:

**Comment by alelom** [comment]
Ok, they are now all done, except the ones on the HashComparer:
NameMatchesFileName:
> in BHoM_Engine\Diffing_Engine\Comparers\HashComparer.cs at line 67, column 19
 in BHoM_Engine\Diffing_Engine\Modify\UpdateRevision.cs at line 43, column 43
 in BHoM_Engine\Diffing_Engine\Query\GetHash.cs at line 36, column 35

these three are referring to the constructor, `Equals` and `GetHashCode` methods.
However, my comparer was in an incorrect namespace and folder. I now have corrected the file location of my file to: `/Objects/EqualityComparers/DiffingHashComparer.cs`. As I see that this is aligned to what we did for other comparers, I hope this will also prevent these compliance errors from popping up.

Same goes for IsStaticClass and IsValidEngineClassName checks on the HashComparer file.

**Comment by FraserGreenroyd** [comment]
That sounds good @alelom - moving those objects to the `Objects` folder will resolve the problems as they are slightly outside the usual Engine method philosophy, as per other engines :smile:
