### ISSUE TITLE
Geometry_Engine: ClipPolyline is not compliant and overlapping

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1536]
#### Broken rules:

The method setup is itself not fully compliant, as it contains the extra Edge class. Also, reading the method description of what the method should be doing, it is overlapping with the BooleanIntersection method for Polylines. 

#### Suggestions to restore compliance:

I think the method itself can be removed in full, and all usages switched to the BooleanIntersection method.

**Comment by rolyhudson** [comment]
Thanks for flagging this @IsakNaslundBh I will check to see if it can be replaced with BooleanIntersection

**Comment by FraserGreenroyd** [comment]
MergedVertices.cs is also the same, is that one of yours @rolyhudson ?

**Comment by rolyhudson** [comment]
@FraserGreenroyd sorry MergedVertices is not one of mine.

**Comment by FraserGreenroyd** [comment]
@rolyhudson No worries :smile: I'll add it to the list of things to sort
