### ISSUE TITLE
Reflection_Engine: deprecate RecordNote method

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1553]
#### Description:

Following BHoM/Grasshopper_Toolkit#480, it would be good to deprecate `BH.Engine.Reflection.Compute.RecordNote` method.

**Comment by adecler** [comment]
@pawelbaran , based on discussions from others closed issues, are you happy to close this one too ?

**Comment by pawelbaran** [comment]
Yeah, doing it now 👍
