### ISSUE TITLE
Set Property Issue

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_Engine#1556]
#### Description:
Set property not working for any properties not directly on the object

#### Steps to reproduce:

![image](https://user-images.githubusercontent.com/34316256/76239951-ca35b800-6208-11ea-9f67-04381e47114f.png)

#### Expected behaviour:
Set Property would work for nested properties

**Comment by awakeman** [comment]
Not sure I'm necessarily best placed to look into this at present.
