### ISSUE TITLE
Diffing_Engine: Method with incorrect namespace

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#1564]
#### Broken rules:
`Compute.HashComparing()` method should be in `BH.Engine.Diffing` not `BH.Engine`.

Same goes for `HashFragmComparer`. 
This one should also be in an `Objects` folder unless I am mistaken (@FraserGreenroyd ?)

**Comment by FraserGreenroyd** [comment]
No that's correct @adecler - I think @alelom is moving `HashFragmComparer` as part of work on #1511 as well, but hopefully he can resolve this namespace one in the same batch of work :smile:
