### ISSUE TITLE
Environment_Engine: Add roofHeight input parameter to MapToLevel method

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/BHoM_Engine#1594]
#### Description:
Add roofHeight as input parameter to the MapToLevel method. This will ensure that the levels being passed through will prepare the extrudeToVolume method to receive correct levels. 

MapToLevels currently takes in all levels and spits out only the levels with associated geometry. This means that the roof height (or any other prioritised levels) are discarded within the method. This leaves the user to select the roof level height and calculate all extrusion heights. 

![image](https://user-images.githubusercontent.com/54593392/77175393-f7038e00-6a98-11ea-9c78-4713e31e9ebc.png)

**Comment by BingWangUS** [comment]
I don't think roofHeight should be a input to MapToLevel function, since it will not be used for MapToLevel. It is a input that needed for ExtrudeToVolume method.

However, under current method, ExtrudeToVolume is taking one height given each room or list of room. It is user's responsibility to create a list of heights based on LevelInUsed and roofHeight.

But I do see the benefit to have a similar method, named ExtrudeAllToVolume, that takes a list of list for room, and LevelInUsed, and a roofHeight, to do all jobs in one.

**Comment by michaelhoehn** [comment]
@BingWangUS Agreed. I was a little conflicted to place this task within this method for the reasons you noted. I thought since this method is taking all levels and outputting the "useful" levels, it may be a bit of a misdirect as the natural tendency is to plug those levels directly into the next method of extrusion. 

Agreed that this is possibly another method entirely, but wanted to pose the issue here to see if it may be handled well within this existing method.

**Comment by BingWangUS** [comment]
Workflow 1:
MapToLevel -> level 1, snap to grid -> user give height 1, ExtrudeToVolume
                    -> level 2, snap to grid -> user give height 2, ExtrudeToVolume
                    -> level 3, snap to grid -> user give height 3, ExtrudeToVolume
etc

Workflow 2:
MapToLevel -> snap all to grid -> plug all level, user give roof height, ExtrudeAllToVolumes

Hope this explains it better.

**Comment by FraserGreenroyd** [comment]
@michaelhoehn @BingWangUS sorry, I'm confused now from reading the comments what exactly the 'fix' or 'feature' that is needed here.

Is this surpassed by the desire in #1615 ?

**Comment by BingWangUS** [comment]
Hi Fraser. I think Michael was proposing a additional input for MapToLevel function as roof height. Then return a list of level in use + roofHeight (level). Thus we can directly supply rooms and levels to Extrude method.

However, I don't agree with it. It is more confusing when output a tree with 5 branch of rooms but a level with 6 branch (level in use + roof). I suggest keeping MapToLevel as it is but create floorHeight method (#1615) to create a 5 branch of heights, which aligns with the Extrude method input.

We agreed the second approach. @michaelhoehn can you confirm?

**Comment by BingWangUS** [comment]
This now should be closed.
