### ISSUE TITLE
Matter_Engine: MatchMaterial

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1617]
#### Description:

This method would allow for getting a specific kind of `IMaterialProperty` from a object with a material. This would allow for a much smoother trans-disciplinary work.
Especially thinking of early stage LCA.

It would either find it on the `Material` or deduce it which kind of material it is.
Deducing it would involve:

1. Evaluating the names and types (descriptions) of the `IMaterialProperty`s and the Material
2. Looking among a data-set of default `IMaterialProperty`s for the correct type 
3. Then pick one matching the evaluated names and descriptions

##### MatchMaterial
Input:

- `Material`, the material to match from
- `IMaterialProperty`, The kind of IMaterialProperty to get from the material
- `DataSet` data set of materials to match to.
- `bool` allowDefaults, whether to allow for matching of the material to a default IMaterialProperty which is not on the `Material`

Output: 

- `IMaterialProperty` 
of the correct type gotten from the materials `IMaterialProperty`s or 
best match based on that material (defaults)

FYI @al-fisher

**Comment by kThorsager** [comment]
@enarhi discuss with @IsakNaslundBh & @al-fisher about feasibility, control and transparency

**Comment by kThorsager** [comment]
@enarhi I'll put something in the diary to have further discussion with @al-fisher @IsakNaslundBh

**Comment by kThorsager** [comment]
Following the discussion:
- Feature to preform automatic matching of materials from one discipline to another is put on hold
- #1697 Add a feature which increases the ease of working with materials while keeping the control

**Comment by Tom-Kingstone** [comment]
Completed in #2932
