### ISSUE TITLE
Common_Engine: Remove deprecated methods

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1624]
#### Broken rules:
It has a bunch of Deprecated methods which we're moved to the Spatial_Engine.

#### Suggestions to restore compliance:

- [x] 1. Raise issues about updating the dependencies in other toolkits.
- [x] 2. Close those issues.
- [x] 3. Assure that Versioning works.
- [ ] 4. Remove the methods.

@FraserGreenroyd how are we looking on running a compliance report to find were these Deprecated methods are used?

Most of these toolkit only need to remove their references to Common_Engine, and removing the methods won't break them. But they will break when we eventually remove the Common_Engine all together, so saw no reason not to raise the issues now.

Toolkits with action required before proceeding:

- [x] Revit
- [x]  ETABS

**Comment by FraserGreenroyd** [comment]
@kThorsager we're not close - you will need to do it manually if you're planning to do this anytime soon, sorry.
