### ISSUE TITLE
Geometry_Engine: weird hardcoded values in CollapseToScaledPolyline

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1631]
#### Description:

Hardcoded values got sneaked in to `BH.Engine.Geometry.Convert.CollapseToScaledPolyline` while working on https://github.com/BHoM/BHoM_Engine/pull/1255:

https://github.com/BHoM/BHoM_Engine/blob/a6b00d12e00910d618ce1b8c233cd41e7c079fe9/Geometry_Engine/Compute/CollapseToScaledPolyline.cs#L44

Could we please change the values (particularly `tolerance` to restore compliance?

**Comment by FraserGreenroyd** [comment]
Removing `bug` label as this is solely a `compliance` issue.

This would be good to resolve out though ASAP :smile:

**Comment by kThorsager** [comment]
It's a hard-coded default value which can be overwritten with ease, and was picked because it gave good values, just like every other tolerance.

Should it be remove altogether or a arbitrary 10^n be picked?

**Comment by FraserGreenroyd** [comment]
Ideally all tolerance inputs should use something from the Geometry_oM Tolerance class. If that class doesn't contain a definition (angle, distance, etc.) which is valid for this type of tolerance then that might be an additional discussion needed.
