### ISSUE TITLE
Structure_Engine: Off-centre section issues

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1657]
#### Description:

https://github.com/BHoM/BHoM_Engine/blob/9ea9155f8dcd6ed0fdb020e1ae99e2f2f39790eb/Structure_Engine/Compute/IntegrateSection.cs#L97
This creates a singular `BoundingBox` at Origo, which will then be a part of the total `BoundingBox` for the section. This means that the placement of the section curves in the XY-plane affects the section properties. This shouldn't happen as the section after this has it's position adjusted, with no corresponding change in values.

IMG: four identical section edges with different section property values
![image](https://user-images.githubusercontent.com/53530468/79240471-bf0a2380-7e69-11ea-9d57-612ac7ec7b1e.png)

FYI @IsakNaslundBh 

Would suggest adding a metod in Geometry_Engine which gets the total bounding box from a collection of `BoundingBoxes` to reduce the amount of people who make this mistake
#### Steps to reproduce:

Create a freefrom section away from the origo on the XY plane

#### Expected behaviour:

the edges on the section should have the same property values as the section

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EpXcV7sd78dOksKEPpfFg3oB4AgrgAKGQ18kYHcORuzmsA?e=5hG7pm

**Comment by IsakNaslundBh** [comment]
Could also be fixed by changing

```
            BoundingBox box = new BoundingBox();
            for (int i = 0; i < curvesZ.Count; i++)
                box += curvesZ[i].IBounds();
```

to

```
            BoundingBox box = curves[0].Bounds();
            for (int i = 1; i < curvesZ.Count; i++)
                box += curvesZ[i].IBounds();
```

(setting the bounds to the first curve and then looping from index 1 instead of 0)
