### ISSUE TITLE
Geometry_Engine: Add Bounds(List<BoundingBox> boxes)

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1658]
#### Description:
A method which gets the combined `BoundingBox` for a collection of boxes

would reduce incidents like these: #1657

**Comment by FraserGreenroyd** [comment]
@BingWangUS has already done this somewhere I think, @BingWangUS is this what you did? Maybe this is something that would help you @BingWangUS ?

**Comment by BingWangUS** [comment]
Yes it is done in CFD_Toolit. Not merged yet. But the idea is tested it out and then moved to engine.
