### ISSUE TITLE
Graphics_Engine: ToRenderMesh methods for BHoM.Geometry primitives

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#1694]
#### Description:

Capturing discussion with @alelom, suggesting need for creation of converts from potentially all geometry primitives to a mesh representation to support creating 3D visualisations of BHoM objects across other host applications that support meshes.

We currently have Query.Geometry() - there are plans to add more control in being able to return multiple different **_representations_** for any object (geometrical or otherwise).
Immediate priority is however to enable the above - that is create _mesh_ from our _geometry primitives_.

So planning phased development.

####  ToRenderMesh
Building on the pre-existing Graphics_Engine/oM.

Add `ToRenderMesh() extension methods for each of the critical geometry primitives.

Surfaces
- `BH.oM.Geometry.Extrusion`
- `BH.oM.Geometry.Pipe` (Linear only for now)
- `BH.oM.Geometry.PlanarSurface`

Solids
- `BH.oM.Geometry.Sphere`
- `BH.oM.Geometry.Cuboid`
- `BH.oM.Geometry.Cone`

Curve and Vector
- `BH.oM.Geometry.Point` - Make a Sphere
- `BH.oM.Geometry.Line` - Make a Pipe

Mesh representations of the above objects (with the exception of `PlanarSurface` and assuming `Extrusion.Capped == false`) are all easily calculated analytically I would suggest.

`PlanarSurface` - could be solved in the general case using a delaunay triangulation - which we have for other applications in the BHoM. 

#### Representation Namespace
Potential then to introduce a new foundational namespace - titled "Representation".
This Representation Engine/oM that disciplines can all reference will be needed to enable objects' own devolved control over querying representations of objects. Analogous to the current Geometry.

`BH.Engine.Structure.Query.Geometry(this Panel)`

#### Migrate some functionality from Graphics

- Also consideration to be made around naming of `RenderMesh`
Could a) be rename `BH.oM.Graphics.Mesh` - namespace specific
as well as consider b) generalising further into a `Representation.Mesh` as could be used for more things. To be considered later.

- Also building out of `ToText` for an object (for all permutations of documentation, graphics 3D & 2D and/or speech)

So in first instance looking at Phase one and creating the `ToRenderMesh` for most useful and easily implemented geometry objects in first instance.

@kThorsager @IsakNaslundBh @rwemay @alelom  FYI

**Comment by alelom** [comment]
Closing as superseded by advances in https://github.com/BHoM/TriangleNet_Toolkit/pull/27. 

Related conversation is where we will move the GeometricalRepresentation() methods that are currently in TriangleNet_Toolkit: https://github.com/BHoM/TriangleNet_Toolkit/issues/32
