### ISSUE TITLE
Structure_Engine: Description crashes for null vectors

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1701]
#### Description:

Vectors being null when getting description should state "null" instead of crashing.

**Comment by peterjamesnugent** [comment]
@IsakNaslundBh using the `Description` and `DescriptionOrName` methods with a `null` `Vector` only returns an error with a `null` result - I cannot get it to crash. Do you have a script?

**Comment by IsakNaslundBh** [comment]
Try getting the description from an empty timber material for example. That is crashing on my machine.

**Comment by peterjamesnugent** [comment]
That's odd, I cannot get it to crash in Rhino 5 or Rhino 6.

Does this test script crash for you: https://burohappold.sharepoint.com/:f:/s/BHoM/EqksKZqBSrZDu9lQuAgxGYEBGon959FhudAQ9EKEpWmMdg?e=Lc0u8y

**Comment by IsakNaslundBh** [comment]
> That's odd, I cannot get it to crash in Rhino 5 or Rhino 6.
> 
> Does this test script crash for you: https://burohappold.sharepoint.com/:f:/s/BHoM/EqksKZqBSrZDu9lQuAgxGYEBGon959FhudAQ9EKEpWmMdg?e=Lc0u8y

Yes it does 
![image](https://user-images.githubusercontent.com/22005920/89264031-8b2e5600-d632-11ea-81b6-2b3db5ce36d9.png)

```
1. This component failed to run properly.
- Error: Object reference not set to an instance of an object.
- Occured in  BH.Engine.Structure.Query.VectorComponents(Vector vector)
     called from BH.Engine.Structure.Query.MaterialAnalyticalValues(IOrthotropic orthoTropicMaterial)
- Are you sure you have the correct type of inputs? Check their description for more details.
```

Maybe we have been speaking over each other with this? I do not mean a full rhino/GH crash, just mean the component is becoming red and throwing an exception. Is it not for you?

**Comment by peterjamesnugent** [comment]
Ah okay, I thought you meant crashing Rhino - it is clear now.
