### ISSUE TITLE
Structure_Engine: SolidVolume for Bar does not consider TaperedProfiles

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1707]
https://github.com/BHoM/BHoM_Engine/blob/f0be1da5815d42e425b0b8195c91cccab15ae6ae/Structure_Engine/Query/SolidVolume.cs#L52

Area on sections with taperedProfiles have 0 area, hence all sections with tapered profiles will be considered to have zero volume

**Comment by michaelhoehn** [comment]
Happy to have a look at this one in the coming 7.1 milestone.

**Comment by peterjamesnugent** [comment]
Believe this was closed a while ago:
https://github.com/BHoM/BHoM_Engine/pull/1735
