### ISSUE TITLE
Geometry_Engine: Join should always return a collection of ICurves

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1722]
#### Description:

Atm `Join` method taking a collection of `Line` returns a collection of `Polyline` and `ICurve` => `PolyCurve` respectively. This can lead in wrapping single segments in `PolyLine` or `PolyCurve`, which had already proved to be problematic now and then.

Maybe it would be better to return a collection of `ICurve` in all cases, where single segments are returned as they are on input?

**Comment by Tom-Kingstone** [comment]
On review, I feel like this change isn't necessary. The IJoin method that takes `List<ICurve>` as input converts all input `ICurve`s into `PolyCurve`s, and then attempts to join those together. This leads to the output being a `List<PolyCurve>` no matter whether we display it as a `List<ICurve>` or not. On the other issue of whether the other Join methods should return `List<ICurve>`, I think the same case can be made for those as well.

> Maybe it would be better to return a collection of `ICurve` in all cases, where single segments are returned as they are on input?

In this case, using the `Convert.ToPolyLine(PolyCurve)` method would work just fine for segments where all subparts are `Line`s
