### ISSUE TITLE
Diffing_Engine: Review of customdataIdName

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#1730]
As discussed @alelom - potential to move the input `customdataIdName` to the DiffConfig.

Good to get wider input on what is most intuitive following more workflows and testcases.

Also, as discussed, ultimately `customdataIdName` will refer to/be replaced by an AdapterID Fragment.
Thus we should include this consolidation in any plan

![image](https://user-images.githubusercontent.com/15924573/80827287-9f019080-8bdb-11ea-97da-539157f3eddc.png)

**Comment by alelom** [comment]
I started typing in a quite long answer to this, but then I must have forgotten to press comment, and I lost it. I have some ideas on this, perhaps it needs a call to be more efficient in terms of time.

**Comment by al-fisher** [comment]
Call sounds good 😄

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Engine/pull/2665 and the many following refactorings done to the diffing.
