### ISSUE TITLE
BHoM_Engine: Add shallow (and deep?) cloning for any object

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#175]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
As mentioned in #768:

Idea to direcly make use of https://github.com/force-net/DeepCloner
