### ISSUE TITLE
Base_Engine: The set geometry method in BHoM_Engine does not do anything

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1754]
#### Description:

The method does a dynamic cast call to an method that returns the obejcts. Should either be fixed or removed as it currently is confusing rather than adding value

#### Steps to reproduce:

Try using the SetGeometry method in the base BHoM_Engine.

#### Expected behaviour:

For it to either work or not exist.

**Comment by FraserGreenroyd** [comment]
I'm voting to go with removing if no one has any objects.
