### ISSUE TITLE
Serialiser_Engine: Investigate exact requirements for (de)serialisation of immutable obejcts

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1760]
#### Description:

As uncovered here https://github.com/BHoM/BHoM_Engine/pull/1756 some objects seem to have slightly different requirements to be able to de-serialise on different machines.

A full investigation on what does requirements are and why this behaviour differs needed.

**Comment by adecler** [comment]
- This method is the key one to understand how Bson handle constructors: https://github.com/mongodb/mongo-csharp-driver/blob/faf90213601ab87749bc8611032465cbbe89b21b/src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs#L471
- When a class has one or more constructors, the best will be picked to initialise the object (see [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/Serialization/MostArgumentsCreatorSelector.cs)). The `values` dictionary provided as argument is the list of property values already extracted from json/bson. The selected constructor is basically the one with the most matching names between parameters and properties. If even a single parameter doesn't have a matching property name, that constructor will be ignored.
- The creation of the object is very simple: pick the values for the arguments by taking the corresponding property values.. Then it is as simple as calling ` _delegate.DynamicInvoke(arguments.ToArray());` where `_deletegate` is the constructor. There is no per-casting or anything like that. So if the Type casting fails, it fails on the invocation level. See source code [here](https://github.com/mongodb/mongo-csharp-driver/blob/faf90213601ab87749bc8611032465cbbe89b21b/src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs#L471)

This is the local state for `TaperedProfile`:

![image](https://user-images.githubusercontent.com/16853390/81768846-9891e380-950e-11ea-9412-ad5d67e710d9.png)

A `ReadOnlyDictionary` inherits from `IDictionary` so there should be no problem there.

**Comment by adecler** [comment]
OK, even if I had reverted my code to the master and cleaned my folder, for some reason I still had the new version of Bson in the BHoM folder. After manually replacing it with the one from the NuGet package, I actually ended up with the same error as Isak.

So it seems that the most logical thing to do is simply to upgrade Bson to fix this bug.

**Comment by adecler** [comment]
Looking at the places where `MongoDB.Bson.dll` is referenced, we have:
- Serialiser_Engine
- Diffing_Engine
- Mongo_Toolkit
- Versioning_Toolkit
- BHoM_UI
- XML_Toolkit
- Topologic_Toolkit
- File_Adapter
- Socket_Toolkit

I am a bit surprised we don't have this better contained so will probably need to be investigated further to see if we can have those repos rely more on Serialiser_Engine before we upgrade Bson version.

@al-fisher , @FraserGreenroyd , FYI

**Comment by adecler** [comment]
closing here as raised as an admin issue for upgrading the NuGet package and reduce the number of direct dependencies to Mongo.Bson.
