### ISSUE TITLE
Geometry_Engine: Add vector from two points method

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1771]

**Comment by kThorsager** [comment]
Or wait, the `-operator` for points returns a `Vector`.
```
Point a;
Point b;
Vector fromAtoB = b - a;
```

Is that enough or would you still prefer a Create method for some reason?

**Comment by rwemay** [comment]
That's what I've been using, but thought would be good and intuitive to add an explicit create method for those that might not be aware the operators are enabled.
