### ISSUE TITLE
Geometry_Engine: Add IIsNurbsCurve to check if any part of a curve is a nurbs

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1772]
#### Description:

![image](https://user-images.githubusercontent.com/15233608/82184327-5c300000-98df-11ea-82b4-9768e78b5363.png)

**Comment by kThorsager** [comment]
`curve.ISubParts().Any(x => x is NurbsCurve);`
is in general used around the rest of the code, is that enough or perhaps it's for UI purposes?

**Comment by rwemay** [comment]
Nice - more elegant! In the UI is one area to filter out things that won't work with a lot of components/avoid the not implemented, the other is similar to the vector issue - makes it slightly more clear/easier as a developer when you see and IsNurbs rather than needing to know to check the sub parts IMO
