### ISSUE TITLE
Geometry_Engine: Not Implemented Exception Review

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1779]
#### Broken rules:
We are trying to keep away from trowing exceptions and instead add a error through reflection.

We're also using the `[NotImplemented]` attribute, which does hides the methods from the UI, but not from the code. i.e. If I'm coding another method I need to go to the methods definition to see if it works.

Currently it's thrown for some different reasons:
- Part of a method which does not work with it.
- The internals of any method with the attribute `[NotImplemented]`
- Some methods which do not seem to have solutions, `ToPolyline(Arc)`

We also have methods like `DiscontinuityPoints(PolyCurve)` which has the attribute but looks like it should work? And is presumably called from the interface all the time.

#### Suggestions to restore compliance:

- Use private fallback methods opposed to keeping a to do list in the code as not implemented methods.
- Return `null` or `NaN` and log a error in Reflection if no solution can be found.
- Don't know how to handle methods who return booleans as there, the safest solution is to throw exception as it can be difficult to determine what the safe option is. So would opt to leave those as is unless a good solution to that could be found.

FYI @pawelbaran @epignatelli @al-fisher

**Comment by kThorsager** [comment]
FYI @alelom 
As you also had various cases for throwing of exceptions

**Comment by alelom** [comment]
Thanks @kThorsager. We currently have a problem with replacing Exceptions with Errors as Errors do not fully replace their functionality. I have been forced in keeping exceptions in a few instances where I need to Catch the error/exception. This is a framework issue that needs resolving and I have got very little time to dedicate to currently. In some instances we currently face an alternative:
1) Either expose irrelevant errors to the user OR duplicating code, OR
2) Keeping some exceptions and do a catch.

I can't go in detail now but this is the situation. I will be against removing some of those exception I placed around until we are able to solve the issue at framework level, for which again I have little time to dedicate now.

**Comment by LMarkowski** [comment]
@al-fisher FYI

I scanned and blame-buttoned through the Geometry_Engine and found those methods which throw `NotImplementedException`s. Vast majority of them are simply versions of methods for unsupported input (mostly `NurbsCurve`). They are written in _italics_ and I guess I can start resolving them right away. I support doing it using fallback methods (e.g as in `RoundCoordinates`).
The rest (not in italics) I will probably change to return `null` and log an error.

Sorry for spam for those who are not interested, but I wanted to make sure no one has anything against, before I start to change their code.

@adecler 

- _ClosestPoint_
- _ControlPoint_
- _ExternalEdges_
- _Length_
- _Project_

@epignatelli 

- _Area_
- _MeshIntersections_

@IsakNaslundBh 

- ShapeProfile
- ShapeProfileCurves

@KonradStolarski 

- CurveProximity

@kThorsager 

- IntegrateRegion

@LMarkowski 

- BooleanDifference
- BooleanIntersection
- BooleanUnion 
- Centroid
- _Distance_
- Extend
- IsClockwise
- IsCoplanar 
- _IsOnCurve_
- _Normal_
- _NurbsForm (convert)_
- _Offset_
- SortAlongCurve 
- _SplitAtPoints_

@pawelbaran 

- BasisFunction - `[NotImplemented]` with 0 references
- _CollapseToPolyline_
- DerivativeFunction - `[NotImplemented]` with 0 references
- DiscontinuityPoints - one basic and one implemented but marked as `[NotImplemented]`
- _EndDir_
- EndPoint  
- _IsContaining_
- _IsEqual_
- _IsInPlane_
- _IsLinear_
- _IsPlanar_
- _IsPolylinear_
- _IsSelfIntersecting_
- _LineIntersections_
- _NurbsCurve (create)_
- _NurbsSurface (create)_
- _ParameterAtPoint_
- _PlaneIntersections_
- _PointAtLength_
- _PointAtParameter_
- _Polyline (convert)_
- _ProjectAlong_
- _StartDir_
- StartPoint
- _TangentAtLength_
- _TangentAtParameter_
- _TangentAtPoint_

**Comment by adecler** [comment]
@LMarkowski , no problem on my side for you to change the code under my name

**Comment by al-fisher** [comment]
Thanks @LMarkowski - looks good

**Comment by epignatelli** [comment]
No problem at all @LMarkowski !

**Comment by pawelbaran** [comment]
Good on my end too, with a few suggestions how I would resolve the non-italics (please be critical, I did not go into detail):
- `BasisFunction`, `DerivativeFunction` - delete, not implemented with zero references, no point in keeping
- `EndPoint`, `StartPoint`, `DiscontinuityPoints` - record error and return `null`
