### ISSUE TITLE
Serialiser_Engine: Immutable objects with overridden properties in their constructor fail to (de)serialise

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1827]
#### Description:

An immutable object that has overridden a property from the base object, for example the Name, and also has this property in its constructor have problem (de)serialising. THis is mentioned here https://github.com/BHoM/BHoM_Engine/pull/1811 where a fix for being able to (de)serialise immutable objects with overridden properties at all was added.

A more general solution, allowing overriden properties to be used in the constructor should be investigated and implemented.

Putting this as a target for the 3.3 milestone.

**Comment by adecler** [comment]
Solved by PR: https://github.com/BHoM/BHoM_Engine/pull/1385
