### ISSUE TITLE
Base_Engine: Centralisation and Standardisation of errors, warnings and notes

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1840]
#### Description:

Sorry if this has already been raised elsewhere(!!) Having just made up another warning text, I've been thinking for a while it could be useful to standardise some common warnings into a format - e.g. IsNurbsCurve or IsPlanar, concatenating (or not depending what the format(s) we decide) things like the guid.

**Comment by adecler** [comment]
Adding on this issue to broaden the spectrum to a general redesign of the error recording solution.

From the discussion we had in the [Monthly Framework Planning Session](https://github.com/BuroHappoldEngineering/BuroHappold_admin/issues/163) :

> We need to improve the logging system to allow for example to 
    - silence it
    - throw exceptions instead of logging errors when `RecordError` is called
    - be very careful on how the interaction of global settings work on the stack
    - also idea of bookmark to delete or recover records since the time of the bookmark
    - @alelom to raise issue and draft PR to cover his own user case that triggered the discussion

> @alelom , see the change of [this PR](https://github.com/BHoM/BHoM_Engine/pull/1762/files) that was a temporary and bad solution for the problem you raised here about silencing the logging system temporarily. So something that is probably worth mentioning in the issue you raise as both an example of the problem we need to solve and something to fix in the long run once we have a better solution in place. 

I would also add that we also mentioned migrating the error log out of Reflection and into the Base namespace.

**Comment by adecler** [comment]
See #https://github.com/BHoM/BHoM_Engine/issues/1645 for reference to teh migration of some of the reflection engine to the base engine
