### ISSUE TITLE
Library_Engine: Add support for versioning for the Library paths

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1864]
#### Description:

Need to add a system that allows for renaming of files and/or movement of folders that the Dataset files resides in. 

This is firstly to allow for moving a file from a particular folder into a subfolder.

First idea is to make use of the already existing `m_libraryPaths` and inject the old location/filename into this, to make sure you still reach the same library as before.

System should be set up with separate textfile(s) that can be modified to state what has happened, that is then being loaded up by the library engine, and injected into the paths.

**Comment by al-fisher** [comment]
Hey @IsakNaslundBh - this would be a good one to plan picking up. As will be very helpful for a number of conversations around further development and organisation of datasets (particularly in the material space).

Have referenced in new issue here: https://github.com/BHoM/BHoM_Datasets/issues/121 - which will be good to action to help the organisation of more of the new datasets being developed by many others including @michaelhoehn @kayleighhoude

**Comment by IsakNaslundBh** [comment]
@al-fisher agreed. Will try to map out what needs to be done to be able to close this out!

**Comment by al-fisher** [comment]
Thanks @IsakNaslundBh
