### ISSUE TITLE
Diffing_Engine: add PropertiesToInclude diffing workflow

### ISSUE THREAD

**Issue by Stepsan** [BHoM/BHoM_Engine#1866]
#### Description:

Please could you include a function similar to the PropertiesToIgnore option, with which specific properties can be selected for comparison? An example of workflow:
- I have two lists of objects, of e.g. `CustomObjects`. The objects come from an external source, over which I have no control (e.g. a Revit model modified by an architect). However I know that each and every one of those objects will always have some known property assigned to them. For example, I know that all CustomObjects will have some property called `propertyA` and another called `propertyB`.
- I want to do the diffing between the lists of objects, based only on those known properties. For this, I would like to have an input called like `propertiesToInclude` where I can specify the name of the properties: `propertyA` and `propertyB`.
- The output can be in the form of a `VennDiagram` where the objects are dispatched to either "onlyInFirstList", "onlyInSecondList", or "both". 

This can be useful for objects which include a lot of sub-properties that are either not known or liable to change.

**Comment by alelom** [comment]
Thanks @Stepsan ! 😄 🚀

**Comment by alelom** [comment]
@Stepsan I've edited the issue to elaborate a bit on what we said, hope you don't mind 😄 
This shows the level of detail we need in Github issues to understand and work on them.
I'll start working on this ASAP 🚀
