### ISSUE TITLE
Global: Design the Representation system

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#1877]
#### Description:

Following the Representation workshop ([meeting minutes here](https://burohappold.sharepoint.com/:w:/s/BHoM/EZ2a3eMTEYJKkZ4FxFFm27QBBNWS-v1Xn-Kh5Aklc11EEQ?e=Oz4fjb)), we want to do a first formalisation of the proposed changes.
This means I will draw diagrams for the proposal with the support of Arnaud.

**Comment by alelom** [comment]
After some other thinking with @rolyhudson regarding the use of Representation in Graphs, we formalised the concept a bit better:
![RepresentationDesign3](https://user-images.githubusercontent.com/6352844/100874500-925c5800-349c-11eb-9ed0-0415184b06fd.png)

**Comment by rolyhudson** [comment]
Noting use cases to be used for further discussion and development :
- Structural geometry
- Text representation
- Venue 
- CIH

**Comment by alelom** [comment]
Following today's conversation, the main comment on the diagram above is that we should drop the `storeInFragment` logic as it adds unneeded complexity. Further, the representation by itself should not be coupled with the object, as it can be computed and consumed on-the-fly by the application that needs it when needed.

**Comment by alelom** [comment]
Closed as described in https://github.com/BHoM/BHoM_Engine/pull/2288#issuecomment-786750390
