### ISSUE TITLE
Cull Theatron without deprecating first?

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM_Engine#1886]
`Audience_oM` and `Engine` has replaced the functionality of the `Theatron` tools (within `Architecture_oM` and `Engine`). 

Previously I had suggested removing `Theatron` elements and methods after marking it Deprecated. I think this is an unnecessary step as it is very unlikely any one is using it. 

I'd like to check here if any one objects to this?

There is one dependency in `Humans_Engine` on the `Theatron.ActivityArea`. 
As part of the removal of Theatron this dependency can be resolved (and simplified) using a `Polyline` and `Point` in place of the  `Theatron.ActivityArea`.

**Comment by FraserGreenroyd** [comment]
> Previously I had suggested removing `Theatron` elements and methods after marking it Deprecated. I think this is an unnecessary step as it is very unlikely any one is using it.

Unlikely, yes, but not impossible - and we have no way of knowing what is being used in the wild as this is an open source project. We should follow our deprecation process as much as possible I think (just my 2-pence!).

**Comment by rolyhudson** [comment]
Thanks @FraserGreenroyd. Understood and happy to proceed with deprecating.
