### ISSUE TITLE
Geometry_Engine: Centroid does not always return a point in a polygon

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#1896]
#### Description:
Some polylines which represent a closed polygon are not getting the correct centroids returned. This causes issues in workflows relying on the centroid of a polyline. Because the `PointInRegion` method also uses a centroid to begin with, this does not provide a workaround. `Centre` does provide a workaround, but does not work for the reasons `Centroid` exists in the first place.

#### Steps to reproduce:
I have isolated 4 polylines that have this issue in the linked test file. Run the test file and see that the centroid is no where near the original polyline.

#### Expected behaviour:
That the centroid is actually somewhere vaguely near the polyline it's for (ideally, somewhere in the centre of it...)

#### Test file(s):
[Download here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Centroid%20Bug/TestFile.gh?csf=1&web=1&e=Y3m7vP)

FYI: @rboulton-BH

**Comment by IsakNaslundBh** [comment]
Had a first quick look, and I think the issue stems from the fact that the curves are actually not perfectly planar, and this is not caught by the IsPlanar method, causing the Normals to be incorrect. trying to get the normal out from those curves gives positive or negative global Z, which is obviously wrong for vertical curves. Fitting a plane through the curves and then projecting the curves to this plane, then doing all the operations gives correct results.

Hence, something tolerance related is causing the issues here.
