### ISSUE TITLE
MEP_Engine: Adjust Error Handling on Section Profile and Box Profile

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_Engine#1953]
#### Description:
-Set defaults for inner and outer radius to be 0 for both
-Thickness should only be a required property for the thickness on the box/tube profiles (aka the duct thickness itself)
-Lining thickness and insulation thickness should be ok as 0 (as they often are, especially lining)

FYI: @IsakNaslundBh @AndreBalasian @FraserGreenroyd

**Comment by IsakNaslundBh** [comment]
>-Set defaults for inner and outer radius to be 0 for both

Agree, this can be added to the Create method for the box profile in Geometry_Engine. Have nothing against doing this from structures side.

> -Thickness should only be a required property for the thickness on the box/tube profiles (aka the duct thickness itself)
-Lining thickness and insulation thickness should be ok as 0 (as they often are, especially lining)

This will need to be handled on the side of MEP_oM and MEP_Engine.

My suggestion would be to update the Create methods for `SectionProfile` and check if the lining and/or insulation thickness is 0. If so, do not create the offset profile, but just set it to `null`. In my mind this makes more sense, as it is not a profile with 0 thickness, it is actually just nothing there.

This will then need to be handled in any method working with the SectionProfile, such as the Create method for the `DuctSectionProperty`, `PipeSectionProperty` and `WireSectionProperty` by checking if the value is null, and if so, set the corresponding areas to 0 etc.


Also, sort of unrelated but found whilst checking through this, think I found a small bug that I assume is a leftover from when the negative profiles where used. THe lining area on line 58 below:

https://github.com/BHoM/BHoM_Engine/blob/2ce2c5f29c29782b64d44940e688987555a2f338/MEP_Engine/Create/Elements/DuctSectionProperty.cs#L57-L59

I think should just be the area of the lining profile, as there is no longer any overlap between any of the profiles.
