### ISSUE TITLE
BHoM_Engine: Name is saved in CustomData instead of replacing Name property. Same for other properties

### ISSUE THREAD

**Issue by JonathanNillius** [BHoM/BHoM_Engine#1981]
Can't find object properties to input on my custom objects.

not a custom object:
![image](https://user-images.githubusercontent.com/54712802/73356722-e271f900-4292-11ea-90aa-6b4e874dcaaf.png)

CreateCustom object:
![image](https://user-images.githubusercontent.com/54712802/73356813-10573d80-4293-11ea-9bcb-32971411cebb.png)

**Comment by adecler** [comment]
Transferred as it is a bug in the `BH.Engine.Base.CustomObject` method
