### ISSUE TITLE
Reflection_Engine: Add record event methods that accept Exceptions

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2011]
#### Description:

Suggestion to adding additional RecordEvent methods, RecordError, RecordWarning and RecordNote methods that accepts an exception as an input.

This way we could centralise extraction of the exception message, together with some additional error text provided together with the exception.

Can the also use the call stack from the exception rather than extracting the call stack ourselves, which might help with debugging.

@adecler @al-fisher @alelom @FraserGreenroyd

**Comment by alelom** [comment]
Thanks for logging this @IsakNaslundBh .
