### ISSUE TITLE
Base_Engine: FilterByType could return the excluded objects too

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2015]
#### Description:

Currently `FilterByType` method returns only the objects of a given type. It would be nice to be able to extract the inverse output easily, preferably using multi output (collection of passing objects as one and collection of not passing as the second). I would be happy to implement it - @adecler would you have any concerns with changing the return type of the existing method?

**Comment by adecler** [comment]
Given that it is never used directly in the code, I am fine with this. 

This will however make the code more awkward on the C# side to use multi-outputs. I wonder if it is not time to consider supporting `out` method parameters. 

@IsakNaslundBh , @al-fisher , @FraserGreenroyd , FYI.

**Comment by pawelbaran** [comment]
I do not think this feature is needed now, therefore closing the issue.
