### ISSUE TITLE
Environment_Engine: Removal of unnecessary Create methods simply exposing only the Public Defining properties

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#2036]
#### Broken rules:
As per parent issue https://github.com/BHoM/BHoM_Engine/issues/1155 - to be tackled after close out of https://github.com/BHoM/Versioning_Toolkit/issues/96

FYI @FraserGreenroyd @tg359 - please assign as makes sense 😄

**Comment by FraserGreenroyd** [comment]
I'll give this to @JohannaOlin1 and @linaeriksson to handle, as our unnecessary create methods were deprecated some time ago so are ready to be removed :smile:

**Comment by FraserGreenroyd** [comment]
@JohannaOlin1 to handle this sprint :smile:
