### ISSUE TITLE
MEP_Engine: Removal of unnecessary Create methods simply exposing only the Public Defining properties

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#2037]
#### Broken rules:
As per parent issue https://github.com/BHoM/BHoM_Engine/issues/1155 - to be tackled after close out of https://github.com/BHoM/Versioning_Toolkit/issues/96

FYI @FraserGreenroyd @kayleighhoude  - please assign as makes sense 😄

**Comment by FraserGreenroyd** [comment]
@michaelhoehn will enjoy this one :smile:
