### ISSUE TITLE
Analytical_Engine: Add core graph query methods 

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM_Engine#2042]
Add core graph query methods. 

Proposal is to  focus effort on the specific demands / requirements from the `GraphFlow_Toolkit` and need for shortest path in `BuroHappold_Revit_Toolkit`.

All methods below exist in prototype form in `GraphFlow_Toolkit` and will require minor refactoring to migrate and work with the graph object proposed in https://github.com/BHoM/BHoM/issues/1014.

- Adjacency
- A* shortest path
- Dijkstra shortest path
- Depth Dictionary
- IsolatedNodes
- Sinks
- NotSinks
- SubGraphs

@pawelbaran , @tiagogrossi

**Comment by tiagogrossi** [comment]
This sounds great @rolyhudson, please put me as tester :)
