### ISSUE TITLE
Geometry_Engine: Unexpected behaviour in BooleanUnion

### ISSUE THREAD

**Issue by tiagogrossi** [BHoM/BHoM_Engine#2048]
#### Description:
It may be that I'm trying to use `BooleanUnion`for different purposes than originally thought, but when I try to merge a collection of closed `polylines` together I'm getting some unexpected results. See picture below:

Original geometry before using `BooleanUnion`
![image](https://user-images.githubusercontent.com/20777038/95763023-6bf11c00-0ca6-11eb-957c-50bb7ecc6284.png)

![image](https://user-images.githubusercontent.com/20777038/95763124-8cb97180-0ca6-11eb-8cc6-fde26373d71d.png)
After using `BooleanUnion`

#### Steps to reproduce:
Simply open test file below and compare original input geometry and computed geometry from `BooleanUnion`

#### Expected behaviour:
Highlighted segments in yellow in the images above should not exist once `BooleanUnion` is computed.

#### Test file(s):
Test file here [Geometry_Engine#2048.zip](https://github.com/BHoM/BHoM_Engine/files/5365991/Geometry_Engine.2048.zip)

**Comment by tiagogrossi** [comment]
Hey @LMarkowski thought I'd pop this one up in your radar, are you able to have a look please? It works 95% fine, but in some special cases it seems to fail a bit. Let me know your thoughts!

**Comment by LMarkowski** [comment]
Hi @tiagogrossi, thanks for raising that.
It seems to be an issue with the precision of the input curves. If you zoom in that part enough you can see that it is actually a legitimate polygon:
![image](https://user-images.githubusercontent.com/48125514/95786673-598fd600-0cd8-11eb-8092-804901dcdd48.png)
![image](https://user-images.githubusercontent.com/48125514/95786694-6280a780-0cd8-11eb-888a-fd9cd89cfa79.png)
What is interesting it seems that all of the overlapping points are offset by exactly the same value: 0.000595.
I am actually now working on a cleanup method that would cull out leftovers like these, but it is not ready yet.
I think that the boolean method itself did what it should, however as it is a second very similar issue it might be too precise 🙈

**Comment by tdgrossi** [comment]
Oh wow! I had not realized that, thanks for spotting it @LMarkowski! Good to know you're working on something similar, I reckon we leave this issue open until then?

**Comment by tiagogrossi** [comment]
Oh wow! I had not realized that, thanks for spotting it @LMarkowski! Good to know you're working on something similar, I reckon we leave this issue open until then?

**Comment by FraserGreenroyd** [comment]
Closing as @LMarkowski most likely resolved the issue in 2020 during the work being undertaken.
