### ISSUE TITLE
Spatial_Engine: Migrate all ShapeProfile and Grids and level methods from Geometry to Spatial

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2052]
#### Suggestions to restore compliance:

Related to:
https://github.com/BHoM/BHoM/issues/756

Need to migrate all methods targeting object migrated in parent issue.

Should also take this time to make the method compliant by splitting up create methods in separate files.

**Comment by FraserGreenroyd** [comment]
This appears to have been closed out completely in other work, supported by #2063

Closing this issue as complete as part of historic issue clean up.
