### ISSUE TITLE
BHoM_Engine: Rename CustomData to UserData in the base engine

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2071]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\BHoM_Engine\Query\Geometry.cs

 - [ ] BHoM_Engine\BHoM_Engine\Query\ShallowClone.cs

</p>
</details>

**Comment by adecler** [comment]
@FraserGreenroyd , `Geometry` and `ShallowClone` are processing `CustomData` as part of the object but don't use it to store anything.

I have renamed this issue to reflect what needs to happen alongside the name change from `CustomData` to `UserData`.

**Comment by adecler** [comment]
Closing as we agreed to keep the name CustomData
