### ISSUE TITLE
Reflection_Engine: Rename CustomData to UserData to reflect the change in the oM

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2076]
@adecler again not sure if this is as relevant for Reflection Engine so will leave to you to close if not relevant.

The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\Reflection_Engine\Modify\SetPropertyValue.cs

 - [ ] BHoM_Engine\Reflection_Engine\Query\PropertyDictionary.cs

 - [ ] BHoM_Engine\Reflection_Engine\Query\PropertyNames.cs

 - [ ] BHoM_Engine\Reflection_Engine\Query\PropertyValue.cs

</p>
</details>

**Comment by adecler** [comment]
@FraserGreenroyd , the methods listed above are utility methods that assist on the processing of the object including the case when the data is stored as user data but doesn't leverage `CustomData` for any local use.
I have renamed the issue to reflect that.

**Comment by adecler** [comment]
Closing as we agreed to keep the name CustomData
