### ISSUE TITLE
Serialiser_Engine: Rename CustomData to UserData to align with the change in the oM

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2077]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\Serialiser_Engine\Convert\Bson.cs

 - [ ] BHoM_Engine\Serialiser_Engine\Objects\BsonSerializers\CustomObjectSerializer.cs

</p>
</details>

**Comment by adecler** [comment]
@FraserGreenroyd , the references to `CustomData` in the methods above are meant to assist with the serialisation of `CustomObject` and are not use to store code data. I have renamed to issue to reflect that.

**Comment by adecler** [comment]
Closing as we agreed to keep the name CustomData
