### ISSUE TITLE
Structure_Engine: Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2078]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\Structure_Engine\Query\DeformedShape.cs

 - [ ] BHoM_Engine\Structure_Engine\Query\HasAssignedObjectIds.cs

 - [ ] BHoM_Engine\Structure_Engine\Query\PlotBarForce.cs

</p>
</details>

**Comment by IsakNaslundBh** [comment]
Can be closed as of https://github.com/BHoM/BHoM_Engine/pull/2106
