### ISSUE TITLE
Physical_Engine: Add Query methods returning the centerline of BH.oM.Physical.Elements.Beam aligned to top/bottom

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2079]
#### Description:

As in the title, `TopCenterLine` and `BottomCenterLine` would be a nice to have, particularly for the purpose of Revit interaction (at least until https://github.com/BHoM/BHoM/issues/935 and https://github.com/BHoM/BHoM/issues/936 get properly resolved).

FYI @JosefTaylor

**Comment by IsakNaslundBh** [comment]
Moving this to Physical_Engine as targeting Beam/IFramingElement, not IElements
