### ISSUE TITLE
Spatial_Engine: There should be no Area method for IElement1D and IElement0D

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2086]
#### Broken rules:

We have methods for calculating the Area for an `IElement1D` and `IElement0D`. This has been shown to cause issues such as 

https://github.com/BHoM/BHoM_Engine/issues/2081
https://github.com/BHoM/BHoM_Engine/issues/2085

Unless we have a clear need to have an area method that works for any `IElement` I suggest we simply remove the methods for `IElement1D`, `IElement0D` as well as the interface method for `IElement` as it is royally confusing to call Area method as it stands in the Spatial_Engine, which is one of the core places we want to deal with geometry.

#### Suggestions to restore compliance:

Remove the `Area` methods for `IElement1D`, `IElement0D` as well as the interface method for `IElement`

Any objections to why this should not be done? @pawelbaran @al-fisher @LMarkowski @FraserGreenroyd @michaelhoehn

**Comment by FraserGreenroyd** [comment]
No objections from me :smile:

**Comment by pawelbaran** [comment]
Not sure if it is as confusing to me (in the end, it was me who added the methods), but I do not mind keeping `Area` only for `IElement2D`.
