### ISSUE TITLE
Geometry_Engine: Review object cloning

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2100]
#### Description:
Following [this comment](https://github.com/BHoM/BHoM_Engine/pull/2070#pullrequestreview-513864022), there is a few calls to `DeepClone` in Geometry_Engine that need reviewing:
- `LineIntersections` should be happy with shallow clone
- `IsCoplanar` should not need cloning at all
- should `SortCollinear` and `SortAlongCurve` clone all input points or simply sort them? My intuition says only sort, same as you sort collections
- `ClusterCollinear` same as above?

Probably there is more, the above were caught by simply scrolling through the code.

I believe it is one of many issues originating from https://github.com/BHoM/admin/issues/9 - @al-fisher, please feel free to change/close/transfer if it suits better somewhere else.

**Comment by FraserGreenroyd** [comment]
This has been resolved by @pawelbaran this week following historic issue review via another issue which was a duplicate.
