### ISSUE TITLE
BHoM_Engine: add options to set numerical tolerance in `Query.Hash()`

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#2103]
#### Description:

Use case from @rolyhudson :
> I've been using the DifferentProperties() method on a fairly complex structure with 670 nodes - with occasional tiny errors in node position that I need to ignore - diff with tolerances would be very helpful

Should be an easy addition to the current method.
Consider:
- a new parameter `numericTolerance` that applies globally to all numbers
- also to provide another parameter `Dictionary<string,double> roundingPerProperty` that allows to set a rounding per specific property

**Comment by rolyhudson** [comment]
Sounds good and potentially very useful to handle tolerance on different properties. 

Global tolerance would be all I require right now and maybe easier?

I wonder with the `roundingPerProperty` how detailed would the input need to be? 
For example if you were interested in comparing a property called `Position` of type `Point` would it be necessary to specify rounding for `Position.X`,  `Position.Y` and  `Position.Z`? 
This is currently the case with the Diffconfig for `DifferentProperties()` method. What would be nice would be a trickle down so I could just indicate tolerance for Position and all its sub-properties or specify explicitly a full property string.

**Comment by alelom** [comment]
Hey @rolyhudson ,

you're hitting the nail on the head - that's why I also added https://github.com/BHoM/BHoM_Engine/issues/2104
