### ISSUE TITLE
Geometry_Engine: Method to calculate Volume from closed brep

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#219]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
I believe this feature is far beyond our reach at the moment, so there is no need to keep it open - therefore closing.
