### ISSUE TITLE
Structure_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2201]
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

**Comment by alelom** [comment]
Reopening as some usages of oM's GetShallowClone have crept back in.
