### ISSUE TITLE
Reflection_Engine: Bug preventing enum creation from UI 

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2258]
#### Description:
Installing an alpha from today (210107) onwards and put an enum component on a UI, then right click that component, the select an item has no options to select from.

#### Steps to reproduce:
See above, image below to demonstrate:
![image](https://user-images.githubusercontent.com/18049174/103889830-f64aef80-50de-11eb-82dc-921c5c6feb9d.png)

#### Expected behaviour:
That the enum select an item has options available in it.

I found that by commenting out `&& typeof(IObject).IsAssignableFrom(type)` on line 139 of `Reflection_Engine/Query/TypeList.cs` resolved the issue and allowed enums select an item to appear. However, that line of code was added in [this PR](https://github.com/BHoM/BHoM_Engine/pull/2251) which was merged yesterday, and was added to assist in the testing of the UI that the PR was related to. As I can't work out the reason for the addition of the line, I have opted not to raise a PR just removing it because it was added for a reason, so unfortunately will have to leave to you @adecler to propose a solution that resolves this bug, and resolves the original intention for the line addition.

**Comment by adecler** [comment]
Thanks @FraserGreenroyd ,

The reason behind the change is that more and more tests are relying on the types inside the `BHoMTypeList` being actual object definitions. Enums are obviously a complete different beast programmatically speaking so it was weird to merge them together in the first place. I mean we even have a completely different component to handle them in the UI. So there was actually quite a few places in the code that had to explicitly filter them out.

Another reason was that we had some weird `+<>c` types appearing in the menus. So explicitly filter for `IObject` fixed that.

There was however two places in the code that were leveraging the fact that the BHoM list was containing the two:
- The `BHoMEnumList` method that was nothing more than `BHoMTypeList().Where(x => x.IsEnum).ToList()`
- The serialiser Engine that was registering the enums at the same time as the `IObjects`

I'll do a PR that fixes all the above.
