### ISSUE TITLE
Geometry_Engine: Add unit tests

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM_Engine#2272]
#### Definition of the test :
Based on the [discussion](https://github.com/BHoM/BHoM/discussions/1148) add unit tests for the following:
 `Query.IsContaining`
 `Query.Bounds`
 `Query.LineIntersections`
 `Query.Normal`
 `Compute.BooleanUnion`
 `Query.Distance`
 `Query.Area`
 `Compute.BooleanIntersection`
 `Query.PointAtParameter`
 `Query.DiscontinuityPoints`
 `Compute.CurveProximity`
 `Query.ClosestPoint`
 `Query.Centroid`
List is prioritised by count of file changes in github.

**Comment by rolyhudson** [comment]
Dropping `Intersection` methods from the above list. 
Currently unit test checking does not allow for null or empty results.  Tests or intersection should include the situations where no intersection is found.

**Comment by LMarkowski** [comment]
Adding  `Query.LineIntersections` and `Compute.BooleanIntersection` back to the list. 😉
