### ISSUE TITLE
Environment_Engine: adding capacity for solar position method to calculate anytime between hours

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/BHoM_Engine#2291]
#### Description:

Changing the method to take double instead of int as input and add capacity to interpolate for doubles.

**Comment by rboulton-BH** [comment]
There does not appear to be sufficient demand at the moment for this capability that it is worth dedicating resource to it. I anticipate that if the functionality is ever required it will be as a one-off where a manual workaround (e.g. crude interpolation between calculated points) could quite easily be established. @BingWangUS if this would be useful to you then you are welcome to pick up the development yourself and we can provide some support. But for now I'm closing the issue.
