### ISSUE TITLE
MEP_Engine: Pressure Loss Calculation

### ISSUE THREAD

**Issue by sorooshsami** [BHoM/BHoM_Engine#2292]
Following discussion with @kayleighhoude and @FraserGreenroyd it would be nice to have a method for calculating pressure loss for duct work using raw numbers as an interim for the fittings objects.

To begin with, we would like to start with rectangular elbows which would take in as inputs:

 - An angle
 - A height
 - A width
 - A collection of K values which could then come from a dataset for CIBSE guide C or American standards as appropriate

I have some code in Python which is doing this for a project which I can share for translation.

@kayleighhoude what would be your thoughts to interpolating the result where the answer is between values? Would we want that or just want to round the number to the nearest from the K values table?

**Comment by kayleighhoude** [comment]
@sorooshsami interpolating between values would be the most accurate approach, but rounding up between values would likely yield a comparable result since the tables are based on inches or mm values of height and width typically

**Comment by travispotterBH** [comment]
In MEP_Prototypes will be ported over.
