### ISSUE TITLE
Geometry_Engine: Ellipse constructor to return object with consistent axes 

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#230]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Will be resolved when https://github.com/BHoM/BHoM/issues/1288 is actioned. Will close this issue as alignment required by oM refactoring will handle this automatically.
