### ISSUE TITLE
BHoM_Engine: Expose Linq methods for IObject

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#233]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
Assigning myself and adding to next release's MVP milestone in order to close out. I have done some prototyping but it needs work and thought to get it right.

**Comment by awakeman** [comment]
I think this is superceded by #1305 and the PR: #1312. Closing
