### ISSUE TITLE
Shouldn't InheritedTypes exclude nulls?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2330]
#### Description:
While working on #2327 I have noticed that the lines below may lead to null in the returned set:
https://github.com/BHoM/BHoM_Engine/blob/2761083ed5771eee3c642544cbc73e9f1e5f8b6f/Reflection_Engine/Query/InheritedTypes.cs#L42-L43

Wouldn't it be good to add a null check on `type.BaseType` before adding it to `types`?

**Comment by adecler** [comment]
Ha, yes. Nice catch. Looks like I forgot that interfaces don't have a base type
