### ISSUE TITLE
Geometry_Engine: the new RunExtensionMethod "not found" error is returned by the Goos preview every time a BHoMObject does not own one

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#2340]
#### Description:

Due to https://github.com/BHoM/BHoM_Engine/pull/2331, when an object's Goo tries to preview, if the Geometry() method is not found for it, an error is exposed:

![image](https://user-images.githubusercontent.com/6352844/108996811-c78cd680-7696-11eb-8a8d-cdc0b03ae0d3.png)

The error is correctly returned by the newly introduced `RunExtensionMethod(object obj, MethodInfo method)`, because the method for IGeometry provided to it is actually `null`. The search for an IGeometry method is invoked by the Goo. See: <details> 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6352844/109018551-21e66100-76b0-11eb-99e2-b236f539a6e9.png)
</details>

**In general**, the change introduced by https://github.com/BHoM/BHoM_Engine/pull/2331 brings a slight change in the usage of the `RunExtensionMethod()` pattern.

In the case of **_common_ extension methods**, like `IGeometry()` – i.e. _method called from a variety of different places_ – **we need to be careful when using `RunExtensionMethod()` _alone_**. You may be exposing irrelevant errors.

We need to make sure that `ExtensionMethodToCall()` is first used to retrieve the method, then a case `if (method != null)` should be introduced before using `RunExtensionMethod(object obj, MethodInfo method)`. An appropriate error can be then be returned (or not, depending on the usage) if no Method was found.

### Suggested fix

Introduce the check in the IGeometry fallback, from:

```cs
 private static IGeometry Geometry(this IBHoMObject obj)
{
    return Reflection.Compute.RunExtensionMethod(obj, "Geometry") as IGeometry;
}
```

To:

```cs
 private static IGeometry Geometry(this IBHoMObject obj)
{
      MethodInfo method = BH.Engine.Reflection.Query.ExtensionMethodToCall(obj, "Geometry");
      if (method != null)
          value = BH.Engine.Reflection.Compute.RunExtensionMethod(obj, method);
      else
          return null; // returns null and no Error appears in UI, restoring previous behaviour.
}
```
@pawelbaran @adecler @al-fisher @IsakNaslundBh @FraserGreenroyd @rolyhudson

**Comment by pawelbaran** [comment]
As discussed with @alelom, I fully agree with the diagnosis as well as proposed solution. Adding an extra check where needed should not be too laborious taken the current scope of use of `RunExtensionMethod`. My only suggestion would be to remember to refresh the documentation at the end of the milestone to reflect the changes we made.
