### ISSUE TITLE
Analysis_Engine: Query.Geometry() method allows you to generate a non planar PlanarSurface

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Engine#2363]
#### Description:

The query method for a `PlanarSurface` bypasses the checks by not using the constructor:
Relevant part of the code:
https://github.com/BHoM/BHoM_Engine/blob/97c734e1a6b908706da70c66ac7c334ffd648a26/Analytical_Engine/Query/Geometry.cs#L76-L90

This allows steps to produce a non planar PlanarSurface.

#### Steps to reproduce:

Create non planar `Panel` from geometry in test file, run `Query.Geometry()` method to get geometry that is a non planar `PlanarSurface`.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Geometry_Engine/%232356%20-IsPlanar-PlanarSurface.gh?csf=1&web=1&e=Ofa6el

**Comment by Tom-Kingstone** [comment]
@peterjamesnugent, where did you get the non-planar PlanarSurface from?

**Comment by peterjamesnugent** [comment]
Not sure - it was nearly three years. Is it not within the Test File?

**Comment by Tom-Kingstone** [comment]
I figured out how to create the non-planar panel. Is it valid to be able to create a non-planar panel?

**Comment by Tom-Kingstone** [comment]
@peterjamesnugent a little more digging, and I realise that the auto-constructors for panels allow for non-planar edges to be input. The reason `Query.Geometry()` for an `IPanel` does not use the `Create` constructor is because there should not be a panel that is non-planar. Therefore the fix for this issue is to change the constructors for `Panel`s.

**Comment by Tom-Kingstone** [comment]
In the meantime, We'll change the original method mentioned so that non-planar surfaces cannot be made.
