### ISSUE TITLE
Reflection_Engine: Issues with some nesting generics when called from the UI

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2364]
#### Description:

This error is showing itself in the UIs, but think the issue is probably in the generic handling methods in the engine, so raising here. Please feel free to move if wrong.

Some relatively complex methods in terms of generic arguments where added in https://github.com/BHoM/BHoM_Engine/pull/2355/files and those methods seem to have issues getting called from the UI.

I have not digged any deeper into it yet, but @IsakLarbornBH might be able to give some more details.

#### Steps to reproduce:

Try adding a component corresponding to one of the methods in the PR in for example grasshopper.

#### Test file(s):

See https://github.com/BHoM/BHoM_Engine/pull/2355/files

**Comment by adecler** [comment]
After fixing the parts of the code that are not compiling in that PR, I got a component showing up fine:

![image](https://user-images.githubusercontent.com/16853390/109627536-ae939200-7b7c-11eb-84df-375adaed0773.png)

So would be good if you could provide an example of the component will valid inputs

**Comment by IsakLarbornBH** [comment]
Yeah, that PR needs a few other branches to build, namely BHoM/BHoM#1208 and #2354. Because there are changes in both the Graphics_Engine and Result_Engine the way I have it set up now is that you need to create your own branch to merge these two branches into, but there might very well be a much better way to go about this.

There is now a test file on the PR that you can use with Robot. It's messy and unannotated, but it is really just a simple push-execute-pull workflow.

**Comment by adecler** [comment]
Can you provide a simple self-contained example ? Ideally just the component above with some inputs ou consider as valid. I did have a quick look but the meshes definitions I could find were not implementing the expected input interface S not sure which want you are testing on.

 The Grasshopper script you provide doesn't generate any Mesh and I don't have Robot files I can use.

**Comment by IsakLarbornBH** [comment]
The Grasshopper script generates Panels, which Robot will then mesh when executing the analysis, which will also generate the results. But if you give me some time I could internalise some data for you to test with.

**Comment by IsakLarbornBH** [comment]
> Can you confirm ?

I don't think that would work - the method needs actual mesh results, not just a MeshResultRequest as input. I'll create a file with some internalised data :)

**Comment by IsakLarbornBH** [comment]
@adecler This file should work I hope!
[MeshResult Internalised.zip](https://github.com/BHoM/BHoM_Engine/files/6067795/MeshResult.Internalised.zip)

**Comment by adecler** [comment]
@IsakNaslundBh , the bug actually occurs in Grasshopper but would be the same in other UIs. The problem is fairly clear although the solution is not:

![image](https://user-images.githubusercontent.com/16853390/109632367-ecdf8000-7b81-11eb-9402-0c6f573799e2.png)
