### ISSUE TITLE
Reflection_Engine: Null method message introduced in RunExtensionMethod is recorded where not needed

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2377]
#### Description:

As discussed a few times already with @IsakNaslundBh @alelom @FraserGreenroyd, #2331 has armed `RunExtensionMethod` with an error that is recorded when no suitable extension method exists:

https://github.com/BHoM/BHoM_Engine/blob/40b5d28ee0feecce9481875bfe248be42cee8727/Reflection_Engine/Compute/RunExtensionMethod.cs#L96-L101

This, in principle makes sense, but in practice results in the error being recorded in cases where the code was failing silently. Silent failure was often an expected behaviour, therefore the new behaviour is not OK. The change made in #2331 needs to:
a) be rolled back
b) be followed by replacing of `RunExtensionMethod` with `TryRunExtensionMethod` where needed

Since we are late in sprint 5, the plan for this Milestone is a), with b) being executed in 4.2.

**Comment by pawelbaran** [comment]
@IsakNaslundBh @alelom @FraserGreenroyd I have not experienced this issue for a long time, therefore it tempts me to close this issue - how does that sound?

**Comment by FraserGreenroyd** [comment]
I'm happy with that approach @pawelbaran

**Comment by IsakNaslundBh** [comment]
Think I agree, and 

> b) be followed by replacing of RunExtensionMethod with TryRunExtensionMethod where needed

Has already been handled quite some time ago, so think this is fine to close.
