### ISSUE TITLE
Humans-Engine: documentation of method for measuring cValues

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM_Engine#2384]
#### What is missing/incorrect?
A graphical - non technical description of the method is required. Descriptions should provide links to this.

**Comment by rolyhudson** [comment]
Closing this as a first draft of documentation has been added [here](https://github.com/BHoM/documentation/wiki/BHoM-View-quality-conventions).

And link added to description of the method:
![Screenshot 2021-03-15 164856](https://user-images.githubusercontent.com/6618854/111189794-5b730380-85ae-11eb-8583-96ce43f3c443.jpg)

@al-fisher - thanks for the reminder to include the documentation on this 👍. Conversation is ongoing for best single source way to do this in the future maybe not in the documentation wiki.

**Comment by al-fisher** [comment]
Perfect - agreed - wiki is great place to start though.
But as you say, like the idea of a location of more permanence for critical wiki pages to be promoted to
