### ISSUE TITLE
Spatial_Engine: RoundCoordinates(Element2D) works for the whole panel, but fails for its openings

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_Engine#2419]
#### Description:

As in header. When given the whole panel the component doesn't raise any warning. However when rounding coordinates of the openings of the very same panel it raises a failed planarity check warning.

#### Steps to reproduce:

Test file.

#### Expected behaviour:

Should be consistent. 

#### Test file(s):

[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EmMbltkzmxVGoEImdqfEyHgBazCGdcg4qMBBw92xMaPbDA?e=cdNN7F)

**Comment by LMarkowski** [comment]
Might be caused by #2423

**Comment by FraserGreenroyd** [comment]
I've tested this today as part of the historical issue review and the issue can no longer be replicated. Openings of `IElement2D` are rounded suitably. I think it's safe to say that this issue has been resolved in the years since the bug was first found, so I'm closing this issue as resolved 😄
