### ISSUE TITLE
Architecture_Engine - handle nulls

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2462]
For the following methods:

 - [x] BH.Engine.Architecture.Compute.CeilingTiles(Ceiling ceiling, List<Line> ceilingTileLines, Double angleTolerance, Double distanceTolerance, Int32 decimalPlaces)
 - [x] BH.Engine.Architecture.Modify.CleanRoom(Room room, Double angleTolerance, Double minimumSegmentLength)
 - [x] BH.Engine.Architecture.Modify.SetGeometry(Room room, Point locationPoint, ICurve perimeterCurve)
 - [x] BH.Engine.Architecture.Modify.SetOutlineElements1D(Room room, List<IElement1D> outlineElements1D)
 - [x] BH.Engine.Architecture.Query.OutlineElements1D(Room room)
 - [x] BH.Engine.Architecture.Query.OutlineElements1D(Ceiling ceiling)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.CircularPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.EightArcPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.NoCornersPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.OrthogonalPlan(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.ActivityArea.ActivityArea(Polyline activityArea, Point activityFocalPoint)
 - [x] BH.oM.Architecture.Theatron.ProfileOrigin.ProfileOrigin(Point origin, Vector direction)
 - [x] BH.oM.Architecture.Theatron.SeatingBlock.SeatingBlock(ProfileOrigin start, ProfileOrigin vom, ProfileOrigin end, SeatingBlockType t, Double seatWidth, Double aisleWidth)
 - [x] BH.oM.Architecture.Theatron.TheatronGeometry.TheatronGeometry(TheatronPlan planFull, TheatronFullProfile profile, StadiaParameters sParams, List<ProfileParameters> pParams)
 - [x] BH.oM.Architecture.Theatron.TheatronGeometry.TheatronGeometry(TheatronPlan planPart, TheatronFullProfile profile, List<ProfileParameters> pParams)
 - [x] BH.oM.Architecture.Theatron.TheatronFullProfile.TheatronFullProfile(List<ProfileParameters> parameters, TheatronPlan planGeometry)
 - [x] BH.oM.Architecture.Theatron.TheatronFullProfile.TheatronFullProfile(List<ProfileParameters> parameters, Point focalPoint, ProfileOrigin sectionOrigin)
 - [x] BH.oM.Architecture.Theatron.TheatronPlan.PlanGeometry(StadiaParameters parameters)
 - [x] BH.oM.Architecture.Theatron.TierProfile.TierProfile(ProfileParameters parameters, Point lastPointPrevTier)
 - [x] BH.oM.Architecture.Theatron.TierProfile.TransformProfile(TierProfile originalSection, Vector scale, Point source, Point target, Double angle)

**Comment by FraserGreenroyd** [comment]
@rolyhudson be advised I fixed the TransformProfile `should be modify` comment and versioned it appropriately.

**Comment by rolyhudson** [comment]
@FraserGreenroyd you are a legend. Cheers - looking forward to buying you a beer for this. 🍻
