### ISSUE TITLE
Add US (AISC) Steel Sections to reference datasets

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM_Engine#248]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Found this guy here when combing through. Think this can be closed now @JosefTaylor ?
