### ISSUE TITLE
Physical_Engine: Create.Floor doesn't create openings

### ISSUE THREAD

**Issue by mikolaj-nazarczuk** [BHoM/BHoM_Engine#2492]
#### Description:

As in header

#### Steps to reproduce:

See the test file

#### Expected behaviour:

Should create a floor with opening

#### Test file(s):

[SharePoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Physical_Engine/%232492%20-%20CreateFloor%20doesn%27t%20create%20openings?csf=1&web=1&e=wQNbht)

**Comment by LMarkowski** [comment]
@mikolaj-nazarczuk, I've let myself tidy the test script up a bit.

![image](https://user-images.githubusercontent.com/48125514/116208907-a81b3400-a741-11eb-968c-10803f1b1138.png)

I think it looks more like a bit non-intuitive inconsistence than a bug. @pawelbaran, do you have any view on why it was resolved like that?

**Comment by mikolaj-nazarczuk** [comment]
Imo best way to create floor using first method (edges/internalEdges) is like this. Not with opening, shaft etc. but editing profile.
![image](https://user-images.githubusercontent.com/75316519/116213230-e61a5700-a745-11eb-95c1-513c6bfc5711.png)

**Comment by pawelbaran** [comment]
Looking at this issue now, the behaviour seems correct to me. Could you please confirm and close if so, @IsakNaslundBh?

**Comment by pawelbaran** [comment]
Actually, I will close it now, feel free to reopen if you disagree @IsakNaslundBh
