### ISSUE TITLE
Environment_Engine: Add Create method for Node including TimeIndexResult

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM_Engine#2512]
#### Description:

Add the following methods to support more user friendly creation of Nodes with associated `TimeIndexedResult`s.
- `TimeIndexResultFromList` - Input a list of values and a `Type` of `IAnalysisResult` to generate a list of `TimeIndexedResult`s (with default indices of 0 to n).
- `CheckTimeIndexResultsShape` - Input a list of `TimeIndexResult`s and return True/the objects if all objects containing the same shape/length results sets (so that they can align and be queried based on time-index value when associated with Nodes later).
- `Create.Node` - Usual values for creating a Node, but with behind the scenes checks to align n sets of `TimeIndexResults` with n nodes

Relies on https://github.com/BHoM/BHoM/pull/1206.

Additional methods that might be useful currently exist on a branch related to issue #2371, [here](https://github.com/BHoM/BHoM_Engine/tree/Environment_Engine-%232371-IAnalysisResultOperations).

**Comment by tg359** [comment]
This issue should probably have been closed, but here's a related one - https://github.com/BHoM/BHoM/issues/1189

**Comment by Tom-Kingstone** [comment]
@tg359 should it be closed now? It looks like this has been captured in the other issue fairly comprehensively.

**Comment by tg359** [comment]
> @tg359 should it be closed now? It looks like this has been captured in the other issue fairly comprehensively.

Yes I think so. It's long enough ago too that any need for it that hasn't referenced this issue has likely solved it - or not been worth solving in the first place.
