### ISSUE TITLE
Spatial_Engine: Add method to query an element's dominant orientation

### ISSUE THREAD

**Issue by tiagogrossi** [BHoM/BHoM_Engine#2537]
#### Description:
Sometimes it's very useful to know a shape's orientation, such as a room (through its boundaries). The method should receive inputs from both IElement1D and 2D

**Comment by tiagogrossi** [comment]
@FraserGreenroyd can you give some advice on this please? Because my inputs are either `IElement1D` or `IElement2D` I need to query their `IGeometry`, which comes from Spatial_Engine and has a reference to Geometry_Engine. Therefore I can not add a reference to Geometry_Engine of Spatial_Engine due to circular references. Should I then add this query method to spatial?

**Comment by FraserGreenroyd** [comment]
I would advise doing this in spatial engine @tiagogrossi - anything using `IElement` interfaces belongs in Spatial engine, while Geometry Engine is more for the raw geometry operations.
