### ISSUE TITLE
Acoustic_Engine: Conform to BHoM_Test

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#260]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Testing strategy has completely changed since this issue was opened, with the UnitTests being able to be added. BHoM_Test references in the issue is no longer used and has not been for quite some time.

Will close this issue, feel free to reopen if anyone disagree.
