### ISSUE TITLE
Environment_Engine: Make openings as ratio of wall or floor area

### ISSUE THREAD

**Issue by jamesramsden-bh** [BHoM/BHoM_Engine#2626]
#### Description:

In early stage design, the sizing of the windows is commonly defined as a ratio of wall or floor area, without particular concern for an individual window's placement or size. A new method (or set of methods) is required to allow window openings to be automatically generated on a space's external walls. 

A possible algorithm for producing an opening based on floor area could be:
1) The user defines the external wall of a space with a polyline (either by tracing over the edge of the space, or scoring over the edge of the space similar to how airwalls are defined)
2) The method calculates the floor area of the space
3) The method takes a ratio value from the user, and multiplies this by the floor area to get an intended opening area
4) Where more than one walls are selected as being external, this intended opening area is shared in proportion to the area of each of these external walls
5) Openings are then defined as being centrally positioned on the wall, with a sill height of 0.9m, with a top-of-window height of 0.2m below the top of the wall panel, and a width as required to provided the required opening area

A possible algorithm for producing an opening based on wall area would be the same as steps 1 and 5 above, with the user providing an intended opening-to-wall ratio.

**Comment by Tom-Kingstone** [comment]
On review of this historic issue, a new issue was raised in december that captures the contents of this issue, so I will link this issue there, and close this one, as well as deleting it's linked branch (as it is behind by a lot of commits).
