### ISSUE TITLE
Verification: Align with Reflection_Engine changes

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2692]
#### Suggestions to restore compliance:

https://github.com/BHoM/BHoM_Engine/pull/2681 changed a method name. Requires updating in the verification.

@pawelbaran @FraserGreenroyd @adecler  FYI

**Comment by pawelbaran** [comment]
Isn't that closed with https://github.com/BHoM/BHoM_Engine/pull/2693 @IsakNaslundBh? Looks like you made a typo in the PR description.

**Comment by IsakNaslundBh** [comment]
> Isn't that closed with #2693 @IsakNaslundBh? Looks like you made a typo in the PR description.

Yes, you are right
