### ISSUE TITLE
Environment_Engine: Space Checking Method

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_Engine#2701]
#### Description:

Implement method for checking spaces (see screenshot below, per conversation with @rboulton-BH) This method is key to the proper implementation of IsContaining for spaces 

![image](https://user-images.githubusercontent.com/34316256/142262452-6eedcb4a-6e10-494c-91d7-f67ab62ff859.png)

**Comment by FraserGreenroyd** [comment]
@emilsvedjer the best way to do this is to do a method returning 2 outputs, one of 'valid' spaces and one of 'invalid' based on these three parameters:

 - If space perimeter length is == 0
 - If space perimeter length is self-intersecting (if the method exists in geometry engine to do that)
 - If space perimeter is not closed

The last option, regarding Revit parameters, will not be able to be done in a method that sits in the Environment Engine. Following discussion with @rboulton-BH this is an edge case check for something - @kayleighhoude can you provide more details on what the edge case was?

**Comment by kayleighhoude** [comment]
@FraserGreenroyd the unclean spaces in this example were pretty typical of a Revit model that we would be utilising in MEP @emilsvedjer if you could lmk which sprint we're planning this for next milestone would be appreciate :)
