### ISSUE TITLE
Serialiser_Engine: add WriteToFile and ReadFromFile methods

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2727]
#### Description:

As discussed with @alelom at some point, using `FileAdapter` to simply save a few BHoM objects to a file (or load them) on the back end is not always ideal - for such simple operations it could be worth to have methods like `WriteToFile` and `ReadFromFile`

I am happy to implement these, but would like to confirm with others before this gets tackled. Any concerns @adecler @al-fisher @IsakNaslundBh @FraserGreenroyd?

**Comment by adecler** [comment]
I am not too sure about this one. That would break the nice separation of concerns that we have between the Serialiser engine and the file adapter. A simple example to this is that the serialiser is OS independent while the file adapter is not. 

I also quite like that every single transfer to another platform (including files) is working the same way. This mean that there is no learning curve between saving files and sending data to an external software. If we change the way it works for file, what prevents us from asking the same for some other adapter ?

**Comment by alelom** [comment]
As per our chat @pawelbaran maybe we could just write `WriteToFile()` and `ReadFromFile()` methods (they already exist in the File_Adapter, actually, but I don't think they're public) and expose them in the UI directly, if useful. They could then be OS-specific if needed in the future. I agree with @adecler that the Serialiser_Engine should be OS independent, especially if we want to move to a more service-oriented BHoM.

**Comment by pawelbaran** [comment]
I agree and like the idea @alelom 👍 Actually, I would even consider whether the method should be exposed to the UI (it will by definition I guess), or maybe just available on the back end not to distract the users from using the File adapter.

**Comment by alelom** [comment]
@pawelbaran can we consider this closed by https://github.com/BHoM/File_Toolkit/pull/130?

**Comment by pawelbaran** [comment]
Yeah definitely - solved by https://github.com/BHoM/File_Toolkit/pull/130, thanks @alelom 👍
