### ISSUE TITLE
Verification: Check class maps of generic types correctly registred

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2728]
#### Description:

after https://github.com/BHoM/BHoM_Engine/pull/2724 we should add a secondary test for the serialiser verification that ensures that the issue solved by the linked PR, which relates to serialisation of inner generic objects is properly tested for. Should not be an issue after the linked PR, but test to be added to make sure any changes to the code does not bring back that issue.

**Comment by FraserGreenroyd** [comment]
I'm closing this as the new serialiser engine does not rely on class maps. Please reopen if you think we should still investigate! 😄
