### ISSUE TITLE
Base_Engine: Remove ThreadStatic attribute from m_DebugLog field to enable recording events in multithreaded code

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2745]
#### Description:

As in the title, I would like to enable recording events in multithreaded code. Currently it is impossible because of `m_DebugLog` field having `ThreadStatic` attribute, which results in the field value being set to default on each thread that attempts to access it. I guess the attribute has been added for a reason, so it would be great if someone could shed some light on that, @adecler @IsakNaslundBh @FraserGreenroyd?

I am considering whether it would be OK to make the access to log thread safe by putting it behind `lock` or, alternatively, by changing its `List` properties to `ConcurrentBag`? The 1st option sounds best to me, but curious what do others think.

Happy to action the decision made in here as it is pretty relevant to my current work 👍

**Comment by IsakNaslundBh** [comment]
If this is handled, it can close https://github.com/BHoM/BHoM_Engine/issues/2009 as well as essentially duplicate issue. 👍
