### ISSUE TITLE
FindFragment doesn't work for interface types

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#2753]
#### Description:
If the type `T` in `FindFragment<T>()` is an interface, FindFragment returns null even if a fragment implementing that interface is in the FragmentSet.

I couldn't find another method that cover that case (e.g. returning all fragment implementing that interface).

**Comment by IsakNaslundBh** [comment]
Think this method should cover the case you are after @adecler  https://github.com/BHoM/BHoM_Engine/blob/main/BHoM_Engine/Query/GetAllFragments.cs ?

A bit confusing with the different method names though. Maybe that method should be called `FindFragments` or something like that.

**Comment by adecler** [comment]
Thanks @IsakNaslundBh , I managed to missed that one for some reason.
