### ISSUE TITLE
Geometry_Engine: RandomGeometry creates are not thread safe

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2801]
#### Description:

The random geometry create methods are not thread safe as they all make use of the same instance of the Random class which is not itself thread safe. This can in some cases lead to weird crashes due to race conditions. The random create for vector is for example used in the IsContaining method which makes this important to fix to be able to parallelise any algorithm depending on that particular methods (which are tonnes, including boolean methods for polylines/polycurve)

#### Steps to reproduce:

Hard to reproduce with high reliability as with most race condition issues, but parallelising a method that relies on for example IsContaining leads to crashes sporadically happening.

#### Expected behaviour:

For thread saftey to be guarantied for the Create methods. A simple lock when extracting NextSeed should hopefully do.

**Comment by FraserGreenroyd** [comment]
Playing hard ball here, but are `RandomGeometry` Create methods really necessary anymore? Are they really beneficial here in the core engine?

Would it be more beneficial to move those methods to Test_Toolkit for testing purposes?

I note you do mention

 > The random create for vector is for example used in the IsContaining method

I would ask why - though I don't know enough of the codebase in the Geometry Engine so will accept if it does need to be there.

But this would be my initial question, before we look at fixing race conditions, as to whether we even need the methods moving forward? (And if we do, absolutely fine, but meh, I like asking questions 😉 )

**Comment by IsakNaslundBh** [comment]
> I would ask why - though I don't know enough of the codebase in the Geometry Engine so will accept if it does need to be there.

It is used to create a random infinite line in the plane of the curve from the point that is checked if it is inside the curve being checked. The infinite line is then intersected with the curve, and  the number of intersection points % 2 is used to determine if the point is inside the curve or not.

This is to the best of my knowledge the most common way to perform this check, using random vectors.

Also, to make this thread safe is no big task, just a simple lock to be but in place, hence might as well get it fixed, but happy for you to raise an issue about removing the other create methods if you think they should not be there, as I would argue that is a separate issue :)
