### ISSUE TITLE
Geometry_Engine: IsContaining tolerance needs reversing if !acceptOnEdge

### ISSUE THREAD

**Issue by jamesramsden-bh** [BHoM/BHoM_Engine#2863]
The EnvironmentEngine test procedure is currently failing test 1.5.9. This was isolated to the Environment_Engine.Query.IsContaining, and then in turn to Geometry_Engine.Query.IsContaining method. The test only fails when `acceptOnEdge = false`. (Note that this test case used a point that was in the centre of the panel in question.) It appears that the tolerance in this method has been incorrectly implemented in this case. 

Currently, from line 81 reads: 
```
            if (acceptOnEdge)
            {
                return (pt.X >= min.X - tolerance && pt.X <= max.X + tolerance &&
                        pt.Y >= min.Y - tolerance && pt.Y <= max.Y + tolerance &&
                        pt.Z >= min.Z - tolerance && pt.Z <= max.Z + tolerance);
            }
            else
            {
                return (pt.X > min.X + tolerance && pt.X < max.X - tolerance &&
                        pt.Y > min.Y + tolerance && pt.Y < max.Y - tolerance &&
                        pt.Z > min.Z + tolerance && pt.Z < max.Z - tolerance);
            }
```

when it should read

```
            if (acceptOnEdge)
            {
                return (pt.X >= min.X - tolerance && pt.X <= max.X + tolerance &&
                        pt.Y >= min.Y - tolerance && pt.Y <= max.Y + tolerance &&
                        pt.Z >= min.Z - tolerance && pt.Z <= max.Z + tolerance);
            }
            else
            {
                return (pt.X > min.X - tolerance && pt.X < max.X + tolerance &&
                        pt.Y > min.Y - tolerance && pt.Y < max.Y + tolerance &&
                        pt.Z > min.Z - tolerance && pt.Z < max.Z + tolerance);
            }
```

My theory may not be correct, so ensure it is well tested before submitting!

**Comment by IsakNaslundBh** [comment]
I do get where you are coming from, but I actually think it is correct the way it has been implemented.

Consider the following 4 cases for the 2d case where the tolerance has been set really high for illustration purposes. This can ofc be extrapolated to a 3d cuboid:

![image](https://user-images.githubusercontent.com/22005920/174013853-2eeafcbb-c4cd-4228-989c-6cbcc5debf6c.png)

you then have:

0. clearly inside -> true independent of value of `acceptOnEdge`
1. inside, within tolerance of boundary/edge -> deemed "on Edge" -> true if acceptOnEdge is true, false if acceptOnEdge is false.
2. outside, within tolerance of boundary/edge -> deemed "on Edge" -> true if acceptOnEdge is true, false if acceptOnEdge is false.
3. clearly outside -> false independent of value of `acceptOnEdge`

What `acceptOnEdge` is controlling is basically if points within the zone of +tol and -tol should be tolerated or not, as points in that zone are on the edge of the `BoundingBox`, within given tolerance. What this basically means is that `acceptOnEdge` sort of controls if you are inside the +tol box or within the -tol box.

Now, looking at the source of your issue, I suspect it is the Environment_Engine method that needs to be updated. When using boundingBoxes to pre-filter for `IsContaining` before any more detailed checks are done `acceptOnEdge` should generally always be true. This is, I would hardcode the call in here:

https://github.com/BHoM/BHoM_Engine/blob/3ec57b210b3afcec82f8d504a470df5252e9c3d1/Environment_Engine/Query/IsContaining.cs#L112-L113

to true, independent of the input variable. I think this should be fine to do, as I read that particular input variable to be referring to the edge of the panel, not the edge of the `BoundingBox` of the panel. I think this should be the general strategy when pre-filtering with bounding boxes, especially for flat objects that can be aligned with any of the world axis systems, resulting in flat boxes. This is also what is being done when pre-filtering other potential flat geometries with bounding boxes, see:

https://github.com/BHoM/BHoM_Engine/blob/3ec57b210b3afcec82f8d504a470df5252e9c3d1/Geometry_Engine/Query/IsContaining.cs#L198-L199

and

https://github.com/BHoM/BHoM_Engine/blob/3ec57b210b3afcec82f8d504a470df5252e9c3d1/Geometry_Engine/Query/IsContaining.cs#L321-L322

for example.

Quite lengthy answer, but wanted it to be as clear as possible. Had a discussion with @pawelbaran on the subject a few years back when I slightly questioned it in a similar manner, and was convinced that this is the correct solution, and I still think it is.

**Comment by pawelbaran** [comment]
Agreed with @IsakNaslundBh, I had a fresh look at the code for bounding boxes and still believe it is fine, so possibly your test assumptions need some adjustment @jamesramsden-bh?

**Comment by jamesramsden-bh** [comment]
Closing as, after talking with @IsakNaslundBh , the actual issue was with the definition of the word 'edge'. Isak is going to redefine `acceptOnEdge` to something like acceptOnBoundary or acceptOnFace. I will change the Environment_Engine code to suit the code here.
