### ISSUE TITLE
Environment_Engine: Split Building Elements

### ISSUE THREAD

**Issue by sofmal** [BHoM/BHoM_Engine#292]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
No longer an issue as there are methods to clean and split panels within the engines now. New issues to be raised if problems with those methods/functionalities.
