### ISSUE TITLE
Reflection_Engine: Add a method to query subtypes of a type

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2964]
#### Description:

In some cases (mainly in adapter actions - see https://github.com/BHoM/Mongo_Toolkit/issues/166) it is needed to get all subtypes of a type, so would be good to add a method that does it.

**Comment by FraserGreenroyd** [comment]
Ah no, forgive me, he did the opposite - getting all base types of a type, not the sub types... Though he still needs to PR his change up to Reflection Engine from my review 😄
