### ISSUE TITLE
Modify all website urls within BHoM related repositories to reference a central location

### ISSUE THREAD

**Issue by travispotterBH** [BHoM/BHoM_Engine#3027]
#### Description:

Links to websites as exposed through buttons in each UI should be located in a central location so that a links can be updated across all UIs in one modification.

**Comment by travispotterBH** [comment]
See these:
https://github.com/BHoM/Excel_UI/pull/381

**Comment by desaiwangBH** [comment]
Existing link types: (WIP)

Documentation: some needs to be updated to bhom.xyz
- https://bhom.xyz/
- https://github.com/BHoM/documentation/wiki
- *parts of the wiki is still on github, ex. Specific Structural Engineering adapters (Robot, GSA, Etabs, Lusas)

Codebase: https://github.com/BHoM/... 

External:
- GH forum: https://www.grasshopper3d.com/forum/topics/grasshopper-icons-vector-sourc
- Revit Documentation: https://help.autodesk.com/view/RVT/2022/ENU/?guid=GUID-BC1DC181-B6D0-4479-8385-363A9EE5E75E
- GitHub Documentation: https://docs.github.com/en/get-started/quickstart/github-flow
- .NET Documentation: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual

Image: 
- https://raw.githubusercontent.com/BHoM/documentation/main/Images/logos/BHoM_Logo.png
- https://raw.githubusercontent.com/SciSharp/Keras.NET/master/Images/XOR_Output.PNG
- https://raw.githubusercontent.com/SciSharp/Keras.NET/master/Images/MNIST_Output.PNG

Style sheets:
- https://fonts.googleapis.com/icon?family=Material+Icons
- https://code.getmdl.io/1.3.0/material.indigo-pink.min.css
