### ISSUE TITLE
Humans_Engine: Documentation URL

### ISSUE THREAD

**Issue by desaiwangBH** [BHoM/BHoM_Engine#3075]
https://github.com/BHoM/BHoM_Engine/blob/34a943b8ca2cde64e124b5994df2d26b2c65884d/Humans_Engine/Query/CvalueAnalysis.cs#L41

https://github.com/BHoM/BHoM_Engine/blob/34a943b8ca2cde64e124b5994df2d26b2c65884d/Humans_Engine/Query/CvalueAnalysis.cs#L61

Need to call DocumentationURL to generate URL instead of having it as a constant string.

Lines 41, 61, both in descriptions of methods.

**Comment by travispotterBH** [comment]
Hmm. Thinking about this. If these are going to be in Descriptions. 
This won't work.
![image](https://github.com/BHoM/BHoM_Engine/assets/96432552/3f409d04-15b7-4ba6-aca0-6c7d4a83a3c9)
Applies to all issues where the idea is to use this method in an attribute. Its compile time vs runtime issues. 



Please correct me if I'm wrong, but I don't believe there is a way around this. @FraserGreenroyd 


I attempted this, but it won't work either: 
![image](https://github.com/BHoM/BHoM_Engine/assets/96432552/be127323-80fd-453f-afab-f1ba82565ee5)
