### ISSUE TITLE
Environment_Engine: compute method to create openings on external panels by glazing ratio

### ISSUE THREAD

**Issue by FelixMallinder-BH** [BHoM/BHoM_Engine#3226]
#### Description:

Method to calculate window sizes based on glazing ratio, for externally facing panels and create openings. 

Inputting a list of panels, which have assigned spaces. identifying the external facing panels, and removing panels that have been chosen to be ignored. Using the area of the then-selected panels, calculate an allowed area for glazing and as such, the dimensions of the windows, uniformly to adhere to the calculated area. Then, generate openings for the given window dimensions, on identified panels from input point locators.

Inputs:
- sill height
- window height 
- glazing ratio
- opening type
- window points
- panels 
- panels to ignore 

Outputs:
- openings

**Comment by Tom-Kingstone** [comment]
see also - #2626
