### ISSUE TITLE
Geometry_Engine: Offset polyLine not working as expected 

### ISSUE THREAD

**Issue by KalleEdstroem** [BHoM/BHoM_Engine#3235]
#### Description:

Used offset method on a PolyLine object. 
Which created a "dent" in the PolyLine output.

![offset issue](https://github.com/BHoM/BHoM_Engine/assets/143606343/ad92584a-5a7e-4b3c-a3a0-5ac8996a6a99)

Problems occurs in this method:
https://github.com/BHoM/BHoM_Engine/blob/7aceffd25882b46cc9ba497c6e2b948f95fabdf6/Geometry_Engine/Modify/Offset.cs#L133

#### Steps to reproduce:

Test script shows issue. 

#### Expected behaviour:

Expected behavior is that the offset output keeps the same shape as the input. Behavs same as the Rhino version of offset shown in testscript. 

#### Test file(s):

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233235%2DOffsetProducingDentICurve%2Egh&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine

**Comment by FraserGreenroyd** [comment]
@KalleEdstroem is this not covered by #1333 ?

**Comment by KalleEdstroem** [comment]
I would guess that the things mentioned in #1333 are the reasons why this bug is occurring.
