### ISSUE TITLE
Infinite loop on Split(Polyline, cuttingLines)

### ISSUE THREAD

**Issue by vietle-bh** [BHoM/BHoM_Engine#3270]
#### Description:

The prophecy has come true. My method managed to not run out of children 😅
https://github.com/BHoM/BHoM_Engine/blob/d13f40bb41726cb0b8ab3b4c809ac6819a8266a5/Geometry_Engine/Compute/Split.cs#L82

![image](https://github.com/BHoM/BHoM_Engine/assets/102604891/5215121c-10cd-4f74-9930-5d2910888628)

**Comment by vietle-bh** [comment]
Hi @FraserGreenroyd , do you know who created this method and therefore knows best how to break this infinite loop?

**Comment by FraserGreenroyd** [comment]
@vietle-bh this was made by @JohannaOlin1 and myself back in 2020/2021.

Can you upload some test files and we can take a look (or are you taking a look and just wanted to know who to ask for tips if needed?)? 😄

**Comment by vietle-bh** [comment]
Thanks @FraserGreenroyd , it would be great to have this handled by the experts 😉 
I'll create the test file and share it here Asap.
