### ISSUE TITLE
Geometry_Engine: Update unit tests for methods modified in 7.1

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Engine#3277]
#### Broken rules:

Unit tests need updating for the methods modified in this PR:
https://github.com/BHoM/BHoM_Engine/pull/3275

#### Suggestions to restore compliance:

Create unit tests

**Comment by pawelbaran** [comment]
TODO: also cover methods modified in https://github.com/BHoM/BHoM_Engine/pull/3280 and https://github.com/BHoM/BHoM_Engine/pull/3283

**Comment by pawelbaran** [comment]
TODO: more to cover, https://github.com/BHoM/BHoM_Engine/pull/3290, https://github.com/BHoM/BHoM_Engine/pull/3292, https://github.com/BHoM/BHoM_Engine/pull/3293, https://github.com/BHoM/BHoM_Engine/pull/3298
