### ISSUE TITLE
Structure_Engine: Syncing of input and output property names

### ISSUE THREAD

**Issue by DanielJonssonBH** [BHoM/BHoM_Engine#335]
Some of the objects in the Structure_Engine Create Class have different names for their inputs and properties. So when you want to get back a propertya property back you first need to explode the objects in order to see what the actual property name to query is. It's a very quick fix to just change the constructors to be consistent in the naming conventions.

For example, here slabDepth becomes Thickness and depthX TotalDepthX etc:
image

Below I've listed the inconsistent ones I've found when creating the unit tests.

AreaTemperatureLoad:
t --> TemperatureChange

GravityLoad:
direction --> GravityDirection

PointVelocity:
Translation --> TranslationalVelocity
rotation --> RotationalVelocity

LoadingPanelProperty:
supportCondition --> LoadApplication

Reinforcement:
count --> BarCount

Ribbed:
slabDepth --> Thickness

RigidLink:
constraint misspelled

ChannelProfile:
width --> FlangeWidth

SteelTSection/SteelISection:
flangeWidth --> Width

Waffle:
slabDepth --> Thickness
depthX/Y --> TotalDepthX/Y

**Comment by IsakNaslundBh** [comment]
many of these handled or made obsolete after the added autogenerated creates.

GravityLoad still outstanding though.
