### ISSUE TITLE
Geometry_Engine: NurbsCurve Bounds gives no tight box

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#344]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
@epignatelli is that still relevant? Is it related with #710 by any means?

**Comment by kThorsager** [comment]
duplicate of #1097

**Comment by pawelbaran** [comment]
Let's close it then
