### ISSUE TITLE
Geometry_Engine: Fix Query.Edge methods

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#394]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After reviewing this issue, cannot replicate the original issue. As it is possible that this has been resolved otherwise in the intervening years, I am closing this issue for now. This can be reopened if any new information is found.
