### ISSUE TITLE
Geometry_Engine: Failing EndDir and StartDir methods for Nurbs curve and Circle

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#397]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
While it is missing for `Nurbs`, I cannot replicate it failing for `Circle`. As such, I'm closing this issue for now as it is stale and lacking information to help it be closed suitably. I would recommend, should people need it in the future, we raise a feature issue for the missing method (as it would be new) and a new bug issue for circle if any further information comes about to help identify any issues with circle `EndDir` calculations 😄
