### ISSUE TITLE
Geometry_Engine: All tests for ExternalEdges and InternalEdges are failing or not implemented. 

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#398]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After reviewing the old issue, I have determined that the tests for ExternalEdges are passing, but the tests for InternalEdges could not be replicated, and therefore this can't be closed as completed. This issue will be closed for now, but if any new issues occur, this can be reopened and discussed again.
