### ISSUE TITLE
Units_Engine: Establish strategy for units engine implementation

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM_Engine#406]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by al-fisher** [comment]
This has been resolved positively as a question [here](https://github.com/BHoM/Localisation_Toolkit/issues/11)
With new actions [here](https://github.com/BHoM/Localisation_Toolkit/issues/18)
