### ISSUE TITLE
Geometry_Engine: Query.IsPlanar is incorrect for Polyline, NurbCurve, and Mesh

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#412]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
The original issue can no longer be replicated and is assumed to have been fixed in the years since the issue was raised. Closing it for now.
