### ISSUE TITLE
Spatial_Engine: Merge FabricatedBox and GeneralisedFabricatedBox (Profiles and SectionCurves)

### ISSUE THREAD

**Issue by DanielJonssonBH** [BHoM/BHoM_Engine#416]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Having reviewed this historic issue as part of the 2024 kick-off, and reviewing the code in todays format, it appears that the context of the original issue is no longer valid and that time has superseded the original requirements of this issue. As such, I am closing this issue as stale, however, if anyone feels differently, please feel free to reopen :smile:
