### ISSUE TITLE
Geometry_Engine: Query.Normal methods failing

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#425]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
I have reviewed this issue and cannot replicate the original issue. As @FraserGreenroyd's comment says the issue seems to have been resolved. So I'm closing this issue for now. If anyone has further information please feel free to reopen.
