### ISSUE TITLE
Geometry_Engine: Query.ParameterAtPoint failing for POlyline and NurbsCurve

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#426]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After review of historical issues, I have determined that this issue should be closed, as ParameterAtPoint is currently not implemented for NurbsCurve, so is expected to fail here, and ParameterAtPoint for PolyLine is now working correctly after testing with current unit tests.
