### ISSUE TITLE
Geometry_Engine: Query.SamplePoints is failing for some of the curves

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#432]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
Closing this issue due to its age and due to the unit test script no longer being supported by BHoM. Please reopen if necessary with an updated test script.
