### ISSUE TITLE
Geometry_Engine: Query.SubParts is failing for Mesh, PolySurface, and CompositeGeometry

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#436]
Reflecting info from #437.

#### Methods failing due to incorrect implementation:

- [ ] Mesh

#### Methods failing due to other methods:

 PolySurface BuroHappoldEngineering/Rhinoceros_Toolkit#57
 CompositeGeometry BuroHappoldEngineering/Grasshopper_Toolkit#235
The unit test requires update since the child issues above have been solved.

**Comment by IsakNaslundBh** [comment]
From some testing on this, this seems to work as indented on my machine. CLosing for now - To be reopened if issue presists
