### ISSUE TITLE
Geometry_Engine: SplitAtPoints missing methods for Arc, Circle, NurbCurve, PolyCurve and ICurve

### ISSUE THREAD

**Issue by hedvigkjellander** [BHoM/BHoM_Engine#447]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
There currently exists methods for everything mentioned except for NurbCurves. If a method for NurbCurves is still needed please raise a new issue for that as I am closing this stale issue for now.
