### ISSUE TITLE
Geometry_Engine: ProjectAlong issues from TestScript

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#448]
Unit test here: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Modify/[Scale.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Modify/Scale.gh?csf=1&web=1&e=dWrlqc)?csf=1&web=1&e=dWrlqc

Methods failing without exceptions:

 Plane
 Arc
 Circle
 PolyCurve
 Loft
 CompositeGeometry
 CoordinateSystem
Methods failing due to other issues:

 NurbsSurface #441
 PolySurface #441
Methods that needs to be restructured:

 Vector Scale(Vector vector, Double rad, Vector axis) is a Rotate method, not sure why it is here

**Comment by vietle-bh** [comment]
Closing this issue due to its age and the unit test script no longer works with the current version of BHoM. Please reopen if necessary with an updated test script.

![image](https://github.com/BHoM/BHoM_Engine/assets/102604891/e6347cfd-ba9d-40c8-804f-aa6badee3386)
