### ISSUE TITLE
Geometry_Engine: NurbForm issues from test script

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#452]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
@epignatelli is that still relevant after superseding nurbs?

**Comment by epignatelli** [comment]
Nope! Closing, thanks!
