### ISSUE TITLE
Geometry_Engine: Should angle tolerance refer to dot product or angle?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#455]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After reviewing historical issues, This issue will be closed as completed, as the Angle method uses the dot product in every case (apart from the angle of Arcs, though that has predefined start and end angles). If this issue comes up again in future, this can be reopened again.
