### ISSUE TITLE
Geometry_Engine: Quaternion issues from unit test

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#464]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After review of historic issues, this issue can not be replicated. A quick look at the code itself (and review of the actual maths involved) shows that the logic itself is correct. It is assumed that this issue has been fixed since it was raised. Closing as completed.
