### ISSUE TITLE
Geometry_Engine: PolYSurface issues from unit test

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#465]
Methods failing due to other issues:

 PolySurface PolySurface(IEnumerable<ISurface> surfaces) https://github.com/BuroHappoldEngineering/Rhinoceros_Toolkit/issues/57

**Comment by Tom-Kingstone** [comment]
After review of historic issues, this issue can not be replicated. After checking basic logic, there seems to be no issues. This issue is assumed to be completed since it was created, and will be closed as such
