### ISSUE TITLE
Structure_Engine/Environment_Engine: Shall take a look at what objects we want to display?

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#469]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by rboulton-BH** [comment]
I believe this has now been completed through other development not referenced here so I am closing the issue. Please feel free to re-open if you disagree
