### ISSUE TITLE
Reflection_Engine: Add an optional link to Wiki as a method attribute

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#471]
As discussed on the call, it would be nice to have an option to add a link that would land on a relevant Wiki page -> this could be added to the context menus in Grasshopper/Dynamo etc.

**Comment by adecler** [comment]
@FraserGreenroyd , I'll let you decide if this issues is still relevant or not.

**Comment by al-fisher** [comment]
@alelom I think we discussed this idea again very recently as well as part of your revamp of documentation. 
I would support formalising embedding of hyperlinks in Descriptions like here: https://github.com/BHoM/BHoM/blob/84ebcb85cb25b27636829a30ce351f7ea586d698/Dimensional_oM/IElement0D.cs#L30
Having an Attribute or similar giving proper conventions will make scrapping easier and then not least of all they can then more easily be checked in compliance/CI if the hyperlinks are at least valid etc. etc. As we add more - checking they are not outdated may become an issue.
@alelom @FraserGreenroyd one for you both to perhaps propose best way you both want to handle 😄
