### ISSUE TITLE
Geometry_Engine: Compute.RowEchelonForm and other methods in the file should use the Matrix class as input

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#480]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
This issue has been stale for years and had never appeared as an actual problem - closing it on that basis, please feel free to reopen if you disagree.
