### ISSUE TITLE
Geometry_Engine: All Compute>SortAlongCurve methods failing.

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#481]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
Closing this issue due to its age and the unit script no longer works with the current version of BHoM. Please reopen if needed with an updated test script.
![image](https://github.com/BHoM/BHoM_Engine/assets/143594852/f0ed0667-a8fb-41ca-a919-8eb9e2f732e2)
