### ISSUE TITLE
Geometry_Engine: Query.Product issues from unit test

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#492]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
I have reviewed the historic issue and cannot replicate the original issue described. It is possible the bug has been resolved in the intervening years since the issue was opened, so I'm closing this issue for now. If anyone has further information on this issue please feel free to reopen 😄
