### ISSUE TITLE
Geometry_Engine: Query.IsPlanar issues from unit tests

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#493]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by Tom-Kingstone** [comment]
After review of unit test script, have tried to recreate this bug and cannot be replicated. Closing this issue until someone finds a new issue with these tests.
