### ISSUE TITLE
Structure_Engine: Some Interface method do not cover all the types

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#500]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Closing this as the method the issue was targeting has been migrated out of Structure_Enigne
