### ISSUE TITLE
Geometry_Engine: All methods should be extension methods

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#502]
Here's the list of failing methods

 - BH.Engine.Geometry.Convert.ToPolyline(NurbCurve)
 - BH.Engine.Geometry.Convert.ToPolyline(Arc)
 - BH.Engine.Geometry.Convert.ToPolyline(Circle)
 - BH.Engine.Geometry.Convert.ToPolyline(Line)
 - BH.Engine.Geometry.Convert.ToPolyline(Polyline)
 - BH.Engine.Geometry.Convert.ToPolyline(ICurve)
 - BH.Engine.Geometry.Query.IsValid(IGeometry)
 - BH.Engine.Geometry.Query.IsValid(IGeometry)
 - BH.Engine.Geometry.Query.ShearArea(List, Double, Double)
 - BH.Engine.Geometry.Query.SliceAt(IList, Double, Double, Plane, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double&)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double, Double, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Vector, ICurve, Double, Double, Double&)
 - BH.Engine.Geometry.Query.AreaIntegration(List, List, Vector, ICurve, Double, Double, Double&)
 - BH.Engine.Geometry.Query.Bounds(List)

**Comment by pawelbaran** [comment]
Methods:
- BH.Engine.Geometry.Convert.ToPolyline(NurbCurve)
- BH.Engine.Geometry.Convert.ToPolyline(Arc)
- BH.Engine.Geometry.Convert.ToPolyline(Circle)
- BH.Engine.Geometry.Convert.ToPolyline(Line)
- BH.Engine.Geometry.Convert.ToPolyline(Polyline)
- BH.Engine.Geometry.Convert.ToPolyline(ICurve)
- BH.Engine.Geometry.Query.IsValid(IGeometry)
- BH.Engine.Geometry.Query.IsValid(IGeometry)
- BH.Engine.Geometry.Query.ShearArea(List, Double, Double)
- BH.Engine.Geometry.Query.SliceAt(IList, Double, Double, Plane, Double)
- BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double&)
- BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double)
- BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double, Double, Double)
- BH.Engine.Geometry.Query.AreaIntegration(List, Vector, ICurve, Double, Double, Double&)
- BH.Engine.Geometry.Query.AreaIntegration(List, List, Vector, ICurve, Double, Double, Double&)
- BH.Engine.Geometry.Query.Bounds(List)

@LMarkowski could you please check if adding `this` keyword breaks the UI, and if not, then could you please refactor the code?

**Comment by pawelbaran** [comment]
@FraserGreenroyd FYI

**Comment by FraserGreenroyd** [comment]
The following methods have been checked and still need to be made extension methods:

 - BH.Engine.Geometry.Convert.ToPolyline(Line)
 - BH.Engine.Geometry.Convert.ToPolyline(Polyline)
 - BH.Engine.Geometry.Convert.IToPolyline(ICurve)
 - BH.Engine.Geometry.Query.SliceAt(IList, Double, Double, Plane, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double&)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Double, Double, Double, Double, Double, Double)
 - BH.Engine.Geometry.Query.AreaIntegration(List, Vector, ICurve, Double, Double, Double&)
 - BH.Engine.Geometry.Query.AreaIntegration(List, List, Vector, ICurve, Double, Double, Double&)

All of the others listed by @adecler and @pawelbaran have been done in the intervening time, so this is the outstanding list of methods needing the `this` keyword

**Comment by Tom-Kingstone** [comment]
on branch https://github.com/BHoM/BHoM_Engine/tree/Geometry_Engine-%23502-MakeMethodsExtensions
