### ISSUE TITLE
BHoM_Engine: Unable to acess Interfacetypes from grasshopper

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#516]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
It seems this was solved at some point:

![image](https://user-images.githubusercontent.com/16853390/72047301-32dde280-32f5-11ea-8f28-e111ba7b9568.png)
