### ISSUE TITLE
Structure_Engine: Methods with out parameters

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#528]
Some methods contain out parameters and needs to be hidden from the UI or removed.

DepthAt
WidthAt
Could be made private if methods still needed internally.

**Comment by FraserGreenroyd** [comment]
Both `DepthAt` and `WidthAt` methods have had `NotImplemented` attributes added which hides them from the UI and solves the original historic issue captured here. Any further work can be captured as new issues going forward 😄
