### ISSUE TITLE
Structure_Engine: Refactor/rewrite Unit Test Scripts to modular format

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#550]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
From 4.0 milestone planning, methods to prioritise:

Query:
- Getometry()
- Normal
- LocalOrientation
- Volume
- Mass

Modify:
- SetNormal
- SetLocalOriention

**Comment by FraserGreenroyd** [comment]
Data driven unit tests have superseded this work so closing this issue as stale based on that.
