### ISSUE TITLE
Global: Do we need a Maths_Engine?

### ISSUE THREAD

**Issue by alexradne** [BHoM/BHoM_Engine#562]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Coming back to the subject, I believe we do, same as Math_oM. I would be glad to implement `Matrix` class (it is on my list for a few months already), a few methods could also migrate (e.g. `RowEchelonForm` etc.). What do you guys think @al-fisher @epignatelli @IsakNaslundBh?

**Comment by IsakNaslundBh** [comment]
I would agree

**Comment by FraserGreenroyd** [comment]
What would a `Math_oM` and `Math_Engine` provide us that `System.Math` does not already offer?

**Comment by rwemay** [comment]
@pawelbaran , @IsakNaslundBh , @alexradne , agree, I do think we need a math engine to carry things like matrix definitions and methods. I know @alexradne raised this some time ago, needing to store engine methods for the structural Equilibriate wrapper methods. 

@FraserGreenroyd , the system.math library only provides some relatively basic methods, there are a number of engineering applications that would make use of a core math library.

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd , the system.math library only provides some relatively basic methods, there are a number of engineering applications that would make use of a core math library.

In that case have we considered `Math.NET` or similar that might provide that functionality without us having to replicate anything? Unless we wanted full ownership on the replication/don't wish to handle additional conversions (thought a `Math.Net_Toolkit` could resolve that?)? I'm just keen to make sure no one reinvents a wheel when I'm sure we can't be the first people to have encountered these problems? :smile:

**Comment by rwemay** [comment]
@FraserGreenroyd , yes could be. As usual, the preference will be to wrap rather than implement directly, so we can change dependencies later/manage multiple dependencies without these needing to be loaded multiple times.

**Comment by epignatelli** [comment]
I do agree we need a `Math` namespace. I can't see any drawback in using an external library as well. There are plenty of them. Depending on how good we want them to be, they could not be .NET, so we may need a wrapper.

Using an existing one doesn't automatically mean that its methods are exposed to UI, though. So, we may still need a wrapper around that, or a rule to expose its methods (which I don't think we ever done before @adecler).

But, either we implement it by our own or we wrap it, I still think we need a place to do it, like a Math_Engine or a Math_Toolkit to give it more freedom.

One thing I would underline is that it would be a library that supports the `Geometry` namespace, which is in the BHoM_Engine at the moment. Having a Math_Toolkit would invalidate the our dependency strategy, so I would go for the two separate modules in the BHoM_Engine and BHoM.

**Comment by epignatelli** [comment]
To reference one of the possible candidates to the math library to wrap, here is are the .NET bindings of numpy https://github.com/SciSharp/NumSharp

**Comment by IsakNaslundBh** [comment]
Have used this before: https://numerics.mathdotnet.com/ . Have worked well @alexradne

**Comment by alexradne** [comment]
I used the Math.Net package and that worked really well for me to solve some linear equations. That was for an internal BuroHappold toolkit. But I don't know the pros and cons between different packages
