### ISSUE TITLE
Structure_Engine: Add "CoordinateSystem" to filter query equality comparer for mesh results query

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#595]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
@rwemay think this can be closed now that the new MeshResultRequests have been added?

**Comment by rwemay** [comment]
Yes perfect, as MeshResultRequest has a basis property.
