### ISSUE TITLE
Environment_Engine : Query Location Curve from Analytical Panel 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#613]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
I consider this issue resolved as pushing into Revit analytical panels is working/ongoing development. Future issues to be raised if this still needs work.
