### ISSUE TITLE
Reflection_Engine: Deep Get/SetProperty

### ISSUE THREAD

**Issue by alexradne** [BHoM/BHoM_Engine#643]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This was resolved by @rwemay in [this commit](https://github.com/BHoM/BHoM_Engine/commit/e508d966189d19c4404d999e27f6542c915d08ee). Any future issues can be raised as new issues 😄
