### ISSUE TITLE
Environment_Engine: Add Create Method for InternalCondition

### ISSUE THREAD

**Issue by mariatjader** [BHoM/BHoM_Engine#650]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Internal Condition is a complex object and needs many dependent create methods to be created. Closing this issue in favour of raising more granular tasks that can be included in March/April sprints.
