### ISSUE TITLE
Structure_Engine: Query.Length should be moved to Spatial_Engine

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#690]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
@IsakNaslundBh are you OK with me deleting the existing method in Structure_Engine once #926 gets merged?

**Comment by pawelbaran** [comment]
@kThorsager is that still relevant after the recent changes related to `IElements`? I am pushing this to 3.2, please feel free to close if already resolved.

**Comment by kThorsager** [comment]
There is an equivalent method in Common_Engine as it is so the one in Structure_Engine can be deleted (as long as every place which uses it is updated), no plans to make use of it or make changes affecting it.

**Comment by pawelbaran** [comment]
Oke, in this case I am unassigning myself, leaving it for @IsakNaslundBh to resolve when appropriate

**Comment by IsakNaslundBh** [comment]
Updating title for this, as this should now target Spatial_Engine rather than Common
