### ISSUE TITLE
Reflection_Engine: RunExtensionMethod and Try

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#692]
Could be useful to have two methods for this:

1. TryRunExtensionMethod. Would do what the current one does. Tries to find the method, if it finds it Runs it, otherwise returns null. No warnings/errors/Exceptions.
2. RunExtensionMethod. Named as the current, but throwing exception/raising error if the method is not found.

To put into some context, @pawelbaran found a case where it was useful to use the RunExtensionMethod and take different actions depending if it returned a null or not. Given the method name, it does not feel like it should be used as a "null check" but be a bit more agressive if the method could not be found, either recording an error or potentionally even throwing an exception. Still this pattern might be useful, and with a slightly different name, TryRunExtensionMethod, it feels like it could be ok.

**Comment by adecler** [comment]
@IsakNaslundBh , is that still an issue ?

**Comment by FraserGreenroyd** [comment]
As we do now have a `TryRunExtensionMethod` in addition to `RunExtensionMethod`, I'm closing this issue as completed 😄 @IsakNaslundBh please feel free to reopen if you disagree!
