### ISSUE TITLE
Reflection_Engine: RunExtensionMethod upgrades

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#693]
Two things that might speed up the running of this method:

1. Find a way to store the methods that take multiple parameters as well, not just the simple ones with just one parameter.
1. Compile the methods before storing them to give improved execution speed compared to invoking the method info.

**Comment by rwemay** [comment]
Running a test on this today comparing between a store in dictionary method as opposed to looking through the list every time, there is a decent performance improvement. @IsakNaslundBh 's code tested below (note we should also fix the typo in the method name! 

![image](https://user-images.githubusercontent.com/15233608/58956898-68d34b00-8797-11e9-9a07-b04b48df37bc.png)



  /***************************************************/

        public static object RunExtentionMethod(object target, string methodName, object[] parameters)
        {
            object result = null;

            string key = target.GetType().FullName + methodName;
            foreach (object obj in parameters)
            {
                key += obj.GetType().FullName;
            }

            if (m_PreviousInvokedMethodsMultiParam.ContainsKey(key))
                return m_PreviousInvokedMethodsMultiParam[key].Invoke(null, new object[] { target }.Concat(parameters).ToArray());

            foreach (MethodInfo method in target.GetType().ExtentionMethods(methodName))
            {
                // Make sure the number of parameters is matching
                ParameterInfo[] paramInfo = method.GetParameters();
                if (paramInfo.Length != parameters.Length + 1)
                    continue;

                // Make sure the type of parameters is matching
                bool matchingTypes = true;
                for (int i = 0; i < parameters.Length; i++)
                {
                    if (!paramInfo[i + 1].ParameterType.IsAssignableFrom(parameters[i].GetType()))
                    {
                        matchingTypes = false;
                        break;
                    }
                }
                if (!matchingTypes)
                    continue;

                m_PreviousInvokedMethodsMultiParam[key] = method;

                return method.Invoke(null, new object[] { target }.Concat(parameters).ToArray());
            }

            return result;
        }


        /***************************************************/
        /**** Private fields                            ****/
        /***************************************************/

        private static Dictionary<Tuple<Type, string>, MethodInfo> m_PreviousInvokedMethods = new Dictionary<Tuple<Type, string>, MethodInfo>();
        private static Dictionary<string, MethodInfo> m_PreviousInvokedMethodsMultiParam = new Dictionary<string, MethodInfo>();



        /***************************************************/

**Comment by pawelbaran** [comment]
I believe this one got resolved already - closing now, please feel free to reopen if you disagree.
