### ISSUE TITLE
Geometry_Engine: Bounds throws breaks when objects are null

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#710]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
@epignatelli is that still relevant after superseding all nurbs?

**Comment by epignatelli** [comment]
It is, yes I think, but we might solve it in another way, not sure which.
This method is used in the UIs to set the bounding box of the entire representation. 
In the new UI we are try-catching this exceptions, but in the background it still happens. 

Happy to find a way to close this, even without actions

**Comment by pawelbaran** [comment]
Hmm, as far as I can see, the nurbs-related `Bounds` methods look as follows:

```
[NotImplemented]
public static BoundingBox Bounds(this NurbsCurve curve)
{
      throw new NotImplementedException();
}

[NotImplemented]
public static BoundingBox Bounds(this NurbsSurface surface)
{
      throw new NotImplementedException();
}
```

Am I missing something?

**Comment by epignatelli** [comment]
I suppose it was part of the bash push where we invalidated all the `NurbsSurface` method. This should be implemented if we want to render surfaces at least in Grasshopper. I am not sure about Dynamo @ZiolkowskiJakub

**Comment by rwemay** [comment]
Is 'bash push' a thing? If it's not I feel like it should be!

**Comment by epignatelli** [comment]
Ahahahahahah it probably is fantasy English, sorry, but it was very onomatopoeic.

I think this is not a bug or compliance issue anyway - I'd tag it as feature request if you agree.

**Comment by epignatelli** [comment]
To reference one of the possible candidates to the math library to wrap, here is are the .NET bindings of numpy https://github.com/SciSharp/NumSharp

**Comment by pawelbaran** [comment]
@epignatelli are you sure this is the right thread? ;)

**Comment by epignatelli** [comment]
Ops, sorry, deleting and moving, wrong one.
