### ISSUE TITLE
Serializer_Engine: Add a way to store breaking changes in types and methods

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#720]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
As we now have the Versioning workflows, I'm closing this as a non-issue.
