### ISSUE TITLE
SVG_Engine : Use RhinoCommon.dll to improve ToSVGString  for NurbsCurves

### ISSUE THREAD

**Issue by DanielJonssonBH** [BHoM/BHoM_Engine#73]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Closing as SVG_Engine no longer exists (now Graphics_Engine) and because the use of `RhinoCommon` within BHoM_Engine would be in violation of the agnostic principles of BHoM_Engine - such work would need to go into `Rhinoceros_Toolkit` or similar.
