### ISSUE TITLE
Library_Engine: Fix types namespace in libraries

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#757]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Closed by https://github.com/BHoM/BHoM_Engine/pull/759
