### ISSUE TITLE
Geometry_Engine: Enable simple transformations for NurbsCurves

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#764]
Enable simple transformations for NurbsCurves. These methods are not dependant on the basis fuctions and similar, and should just affect the ControlPoints.

**Comment by alexradne** [comment]
Related issue: https://github.com/BHoM/BHoM_Engine/issues/960
The branch for that issue implements the following method 
```C#
public static NurbsCurve Transform(this NurbsCurve curve, TransformMatrix transform)
     {
         return new NurbsCurve()
         {
             ControlPoints = curve.ControlPoints.Select(cp => cp.Transform(transform)).ToList(),
             Weights = curve.Weights,
             Knots = curve.Knots
         };
     }
```

**Comment by IsakNaslundBh** [comment]
Link to pull request where it was removed in the Nurbs cleanup push:

https://github.com/BHoM/BHoM_Engine/pull/748/files
