### ISSUE TITLE
Serialiser_Engine: Problem serialising Immutable objects with empty constructor

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#767]
For an Immutable object were we have two constructors, one setting all properties, and one being empty, there is a problem with serialisation.

The [Cartesian Coordinate System](https://github.com/BHoM/BHoM/blob/master/Geometry_oM/CoordinateSystem/Cartesian.cs) has an empty constructor, as for a lot of its use cases is is useful to be able to get out a World-XY at a specific location.

This leads to problems on the following lines:

https://github.com/BHoM/BHoM_Engine/blob/5c26468ee5afc22d21100e4fc93d6423fd6313ad/Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs#L44-L47

Deleting/commenting out these lines makes the coordinate system serialise properly. Is that check needed? By the looks of it, it seems like the code on line 60:

https://github.com/BHoM/BHoM_Engine/blob/5c26468ee5afc22d21100e4fc93d6423fd6313ad/Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs#L60

makes sure that the constructor with most parameters is used anyways.

Test file here:

![image](https://user-images.githubusercontent.com/22005920/51122021-2aa1b300-1819-11e9-9935-91ce07339b5d.png)

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue%20767-Serialisation%20of%20IImutable%20objects.gh?csf=1&e=akbMDG

**Comment by adecler** [comment]
Hmmm, that is a funny one indeed. I don't really see the point of that line either. 
Remove it for now, I cannot think of a way it would cause problem.

**Comment by IsakNaslundBh** [comment]
Cool, will do!
