### ISSUE TITLE
BHoM_Engine: Add filter and group by type methods

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#772]
Methods that would be generally useful to expose to the UI is ta ability to filter and group objects by type. Something simple as:

```
        public static List<object> FilterByType(this IEnumerable<object> list, Type type)
        {
            return list.Where(x => x.GetType().IsAssignableFrom(type)).ToList();
        }
```

and

```
        public static List<List<object>> GroupByType(this IEnumerable<object> list)
        {
            return list.GroupBy(x => x.GetType()).Select(x => x.ToList()).ToList();
        }
```

in the BHoM_Engine would be useful.

**Comment by epignatelli** [comment]
This may fit in this other issue https://github.com/BHoM/BHoM_Engine/issues/233

**Comment by IsakNaslundBh** [comment]
Yeah, think you are right. Knew this had been discussed before as well, but could not find anything.

Wonder if it is worth adding something like this kind of straight away though, as it would be very useful, until we have some larger Linq to UI solution in place?
