### ISSUE TITLE
Environment_Engine: Modify Method to UpdateOpeninngByElementID

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#798]
to allow more agnostic approach and flexibility - update opening information based on ElementID

**Comment by FraserGreenroyd** [comment]
Method needed as agreed:
 - Query method to get an opening by its `ElementID` from a collection of `BuildingElements`
 - Query method to get a host `BuildingElement` by the `ElementID` of an opening
 - Query method to get a `BuildingElement` by its `ElementID`

**Comment by michaldengusiak** [comment]
* Query method to get a `Space` by its `ElementID`
