### ISSUE TITLE
Architecture Engine - Create-methods with Name (Grid, Level)

### ISSUE THREAD

**Issue by alexradne** [BHoM/BHoM_Engine#800]
Create methods for Levels and Grids should have a Name parameter. Currently they do not. 
```c#
public static Level Level(double elevation, string name)
        {
            return new Level
            {
                Elevation = elevation,
                Name = name
            };
        }
```

**Comment by michaldengusiak** [comment]
ok we need this to have working for our Environmental_Engine so when we pull Rhino model  push gbXML we generate Name automatically from height if Name does not exist
