### ISSUE TITLE
Structure_Engine: Standard name for properties

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#820]
Could be good to add some standard naming conventions for our different property types to easy the handling of pushing objects through the different adapters.

Would basically be a string that could be generated based on the properties of the objects.

For example a 200mm ConstantThickness property with C30/37 could be called `0.2 THK - C30/37` or similar. If no name is set, this could then be used as a fallback plan.

Any comments?

**Comment by rwemay** [comment]
Looks good. Probably better to use mm in the name (and write 200mm so its clear).

**Comment by peterjamesnugent** [comment]
I like this, in the Lusas_Toolkit we use the name to store the AdapterID because you cannot force IDs for properties. So it would be something like: 

G1/0.2 THK - C30/37

We might have to change how we read the AdapterID (currently just searches for a "'/" but that can be remedied fairly easily.

**Comment by al-fisher** [comment]
Good idea!

**Comment by JosefTaylor** [comment]
We're going to get into some units issues here... if you want to convert to mm then I want to convert to inches!

**Comment by rwemay** [comment]
I think most materials that are imperial are US specific, so I think it follows that those descriptions would be in inches. Note that this is only the name tag though, the units themselves always default to metric.

**Comment by JosefTaylor** [comment]
Agreed on that. Almost never do we use UK/European materials and call out dimensions in inches, or the other way around. If you want to do that, you can set the name yourself.

**Comment by FredericBourgeon** [comment]
Chiming in on a side case, but there are some cases where the usual name for a section is different from the actual size (thinking timber, mostly on the smaller sections). Which name would be preferred in this case, usual or actual? In timber, section size varies with moisture content, should it be specified as well?

**Comment by IsakNaslundBh** [comment]
Some good input here, thanks! :)

I am fine with mm or m, but maybe should stick to standard SI in m, to not confuse it for people used to imperial?

Regarding name of sections vs the properties:
I think whatever we implemented for this would just be generic string based on the actual magnitude of the properties it consists of. For example, an un-named UB section, like `UB 356x171x53` would be called something like `I - 363.4x173.2x9.1x15.7` where the numbers describe the actual heights, widths and thicknesses. For the name to be used, the name need to be provided.

Think we still should promote naming of sections as the standard workflow and see this as a _fallback_ if that has not been done. Name should ofc also be part of any sections we serialise, which should help with keeping the standard sections consistent! :)

Regarding varying with moisture content in timber, can keep this in mind when we expand the timber capabilities. Not sure exactly what to do there right now!

**Comment by JosefTaylor** [comment]
I agree with Isak- if we're making a default name based on the material and section properties, it should be actual, not nominal. I don't want to put in a custom milled timber which is 23"x14.25" and have BHoM guess at a nominal size which would produce those actual dimensions.

If I'm picking from a catalogue, on the other hand, a 6x6 sure as heck better be 5.5"x5.5".
