### ISSUE TITLE
Environment_Engine: Exposed to Sun not always accurate

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#821]
The `ExposedToSun` method is not always accurately identifying exterior elements as being exposed to the sun.

**Comment by michaldengusiak** [comment]
adjust following for exposed to Sun:

ExposedFloor from: exposedToSun="false" to: exposedToSun="true"
Shade from: exposedToSun="false" to: exposedToSun="true" 
SlabOnGrade from: exposedToSun="true" to: exposedToSun="false"
UndergroundWall from: exposedToSun="true" to: exposedToSun="false"

**Comment by FraserGreenroyd** [comment]
Can you copy this over the XML as well @michaldengusiak as there are separate `ExposedToSun` methods, one here for generic Environment use and one in XML for XML specific use.
