### ISSUE TITLE
Structure_Engine: Asymmetric sections not correctly centred when created from profile

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Engine#825]
When using:

```
SteelSection bhomSection = new SteelSection(
   bhomProfile, area, rgy, rgz, j, iy, iz, iw,
   wely, welz, wply, wplz, centreZ, centreY, zt, zb, yt, yb, asy, asz);
```
The section is not correctly centred when the section is asymmetric. A current workaround involves using the Integrate method in BH.Engine.Structure:

```
bhomProfile = Engine.Structure.Compute.Integrate(bhomProfile, 
 oM.Geometry.Tolerance.MicroDistance).Item1;
```

The downside is that this recalculates a lot of information already pulled from the software (area, second moment of area, shear area etc.). 

```
private static IProfile AdjustCurves(IProfile profile, Vector adjustment)
{
    //Moving all curves to ensure the global origin sits in the centroid of the section.
     IProfile clone = profile.DeepClone();

    foreach (ICurve crv in clone.Edges)
   {
      AdjustCurve(crv, adjustment);
   }

    return clone;
}
```

One alternative would be to make the AdjustCurves method public, and place it in the modify class:

```
private static IProfile AdjustCurves(IProfile profile, Vector adjustment)
{
    //Moving all curves to ensure the global origin sits in the centroid of the section.
    IProfile clone = profile.DeepClone();

    foreach (ICurve crv in clone.Edges)
    {
        AdjustCurve(crv, adjustment);
    }

    return clone;
}
```

**Comment by IsakNaslundBh** [comment]
Just to clarify the above:

Curves not being centred around the origin should only be a problem if you call the constructor on the object straight away. This in itself is not a bug, as this method sits in the oM with no access to any intelligence.

Calling the Create methods for steelsections will ensure everything gets centred post the merge of https://github.com/BHoM/BHoM_Engine/pull/801.

Also agreeing on the two possible solutions:

1. Call integrate from Midas
1. Make the AdjustCurves method public.

**Comment by IsakNaslundBh** [comment]
@peterjamesnugent is this still an issue? If so, after moving to the new integration methods by @kThorsager I think this will be quicker and we could potentionally even add a "Centre profile around origin" method.

**Comment by kThorsager** [comment]
Yes, and just getting the centre point with the new method is filthy quick

**Comment by peterjamesnugent** [comment]
No longer an issue in the MidasCivil_Toolkit - the constructor is no longer implemented and the Engine method is used instead,
