### ISSUE TITLE
Environment_Engine: Adjust Material deafult

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#843]
Adjust default to allow simulation

https://github.com/BuroHappoldEngineering/EnergyPlus_Toolkit/issues/5

**Comment by FraserGreenroyd** [comment]
I don't believe this is an engine issue? According to the related issue, the imported gbXML file from the XML Toolkit into OpenStudio resulted in issues with simulation. This is a problem with whichever tool provided the data, not the Environment_Engine - the Environment_Engine only provides methods for users to create materials in visual programming environments. Any other toolkit using it should be replacing any default values with their data as appropriate.

I would recommend investigating which toolkit pulled the data wrongly and adding an issue there instead.
