### ISSUE TITLE
Environment_Engine: Add Normal for BuildingElement

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#847]
we need to have handling method for capturing normals
this is important for TAS_Toolkit, EnegyPlus_Toolkit and XML

**Comment by FraserGreenroyd** [comment]
We already have this method in the query class? We use it to query whether the normal is pointing away from the space or not?

**Comment by michaldengusiak** [comment]
ok we have these two... 

<img src="https://user-images.githubusercontent.com/26113670/53629972-d0ad4f00-3c06-11e9-9201-418095fe7534.png" width=260>

I will test if this is what we need
ps. we need to clean all unsued items  but I think this is already logged separately

**Comment by FraserGreenroyd** [comment]
Yes we could do with doing a tidy up of functions, but I think it can be done later in the March sprint or even April sprint if needs be. Ultimately they'll need deprecating in case they're being used now that we have done a release of our work. Something to consider next week.

We don't store the normal on the element from those methods, but we do correctly calculate the normal being away from the space (as far as I can tell on my tests) so will be good to see what you find :smile:

**Comment by michaldengusiak** [comment]
@FraserGreenroyd ok  I have now sample set up and issue isolated

<img src="https://user-images.githubusercontent.com/26113670/53729270-b83e6e00-3e6c-11e9-8190-5a920a0db8f1.png" width=260>

<img src="https://user-images.githubusercontent.com/26113670/53729247-a78df800-3e6c-11e9-9277-e226fed82410.png" width=360>

this not does not work for me...
here is test file.. issue is with connecting Space object
[EnvironmentalEngine_Issue847.zip](https://github.com/BHoM/BHoM_Engine/files/2926047/EnvironmentalEngine_Issue847.zip)

**Comment by pawelbaran** [comment]
Hey guys,

Just a general observation: shouldn't such methods work on `IElement2D`? Not sure, but I have an impression that a lot of methods you develop could be used not only for BEnv...

@al-fisher @rwemay maybe it would be good to do a review one day?

**Comment by rwemay** [comment]
Yes... I think there's a consolidation of similar objects at a later stage/once the MVP is working, as there are a lot of similarities between BuildingElement/Panel and PanelPlanar. There is almost certainly an interface and/or abstract that belong in a common namespace.

**Comment by FraserGreenroyd** [comment]
Following investigation this issue is not the issue at hand, closing this issue and raising separate issue to fix the problem at hand.
