### ISSUE TITLE
Environment_Engine: Fix IsContaining for space and point

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#849]
Follow on from #847 

The `IsContaining` method for a 3D space is not accurately providing a result for when a point is being contained or not. This needs to be fixed based on the algorithm discussed with @michaldengusiak

**Comment by navidhatefnia** [comment]
@FraserGreenroyd @michaldengusiak 
Here is my method for IsContaining. 
[IsContaining.zip](https://github.com/BHoM/BHoM_Engine/files/2930636/IsContaining.zip)

**Comment by michaldengusiak** [comment]
@FraserGreenroyd we should transfer this to BHoM and add as additional method
<img src="https://user-images.githubusercontent.com/26113670/53801286-ad501000-3f36-11e9-9a2d-683a567efed2.png" width=360>

@navidhatefnia 

would be good to develop new IsContainingInSpace method

**Comment by navidhatefnia** [comment]
For the 3D IsContaining I think the point has to be in 3 projected polygons of the 3D model on XY, YZ and XZ plane.

**Comment by michaldengusiak** [comment]
I just spotted we have cross reference here

https://github.com/BHoM/BHoM_Engine/issues/899
