### ISSUE TITLE
Structure_Engine: Geometry() method for PanelPlanar

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#859]
With the introduction of the PlanarSurface, https://github.com/BHoM/BHoM/pull/427, we can now return this from the Geometry() method for PanelPlanar. This should allow for automatic visualisation of the panel objects.

**Comment by pawelbaran** [comment]
Please make sure it will not interfere with the way, in which `Geometry` is used by `IElement0D` & `IElement1D` (not saying there _will_ be an issue, just mentioning).

**Comment by IsakNaslundBh** [comment]
should not, and if it would, something else fundamentally needs to change, as this is the methods called by the UIs to be able to visualise objects!

**Comment by pawelbaran** [comment]
BTW can't wait to preview the panels in GH :>
