### ISSUE TITLE
Reflection_Engine: Get and use assembly file version

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#866]
The current version used in for example `IsDeprecated` is the `AssemblyVersion` that we generally are keeping as 2.0.0.0, and not the `AssemblyFileVersion` that we are incrementing.

Example taken from Reflection_oM below (this needs to be updated to 2.3):

```
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.1.0.0")]
```

Should add a method in the Reflection_Engine to get out the `AssemblyFileVersion` for an assembly, and change to be using this in for example the `IsDeprecated` method and other places where appropriate.

Code to get this out:

```
public static Version AssemblyFileVersion(this Assembly assembly)
{
      return new Version(System.Diagnostics.FileVersionInfo.GetVersionInfo(assembly.Location).FileVersion);
}
```

**Comment by IsakNaslundBh** [comment]
The part about deprecation here will be superseded by #923 . Keeping open as still might need other parts of this method

**Comment by adecler** [comment]
Now superseded by versioning engine
