### ISSUE TITLE
Geometry_Engine: Polyline not created from GH referenced curve

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM_Engine#870]
I'm having an issue converting a Curve (being interpreted as a BH.oM.Geometry.NurbsCurve) to a Polyline. I can create  Polyline from points of a PanelPlanar though.

I'm running on the latest master branch for everything. 

[Here is an example file](https://github.com/BHoM/BHoM_Engine/files/2966995/PolylineIssue.zip)

![image](https://user-images.githubusercontent.com/10939984/54366641-eb50e080-4668-11e9-9ef1-5588993c7d86.png)

**Comment by epignatelli** [comment]
Coming from this:
![image](https://user-images.githubusercontent.com/26899347/54367602-931ade00-466a-11e9-8127-bef5121ddf35.png)

**Comment by epignatelli** [comment]
You are using the wrong overload, try using the one for Polylines. Plus it requires https://github.com/BHoM/Rhinoceros_Toolkit/issues/81 to be fixed

**Comment by IsakNaslundBh** [comment]
@epignatelli , believe this has been fixed, and was a Rhino issue, not BHoM_Engine?

**Comment by epignatelli** [comment]
Yes, thanks @IsakNaslundBh , closing this!
