### ISSUE TITLE
Structure_Engine: Add method to check loads for id assignment

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Engine#875]
Add method to check loads for id assignment to prevent Exception raised when loads are defined before having done an initial push of the geometry.

For example, when exporting bar with loads, if you try  to export both bar and load simultaneously with the same Push component you will get a `the given key is not present in the Dictionary` error on it. This is not informative to newcomers. Potential actions:

1. The exception should be caught or, better, prevented. A method should be checking loads to see if they are to be applied to bar which do not yet have an Id assigned (`bar.CustomData[AdapterId]` not existing).

2. A more meaningful error message should appear on the Push component, explaining that a first Push is needed in order to assign Ids to the bars, and then a second push component may be used to export Loads.

### Test file

This is an example file with an ETABS export.

https://burohappold.sharepoint.com/:u:/s/BHoM/ES01T4axRFxMjHx_CJ0UzhEBNebevX0PjQ_sWKSp5Xm_Lw?e=XuIIbC

The exception mentioned above happens in the `SetLoad` method in the `Load.cs` file when `SetLoadDistributed` is called:
``` 
ret = model.FrameObj.SetLoadDistributed(bar.CustomData[AdapterId].ToString(), ...
```
as `CustomData` is not already defined.

**Comment by IsakNaslundBh** [comment]
Not sure if this is really a structure_Engine issue, but might need issues raised in Etabs/Robot/Gsa/Lusas etc?
