### ISSUE TITLE
Reflection_Engine : Document fully code style in support of `BH.Engine.Reflection.Query.Url`

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#876]
Completion and review of the documentation started [here](https://github.com/BHoM/documentation/wiki/Coding-Style) by @epignatelli

**Comment by FraserGreenroyd** [comment]
Updates to documentation have occurred since this issue was raised naturally so am closing this one for the time being in favour of more recent issues for updating documentation.
