### ISSUE TITLE
Reflection_Engine: Show list of compatible types in input descriptions 

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#878]
From @alelom 's https://github.com/BHoM/Grasshopper_Toolkit/issues/339:

> For some components it's not easy to guess what is the right type of input required.
> 
> For example, consider the creation of a structural `Bar`. The input `property` description says:
> 
> > property is a ISectionProperty
> 
> but for a newcomer this is not helpful in finding out what to type in the BHoM search bar next.
> A novice won't find a type compatible with `ISectionProperty` straight away and might struggle looking for terms like "crossSection" or similar.
> 
> A workaround could be to have a **list of types types compatible with the input type in the input description**. This way the user would easily find e.g. the `SteelSection` as a valid input for the `property` input of `ISectionProperty`.
> 
> ![image](https://user-images.githubusercontent.com/6352844/54936235-f71a8d80-4f19-11e9-82b5-5e43fc4f9e19.png)
>

**Comment by alelom** [comment]
Great job @epignatelli! I really think this is immensely useful for newcomers - it makes it so much easier to see what is and isn't already implemented, and generally makes the workflow and learning process much faster.
