### ISSUE TITLE
BHoM_Engine: Build error if user folder does not match account name

### ISSUE THREAD

**Issue by epersson** [BHoM/BHoM_Engine#883]
My windows user account name "Epersson" does not match my user folder name, "einar.persson".

Building the BHoM_Engine yields an error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "C:\Windows\System32\xcopy "C:\Users\einar.persson\BHoM\BHoM_Engine\Library_Engine\DataSets\*.*" "C:\Users\Epersson\AppData\Roaming\BHoM\DataSets" /Y /I /E" exited with code 4.	Library_Engine	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	5020
```	
Running the BHoM installer returns loading errors when launching rhino/gh:
```
Object: CreateDataComponent (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: CreateDataComponent (level 2)
{
  Could not find a part of the path 'C:\Users\Epersson\AppData\Roaming\BHoM\DataSets'.
  DirectoryNotFoundException
}

Object: CreateBHoMData (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: CreateBHoMData (level 2)
{
  Could not find a part of the path 'C:\Users\Epersson\AppData\Roaming\BHoM\DataSets'.
  DirectoryNotFoundException
}
```

**Comment by epignatelli** [comment]
Hi @epersson ! Thanks for flagging this up. 

Changing the post-build events to this:
`C:\Windows\System32\xcopy "$(ProjectDir)DataSets\*.*" "$(Appdata)\BHoM\DataSets" /Y /I /E`
should do the trick.

Would you mind testing it and in case it works pushing the fix?

**Comment by epersson** [comment]
Hi @epignatelli 

That worked, thank you. BHoM_Engine now builds successfully.

What is the proper procedure resolving issues? I do not yet have access to create a new branch for the issue.

**Comment by epignatelli** [comment]
https://github.com/BHoM/documentation/wiki/Resolving-an-Issue should be able to guide you during the process. 

For the access, you should have received an email to enable access to branching by now! If not, let me know.

**Comment by al-fisher** [comment]
Hi @epersson have added you as member now - thanks
