### ISSUE TITLE
Geometry Engine: ClosestPoint(arc, point) returns different values when point is in arc centre

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_Engine#896]
When arc angle is smaller then circa 2.09 (rad) method returns correct value (in this case - radius of the arc).
For greater angles it returns 0.

![image](https://user-images.githubusercontent.com/48125514/55730784-446a2500-5a19-11e9-859b-a64496805b59.png)
![image](https://user-images.githubusercontent.com/48125514/55730798-4df38d00-5a19-11e9-80c1-94f5eaf11781.png)
-------------
![image](https://user-images.githubusercontent.com/48125514/55730634-edfce680-5a18-11e9-97d6-600540386e29.png)
![image](https://user-images.githubusercontent.com/48125514/55730655-f81ee500-5a18-11e9-842a-2ab00289f25a.png)
--------------
![image](https://user-images.githubusercontent.com/48125514/55730688-0c62e200-5a19-11e9-9932-48248bc474b4.png)
![image](https://user-images.githubusercontent.com/48125514/55730707-1a186780-5a19-11e9-9347-c39296b15e94.png)
--------------
![image](https://user-images.githubusercontent.com/48125514/55730840-5ba91280-5a19-11e9-8fe0-f31b3becf6cb.png)
![image](https://user-images.githubusercontent.com/48125514/55730851-62d02080-5a19-11e9-955d-b2d1a62874ef.png)

**Comment by LMarkowski** [comment]
Distance directly refers to ClostestPoint, so the problem might be there

**Comment by pawelbaran** [comment]
At the first sight looks like a relatively easy one - hope you will manage to resolve it _in the meantime_ 😄

**Comment by LMarkowski** [comment]
It turned out that issue was caused by ClosestPoint, not Distance. I renamed the issue and fixed ClosestPoint() in PR #904
