### ISSUE TITLE
Common_Engine : Query.Normal fails on Panels with Circular Boundaries

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#902]
See failing test file [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FCommon_Engine%2FCommon_Engine-Issue902-NormalQueryOnCircularPanel&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

**Comment by pawelbaran** [comment]
@LMarkowski I reckon this is something dependent on your Geometry_Engine method.
