### ISSUE TITLE
Structure_Engine: Add method for setting material to bars

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#903]
Overriding the materials to bars is doable with get and set property, but a bit fiddely. Deservs its own method.

Addition of a `SetMaterial(Bar, Material)` proposed in the Structure_Engine.

Important to remember to make all necessary cloning of 1. that bar and 2. the sectionproperty before assigning the new material.

![image](https://user-images.githubusercontent.com/22005920/56024251-893ad800-5d07-11e9-8b85-6db506ae9a53.png)

**Comment by PiotrBuda** [comment]
Sample GH Script for testing:
[https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=w3LMVj&cid=1cabe4cd-378f-4aaf-a05f-2e0b555da13d&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FStructure_Engine%2FModify](url)
