### ISSUE TITLE
Library_Engine : Review validity of library json files

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#912]
As raised by @epignatelli here https://github.com/BHoM/BHoM_Engine/pull/909 review json files.

**Comment by adecler** [comment]
Probably good to have @IsakNaslundBh and @alelom  involved in this conversation here. I am perfectly fine with the way json is stored right now but I remeber conversations about the possibility of storing as a single dataset object that would contain additional info (e.g. Time of creation, creator name,...)

**Comment by adecler** [comment]
Is this still relevant ?

**Comment by IsakNaslundBh** [comment]
Think still relevant, but can be superseeded by https://github.com/BHoM/Test_Toolkit/issues/187
