### ISSUE TITLE
Geometry_Engine: BooleanUnion(Polylines) error

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_Engine#919]
![image](https://user-images.githubusercontent.com/48125514/56815569-fb500880-6841-11e9-8b1a-ccb02df4cb8c.png)
![image](https://user-images.githubusercontent.com/48125514/56815614-17ec4080-6842-11e9-8a62-fd2c8b8a35c9.png)

**Comment by pawelbaran** [comment]
@LMarkowski please add the description, labels and the test file

**Comment by LMarkowski** [comment]
This issue is no longer relevant as this method was updated in PR #920 and now works fine
