### ISSUE TITLE
BHoM_Engine : Solid Geometry Create Methods for Primitives

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#921]
Create Create methods for:
- [ ] Sphere
- [ ] Torus
- [ ] Cone
- [ ] Cylinder
- [ ] Cuboid

**Comment by pawelbaran** [comment]
@al-fisher looks like the code is in place. is this one still relevant?

**Comment by pawelbaran** [comment]
The methods are in place, closing this one.
