### ISSUE TITLE
Environment_Engine: Fix Missing Roof

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#928]
Sometimes not all surfaces are exported and we need to introduce method of fixing and healing model

![image](https://user-images.githubusercontent.com/26113670/57010263-b9cdad80-6bf3-11e9-895b-166939e26a3d.png)

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue927-FixAirSurfacesforExternalSurfaces?csf=1&e=SqnRdU)

**Comment by FraserGreenroyd** [comment]
Closed as this is issue with the toolkit which pulled the surface (in this instance, Revit Toolkit).
