### ISSUE TITLE
Environment_Engine: Fix Missing Wall

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#929]
Sometimes not all surfaces are exported and we need to introduce method of fixing and healing model, will cross reference this to Revit_Toolkit as this is source of problem

![image](https://user-images.githubusercontent.com/26113670/57010414-60b24980-6bf4-11e9-9a36-f02d2684a211.png)

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue927-FixAirSurfacesforExternalSurfaces?csf=1&e=SqnRdU)

**Comment by FraserGreenroyd** [comment]
Closed as this is issue with the toolkit which pulled the surface (in this instance, Revit Toolkit).
