### ISSUE TITLE
Environment_Engine: Fix Normal 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#930]
new IsContraining method works excellent and for most project is 100% accurate however with our new template I come across one surface that is failing

![image](https://user-images.githubusercontent.com/26113670/57012261-6eb89800-6bfd-11e9-8e22-b782a44ec60d.png)

![image](https://user-images.githubusercontent.com/26113670/57012266-74ae7900-6bfd-11e9-94f3-2979c955f920.png)

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-930%20Normal_IsContaining?csf=1&e=zTDVPo)

also please refer to https://github.com/BHoM/BHoM_Engine/issues/899 for detail GH example

**Comment by michaldengusiak** [comment]
I come across second instance with wrong normal,
I added new test case to test location from above

![image](https://user-images.githubusercontent.com/26113670/59464837-69b44e80-8e21-11e9-8f2c-b1b4c00a9c0a.png)

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  I added `BHoMgbXML_GHNormal.json` so we have just one space with wrong panel normal for `Panel-503`

**Comment by FraserGreenroyd** [comment]
Excellent cheers @michaldengusiak this will be helpful - let's go through this tomorrow :smile:

**Comment by michaldengusiak** [comment]
ok I isolated now problem to specific case
I will use this issue to document this and add file here as well, 

Good news is that we have correct normals on input and then we break it when we run check Query `NormalAwayFromSpace` as it return false we flip normal. 

I will start exploding now step by step to see where problem is

![image](https://user-images.githubusercontent.com/26113670/63025241-af80a800-bea0-11e9-9961-5f75b5893abe.png)
