### ISSUE TITLE
Environment_Engine: Fix slivers to correct type

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#931]
sometimes there are stripes of internal floor that are exposed due to snapping issue. 
We need to apply fix if possible for horizontal surfaces get roof data and apply roof type, exposed etc... or make it exposed adiabatic surface

![image](https://user-images.githubusercontent.com/26113670/57012464-978d5d00-6bfe-11e9-92df-9841a80910bc.png)

![image](https://user-images.githubusercontent.com/26113670/57012737-e12a7780-6bff-11e9-93a2-b63823a93eea.png)

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-930%20Normal_IsContaining?csf=1&e=zTDVPo)

**Comment by FraserGreenroyd** [comment]
There is a method in the engine for `SetTypeByAdjacencies` which should cover the use case outlined above :smile: Feel free to reopen if a more specific method is needed!
