### ISSUE TITLE
Speech_Engine : Refactor to BHoM 2.0

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#94]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by al-fisher** [comment]
This experimental engine was refactored out from the core engines removing the requirement for this

**Comment by FraserGreenroyd** [comment]
Reopening following discussion as Speech Engine does still exist just not part of build processes so will still need to be updated (but to BHoM 6.0 rather than 2.0).

**Comment by al-fisher** [comment]
As discussed will remove this legacy code from the core Engine as originated from an early prototype hack.
If anyone would be interested in implementing similar functionally in the future this can perhaps be done as a specialised Toolkit rather than in the core.
