### ISSUE TITLE
Geometry_Engine: Remove Query.Centre(Polyline) 

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#944]
`Query.Centre(Polyline)` is wrong and should be removed (deprecated). Any references to be changed to `Centroid`.

**Comment by LMarkowski** [comment]
@FraserGreenroyd, I see this one is being used in `TopRight`, `BottomRight`, `BottomLeft` and `NormalAwayFromSpace` methods in the Environment Engine. It is only being called if `Centroid()` fail. Are you ok with removing it from your methods or would you rather replace it with `Average()` (which is what `Centre()` actually returns)?

**Comment by FraserGreenroyd** [comment]
@LMarkowski the back up is helpful, so if we're removing `Centre` completely and `Average()` returns the same result, I'd like to switch it over to that if we can.
