### ISSUE TITLE
Environment_Engine: Adjust Uvalue for transparent construction

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#954]
We need to adjust Uvalue cals for transparent materials according to BS EN 673-2011.

test file and resource here:

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue208_Constructions?csf=1&e=quuuMW)

**Comment by FraserGreenroyd** [comment]
This issue has not been requested by others or had any movement since 2019, so is being closed pending further information requiring deliberation :smile: please feel free to reopen if further information is available to assist with this.
