### ISSUE TITLE
Geometry_Engine: Convert.toNurbsCurve(Arc) 

### ISSUE THREAD

**Issue by alexradne** [BHoM/BHoM_Engine#960]
The method `Convert.toNurbsCurve(Arc)` is needed for the `Extrude(Bar)` method to show sections with rounded profiles. 
Out of curiosity I spent an hour to research Nurbcurves and implement this.
 
But It seems like we can't display extrusion geometries in grasshopper yet. So it does not solve it completely yet

**Comment by alexradne** [comment]
How to create a circle segment nurbs curve:
https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/NURBS/RB-circles.html

Test Script:
In [test scripts folder](https://burohappold.sharepoint.com/:f:/s/BHoM/EvUOE3tGNy5AviWnk2C-NEQB34hGy5ic0eapcgRDMt7WbA?e=ZrRtoZ)

**Comment by epignatelli** [comment]
I think it's time we can discuss about introducing two resolutions of rendering in the UI (at least in Grasshopper): the physical resolution and the analytical resolution.

e.g. a bar has a line as analytical geometry, a T-shaped extrusion as physical geometry
@al-fisher @rwemay @adecler @IsakNaslundBh @FraserGreenroyd any thought?

**Comment by IsakNaslundBh** [comment]
Think we had this already, at least we did have it at one point. Can be worth looking through some old commits for the code.

**Comment by IsakNaslundBh** [comment]
and @epignatelli I agree. In terms of visualisation we already have (or at least had) two options, extruded or centre line. Right now the `Geometry()` method for both the framingelements and the bars return the centreline geometry, as often more useful and significantly lighter. If something else is wanted (extruded) you have to call it explicitly.

Are you envisaging some global setting or something else?

**Comment by epignatelli** [comment]
Yes, it was one of my though to replicate the grasshopper behaviour of "wireframe" or "meshes" rendering. Do you see the need from the designer point of view?

I'd rather not overriding the normal grasshopper behaviour - we might want to display meshes of grasshopper objects and wireframe of bhom objects.
It may be just a component you drop on the canvas that modifies the behaviour or an entry in the grasshopper menu.
