### ISSUE TITLE
BHoM_Engine: How to use query dictionary?

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#972]
How to create and then query dictionary?

I want to attach to Panel dictionary with some data. In first step will be Panel Name. So in external tools panel will hold some data and when operations will be done we can keep reference. 

I think I set it up but not sure how to query data to confirm it was correctly constructed?
Any help and clarification or alternative method really appreciated. This needs to be dictionary. 

![image](https://user-images.githubusercontent.com/26113670/58094054-b2346f80-7bc7-11e9-9fc2-02a87b549e78.png)

**Comment by adecler** [comment]
Difficult to help you with so little context but here's a few pointers that will hopefully get you on the right track:
- If you check the `Equalities` input of the `FilterQuery` component, you will notice that it requires a `Dictionary<string, object>`. You are creating a `Dictionary<object,string>`
- The `Equalities` input of the `FilterQuery` is a flex input used differently by each adaptor depending on the range of equalities they want to cover. If you check [the code of the Pull for the BHoM_Adapter itself](https://github.com/BHoM/BHoM_Adapter/blob/12304b8fc904cd4be17101e7f7cd23854a060e4f/BHoM_Adapter/BHoMAdapter.cs#L103), you will find what is actually supported on that level. Doing the same on a specific adapter should give you more details in case it is not documented directly in the wiki of the corresponding repo.
