### ISSUE TITLE
Geometry_Engine: Query SubPart does not work

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#973]
BH.Engine.Query SubParts for PolyCurve does not work in Dynamo

![image](https://user-images.githubusercontent.com/26113670/58094456-a1d0c480-7bc8-11e9-8a50-d4907f23fee4.png)

**Comment by pawelbaran** [comment]
No clue how can this happen, looks like there is no code ending with `NotImplementedException` in the Geometry_Engine. I bet this is a Dynamo_Toolkit issue, would rather port it to https://github.com/BHoM/Dynamo_Toolkit

**Comment by pawelbaran** [comment]
This is definitely a Dynamo_Toolkit issue, the method works fine on the BHoM_Engine side. Closing.
