### ISSUE TITLE
Environment_Engine: Calculate Vapour Diffusion

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#978]
With the oM changes we now have `VapourResistivity` as a property of material types. The Vapour Diffusion Factor is then a calculated function when we have a thickness of when the material is used on a `Layer` object.

Currently, a basic calculation of:

`VapourResistivity` / `air vapour resistivity (5GN·s/kg·m)` / `layer thickness`

Is being assumed, with the reverse calculation providing `VapourResistivity` from a `VapourDiffusionFactor`.

So the question becomes, is this the valid calculation and will it work for the majority of our cases or do we need to consider a more complex/different algorithm for calculating `VapourDiffusion` from `VapourResistivity`?

Note, we cannot store `VapourDiffusion` on the `Layer` object because that is the physical object shared between disciplines, though we may be able to look at a Fragment which the `Layer` object could store with this data if this algorithm becomes too complex. But ideally, the calculation will exist somewhere we just need to use the right one! :smile:

**Comment by michaldengusiak** [comment]
ok I started some conversation in [BHoM PR ](https://github.com/BHoM/BHoM/pull/490) on this

here is some example and also I await confirmation on this from different source:
http://www.builddesk.co.uk/wp-content/uploads/2013/01/vapourResistances.pdf

**Comment by rboulton-BH** [comment]
Doesn't appear to be demand to push this issue any further and we already have some functionality so I'm going to close the issue
