### ISSUE TITLE
Units_Engine: Add units engine projects 

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#981]
Need to standardise the way we handle different units when needed.

Suggestion to make convertions to and from SI only. can then be stringed together when needed. For example mm -> inches would be mm->m->inches

**Comment by FraserGreenroyd** [comment]
@tg359 has done some work on this in Environments, might be worthwhile getting his input/converting some of his existing stuff for this :smile:

**Comment by tg359** [comment]
I've used [Units.NET](https://github.com/angularsen/UnitsNet) on some of the S&P code. It's really well documented, widely used, and there's no point reinventing the wheel as it seems to have conversions for pretty much any obscure unit there is (including from Poundals to Dyne).

**Comment by rwemay** [comment]
I don’t think BHoM_Engine should have any dependencies so if wrapping another units conversion it should be a separate repo. Im also uncomfortable with excessively relying on something else to convert/wrap all conversions so we should implement on an as needed basis, and things need to be heavily tested. The issue of risk/open source came up again in an event this week, reinforcing that we must make sure anything we wrap or write is fully documented and tested. @al-fisher  thoughts?

**Comment by al-fisher** [comment]
Agreed. Two things.
1. Separate Units_Toolkit Repo should be the correct approach. This will allow the Core BHoM_Engine to a) remain independent and b) importantly keep clarity over BHoM and BHoM_Engine being exclusively SI. Reducing risk of unit confusion and creep.
Can control dependences (on Unit_Engine too) very deliberately for Converts in Adapter Toolkits etc.
2. Secondly, incremental implementation inline with demand makes sense, especially when we add the compliance requirement of unit tests to be implemented in advance of merge.
This latest increase in requirements, being rolled out gradually as discussed, is certainly recommended for code of this sensitivity. 
@FraserGreenroyd @tg359 hope all makes sense?

**Comment by al-fisher** [comment]
Picking up the conversation with my past self ... 

> Separate Units_Toolkit Repo should be the correct approach. 

The key point made above is that the BHoM and BHoM_Engine should not have dependency on Units_Engine. 
Option as alternative to a whole repo called Units_Toolkit Repo is to have a Units_Engine new project inside the BHoM_Adapter. It is after all the Adapter and its converts that will rely on this capability - as well as the BHoM_UI who depends on Adapter already.

The other option is to go broader and include units inside a new Localisation_Toolkit ? Which again only Adapter and UI should depend on/utilise.
@FraserGreenroyd @rwemay

**Comment by IsakNaslundBh** [comment]
Some comments after discussion with @FraserGreenroyd :

- 100% agree to not keep it in the core engine for the reasons given by @al-fisher . BHoM and BHoM_Enigne _need_ to always be in SI
- Not sure about putting this in the core adapter, as I think it could have use-cases outside + it does not really feel like a natural home for it imo.
- Would rather put it in a Localisation_Toolkit to then be used by adapters and UI.
- Can then also potentially be used in special cases for toolkits where other units might be required, such as codified calcs etc.

**Comment by FraserGreenroyd** [comment]
This has been resolved by the creation of [Localisation_Toolkit](https://github.com/BHoM/Localisation_Toolkit) :smile:
