### ISSUE TITLE
Reflection Engine: Access Object information within an Object

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/BHoM_Engine#982]
Enable get property to access properties of objects within objects, thus preventing the need for example below.

![image](https://user-images.githubusercontent.com/34092831/58344447-9d690d80-7e4d-11e9-9363-50e3af497f3d.png)

Suggestion syntax could be using "." hence in this example "SectionProperty.Name" could be used to access the section name for the list of BHoM bars.

**Comment by rwemay** [comment]
Like! We were just speaking about this this week. Should be for get and set I think.

**Comment by epignatelli** [comment]
@jdarcyBHE would you mind uploading the file of the screenshot?
